/**
 * Default Report Designs Seed
 *
 * Seeds one default AnkaReport layout per entity into sys_report_designs.
 * The layout renders a two-column (label | value) view of every field.
 * Administrators can open Admin → Report Designs to customise any layout.
 *
 * Generated: 2026-08-29T04:45:21.927Z
 */

import { type Kysely } from 'kysely';

interface FieldRow {
  label: string;
  field: string;
}

interface ReportItem {
  type: string;
  x: number;
  y: number;
  width: number;
  height: number;
  text?: string;
  binding?: string;
  style?: Record<string, string | number>;
}

interface ReportLayout {
  headerSection: { height: number; items: ReportItem[] };
  contentSection: { height: number; binding: string; items: ReportItem[] };
  footerSection: { height: number; items: ReportItem[] };
}

function toLabel(columnName: string): string {
  return columnName
    .replace(/_id$/, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function buildLayout(entityName: string, fields: FieldRow[]): ReportLayout {
  const ROW_H = 24;
  const GAP = 4;
  const LABEL_W = 180;
  const VALUE_W = 370;
  const START_Y = 8;
  const contentH = Math.max(fields.length * (ROW_H + GAP) + START_Y + 12, 60);

  const items: ReportItem[] = [];
  fields.forEach((f, i) => {
    const y = START_Y + i * (ROW_H + GAP);
    items.push({ type: 'text', x: 10, y, width: LABEL_W, height: ROW_H, text: `${f.label}:`, style: { fontWeight: 'bold', fontSize: 11, color: '#374151' } });
    items.push({ type: 'text', x: LABEL_W + 20, y, width: VALUE_W, height: ROW_H, binding: f.field, style: { fontSize: 11, color: '#111827' } });
  });

  return {
    headerSection: {
      height: 56,
      items: [{ type: 'text', x: 10, y: 14, width: 560, height: 32, text: `${entityName} Report`, style: { fontSize: 20, fontWeight: 'bold', color: '#0f4c75' } }],
    },
    contentSection: { height: contentH, binding: 'records', items },
    footerSection: {
      height: 28,
      items: [{ type: 'text', x: 10, y: 6, width: 560, height: 20, text: 'Generated by APPWITHAI', style: { fontSize: 9, color: '#9ca3af', textAlign: 'center' } }],
    },
  };
}

const entityReports: Array<{ tableName: string; displayName: string; columns: string[] }> = [
  {
    tableName: 'bus_user',
    displayName: 'User',
    columns: [
      'email',
      'first_name',
      'last_name',
      'role',
      'job_title',
      'phone',
      'team_id',
      'quota_annual',
      'is_active',
      'last_login',
    ],
  },
  {
    tableName: 'bus_team',
    displayName: 'Team',
    columns: [
      'name',
      'manager_id',
      'region',
      'quota_annual',
      'is_active',
    ],
  },
  {
    tableName: 'bus_territory',
    displayName: 'Territory',
    columns: [
      'name',
      'region',
      'country_code',
      'manager_id',
      'employee_count_floor',
      'employee_count_ceiling',
      'is_active',
    ],
  },
  {
    tableName: 'bus_account',
    displayName: 'Account',
    columns: [
      'name',
      'account_number',
      'account_type',
      'tier',
      'industry',
      'website',
      'phone',
      'billing_street',
      'billing_city',
      'billing_postal_code',
      'billing_country',
      'employee_count',
      'annual_revenue',
      'health_score',
      'territory_id',
      'sla_policy_id',
      'status',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_contact',
    displayName: 'Contact',
    columns: [
      'account_id',
      'first_name',
      'last_name',
      'email',
      'phone',
      'mobile',
      'job_title',
      'department',
      'lead_source',
      'is_primary',
      'email_opt_out',
      'do_not_call',
      'status',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_lead',
    displayName: 'Lead',
    columns: [
      'first_name',
      'last_name',
      'company_name',
      'email',
      'phone',
      'job_title',
      'industry',
      'employee_count',
      'annual_revenue',
      'lead_source',
      'rating',
      'score',
      'campaign_id',
      'status',
      'owner_id',
      'converted_at',
      'disqualification_reason',
    ],
  },
  {
    tableName: 'bus_campaign',
    displayName: 'Campaign',
    columns: [
      'name',
      'campaign_type',
      'status',
      'start_date',
      'end_date',
      'budgeted_cost',
      'actual_cost',
      'expected_revenue',
      'expected_response_count',
      'target_audience',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_campaign_member',
    displayName: 'Campaign Member',
    columns: [
      'campaign_id',
      'lead_id',
      'contact_id',
      'member_status',
      'responded_at',
      'has_responded',
    ],
  },
  {
    tableName: 'bus_opportunity',
    displayName: 'Opportunity',
    columns: [
      'account_id',
      'contact_id',
      'campaign_id',
      'name',
      'description',
      'amount',
      'currency_code',
      'stage',
      'probability',
      'forecast_category',
      'expected_close_date',
      'actual_close_date',
      'lead_source',
      'next_step',
      'loss_reason',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_opportunity_line_item',
    displayName: 'Opportunity Line Item',
    columns: [
      'opportunity_id',
      'product_id',
      'quantity',
      'unit_price',
      'discount_percent',
      'line_total',
      'line_description',
    ],
  },
  {
    tableName: 'bus_product',
    displayName: 'Product',
    columns: [
      'product_code',
      'name',
      'description',
      'family',
      'list_price',
      'unit_cost',
      'billing_frequency',
      'is_active',
    ],
  },
  {
    tableName: 'bus_quote',
    displayName: 'Quote',
    columns: [
      'quote_number',
      'opportunity_id',
      'account_id',
      'name',
      'status',
      'version_number',
      'valid_until',
      'subtotal',
      'discount_percent',
      'discount_amount',
      'tax_amount',
      'grand_total',
      'approved_by_id',
      'approved_at',
      'approval_notes',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_quote_line_item',
    displayName: 'Quote Line Item',
    columns: [
      'quote_id',
      'product_id',
      'quantity',
      'unit_price',
      'discount_percent',
      'line_total',
      'sort_order',
    ],
  },
  {
    tableName: 'bus_contract',
    displayName: 'Contract',
    columns: [
      'contract_number',
      'account_id',
      'quote_id',
      'status',
      'start_date',
      'end_date',
      'term_months',
      'annual_value',
      'auto_renew',
      'renewal_notice_days',
      'signed_by_id',
      'signed_at',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_support_case',
    displayName: 'Support Case',
    columns: [
      'case_number',
      'account_id',
      'contact_id',
      'sla_policy_id',
      'subject',
      'description',
      'case_type',
      'priority',
      'origin',
      'status',
      'first_response_due_at',
      'first_response_at',
      'resolution_due_at',
      'resolved_at',
      'is_sla_breached',
      'resolution_notes',
      'satisfaction_score',
      'escalated_by_id',
      'owner_id',
    ],
  },
  {
    tableName: 'bus_sla_policy',
    displayName: 'Sla Policy',
    columns: [
      'name',
      'tier',
      'first_response_minutes',
      'resolution_hours',
      'business_hours_only',
      'is_active',
    ],
  },
  {
    tableName: 'bus_activity',
    displayName: 'Activity',
    columns: [
      'activity_type',
      'subject',
      'description',
      'status',
      'priority',
      'due_at',
      'completed_at',
      'duration_minutes',
      'account_id',
      'contact_id',
      'lead_id',
      'opportunity_id',
      'support_case_id',
      'contract_id',
      'owner_id',
    ],
  },
];

export async function seed(db: Kysely<any>): Promise<void> {
  for (const entity of entityReports) {
    if (entity.columns.length === 0) continue;
    const fields: FieldRow[] = entity.columns.map((col) => ({ label: toLabel(col), field: col }));
    const layout = buildLayout(entity.displayName, fields);
    await db
      .insertInto('sys_report_designs')
      .values({
        table_name: entity.tableName,
        name: `${entity.displayName} Default Report`,
        layout: JSON.stringify(layout),
      })
      .onConflict((oc) => oc.column('table_name').doNothing())
      .execute();
  }
  console.log('✓ Default report designs seeded');
}
