/**
 * Test Setup for crm Backend
 * Generated by ERDwithAI
 *
 * Provides test utilities, fixtures, and database setup
 */

import { Test, TestingModule } from '@nestjs/testing';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { KYSELY_CONNECTION } from '../src/database/database.constants';
import {
  Kysely,
  DummyDriver,
  PostgresAdapter,
  PostgresIntrospector,
  PostgresQueryCompiler,
} from 'kysely';

// Use a no-op dialect for tests instead of SQLite/PostgreSQL.
// Queries compile but return empty results, which avoids native module
// loading and database provisioning in test environments.

// Test database instance
let testDb: Kysely<any>;

// Test application instance
let testApp: NestFastifyApplication;

/**
 * Initialize test database connection
 */
export async function initTestDatabase(): Promise<Kysely<any>> {
  if (!testDb) {
    // No-op dialect (no native modules required)
    testDb = new Kysely({
      dialect: {
        createAdapter: () => new PostgresAdapter(),
        createDriver: () => new DummyDriver(),
        createIntrospector: (db) => new PostgresIntrospector(db),
        createQueryCompiler: () => new PostgresQueryCompiler(),
      },
    });
  }
  return testDb;
}

/**
 * Close test database connection
 */
export async function closeTestDatabase(): Promise<void> {
  if (testDb) {
    try {
      await testDb.destroy();
    } catch (_e) {
      // Already closed
    }
    testDb = undefined as any;
  }
}

/**
 * Create test application
 */
export async function createTestApp(module: any): Promise<NestFastifyApplication> {
  const builder = Test.createTestingModule({
    imports: [module],
  });

  // Override KYSELY_CONNECTION with the shared test database so the NestJS app
  // uses the same in-memory SQLite database as the test helpers.
  if (testDb) {
    builder.overrideProvider(KYSELY_CONNECTION).useValue(testDb);
  }

  const moduleFixture: TestingModule = await builder.compile();

  const app = moduleFixture.createNestApplication<NestFastifyApplication>(
    new FastifyAdapter()
  );

  // Match production configuration
  app.setGlobalPrefix('api');

  await app.init();
  await app.getHttpAdapter().getInstance().ready();

  return app;
}

/**
 * Close test application
 */
export async function closeTestApp(app: NestFastifyApplication): Promise<void> {
  if (app) {
    await app.close();
  }
}

/**
 * Generate test UUID
 */
export function generateTestId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Test data factories
 */
export const TestDataFactory = {
  /**
   * Create test User data
   */
  createUser(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      email: `test-${uid}@example.com`,
      first_name: `Test First Name ${uid}`,
      last_name: `Test Last Name ${uid}`,
      role: `Test Role ${uid}`,
      job_title: `Test Job Title ${uid}`,
      phone: `Test Phone ${uid}`,
      team_id: `Test Team Id ${uid}`,
      quota_annual: 10.99,
      is_active: true,
      last_login: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test Team data
   */
  createTeam(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      manager_id: `Test Manager Id ${uid}`,
      region: `Test Region ${uid}`,
      quota_annual: 10.99,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Territory data
   */
  createTerritory(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      region: `Test Region ${uid}`,
      country_code: `Test Country Code ${uid}`,
      manager_id: `Test Manager Id ${uid}`,
      employee_count_floor: 1,
      employee_count_ceiling: 1,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Account data
   */
  createAccount(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      account_number: `Test Account Number ${uid}`,
      account_type: `Test Account Type ${uid}`,
      tier: `Test Tier ${uid}`,
      industry: `Test Industry ${uid}`,
      website: `Test Website ${uid}`,
      phone: `Test Phone ${uid}`,
      billing_street: `Test Billing Street ${uid}`,
      billing_city: `Test Billing City ${uid}`,
      billing_postal_code: `Test Billing Postal Code ${uid}`,
      billing_country: `Test Billing Country ${uid}`,
      employee_count: 1,
      annual_revenue: 10.99,
      health_score: 1,
      territory_id: `Test Territory Id ${uid}`,
      sla_policy_id: `Test Sla Policy Id ${uid}`,
      status: `Test Status ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Contact data
   */
  createContact(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      account_id: `Test Account Id ${uid}`,
      first_name: `Test First Name ${uid}`,
      last_name: `Test Last Name ${uid}`,
      email: `test-${uid}@example.com`,
      phone: `Test Phone ${uid}`,
      mobile: `Test Mobile ${uid}`,
      job_title: `Test Job Title ${uid}`,
      department: `Test Department ${uid}`,
      lead_source: `Test Lead Source ${uid}`,
      is_primary: true,
      email_opt_out: true,
      do_not_call: true,
      status: `Test Status ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Lead data
   */
  createLead(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      first_name: `Test First Name ${uid}`,
      last_name: `Test Last Name ${uid}`,
      company_name: `Test Company Name ${uid}`,
      email: `test-${uid}@example.com`,
      phone: `Test Phone ${uid}`,
      job_title: `Test Job Title ${uid}`,
      industry: `Test Industry ${uid}`,
      employee_count: 1,
      annual_revenue: 10.99,
      lead_source: `Test Lead Source ${uid}`,
      rating: `Test Rating ${uid}`,
      score: 1,
      campaign_id: `Test Campaign Id ${uid}`,
      status: `Test Status ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      converted_at: new Date().toISOString(),
      disqualification_reason: `Test Disqualification Reason ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Campaign data
   */
  createCampaign(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      campaign_type: `Test Campaign Type ${uid}`,
      status: `Test Status ${uid}`,
      start_date: '2024-01-15',
      end_date: '2024-01-15',
      budgeted_cost: 10.99,
      actual_cost: 10.99,
      expected_revenue: 10.99,
      expected_response_count: 1,
      target_audience: `Test Target Audience ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test CampaignMember data
   */
  createCampaignMember(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      campaign_id: `Test Campaign Id ${uid}`,
      lead_id: `Test Lead Id ${uid}`,
      contact_id: `Test Contact Id ${uid}`,
      member_status: `Test Member Status ${uid}`,
      responded_at: new Date().toISOString(),
      has_responded: true,
      ...overrides,
    };
  },

  /**
   * Create test Opportunity data
   */
  createOpportunity(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      account_id: `Test Account Id ${uid}`,
      contact_id: `Test Contact Id ${uid}`,
      campaign_id: `Test Campaign Id ${uid}`,
      name: `Test Name ${uid}`,
      description: 'Test text content',
      amount: 10.99,
      currency_code: `Test Currency Code ${uid}`,
      stage: `Test Stage ${uid}`,
      probability: 1,
      forecast_category: `Test Forecast Category ${uid}`,
      expected_close_date: '2024-01-15',
      actual_close_date: '2024-01-15',
      lead_source: `Test Lead Source ${uid}`,
      next_step: `Test Next Step ${uid}`,
      loss_reason: `Test Loss Reason ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test OpportunityLineItem data
   */
  createOpportunityLineItem(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      opportunity_id: `Test Opportunity Id ${uid}`,
      product_id: `Test Product Id ${uid}`,
      quantity: 10.99,
      unit_price: 10.99,
      discount_percent: 10.99,
      line_total: 10.99,
      line_description: `Test Line Description ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Product data
   */
  createProduct(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      product_code: `Test Product Code ${uid}`,
      name: `Test Name ${uid}`,
      description: 'Test text content',
      family: `Test Family ${uid}`,
      list_price: 10.99,
      unit_cost: 10.99,
      billing_frequency: `Test Billing Frequency ${uid}`,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Quote data
   */
  createQuote(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      quote_number: `Test Quote Number ${uid}`,
      opportunity_id: `Test Opportunity Id ${uid}`,
      account_id: `Test Account Id ${uid}`,
      name: `Test Name ${uid}`,
      status: `Test Status ${uid}`,
      version_number: 1,
      valid_until: '2024-01-15',
      subtotal: 10.99,
      discount_percent: 10.99,
      discount_amount: 10.99,
      tax_amount: 10.99,
      grand_total: 10.99,
      approved_by_id: `Test Approved By Id ${uid}`,
      approved_at: new Date().toISOString(),
      approval_notes: 'Test text content',
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test QuoteLineItem data
   */
  createQuoteLineItem(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      quote_id: `Test Quote Id ${uid}`,
      product_id: `Test Product Id ${uid}`,
      quantity: 10.99,
      unit_price: 10.99,
      discount_percent: 10.99,
      line_total: 10.99,
      sort_order: 1,
      ...overrides,
    };
  },

  /**
   * Create test Contract data
   */
  createContract(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      contract_number: `Test Contract Number ${uid}`,
      account_id: `Test Account Id ${uid}`,
      quote_id: `Test Quote Id ${uid}`,
      status: `Test Status ${uid}`,
      start_date: '2024-01-15',
      end_date: '2024-01-15',
      term_months: 1,
      annual_value: 10.99,
      auto_renew: true,
      renewal_notice_days: 1,
      signed_by_id: `Test Signed By Id ${uid}`,
      signed_at: new Date().toISOString(),
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test SupportCase data
   */
  createSupportCase(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      case_number: `Test Case Number ${uid}`,
      account_id: `Test Account Id ${uid}`,
      contact_id: `Test Contact Id ${uid}`,
      sla_policy_id: `Test Sla Policy Id ${uid}`,
      subject: `Test Subject ${uid}`,
      description: 'Test text content',
      case_type: `Test Case Type ${uid}`,
      priority: `Test Priority ${uid}`,
      origin: `Test Origin ${uid}`,
      status: `Test Status ${uid}`,
      first_response_due_at: new Date().toISOString(),
      first_response_at: new Date().toISOString(),
      resolution_due_at: new Date().toISOString(),
      resolved_at: new Date().toISOString(),
      is_sla_breached: true,
      resolution_notes: 'Test text content',
      satisfaction_score: 1,
      escalated_by_id: `Test Escalated By Id ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test SlaPolicy data
   */
  createSlaPolicy(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      tier: `Test Tier ${uid}`,
      first_response_minutes: 1,
      resolution_hours: 1,
      business_hours_only: true,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Activity data
   */
  createActivity(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      activity_type: `Test Activity Type ${uid}`,
      subject: `Test Subject ${uid}`,
      description: 'Test text content',
      status: `Test Status ${uid}`,
      priority: `Test Priority ${uid}`,
      due_at: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      duration_minutes: 1,
      account_id: `Test Account Id ${uid}`,
      contact_id: `Test Contact Id ${uid}`,
      lead_id: `Test Lead Id ${uid}`,
      opportunity_id: `Test Opportunity Id ${uid}`,
      support_case_id: `Test Support Case Id ${uid}`,
      contract_id: `Test Contract Id ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

};

/**
 * Clean up test data from database
 */
export async function cleanupTestData(): Promise<void> {
  const db = await initTestDatabase();

  // Delete in reverse order of dependencies
  try {
    await db.deleteFrom('bus_user').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_team').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_territory').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_account').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_contact').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_lead').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_campaign').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_campaign_member').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_opportunity').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_opportunity_line_item').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_product').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_quote').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_quote_line_item').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_contract').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_support_case').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_sla_policy').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_activity').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
}

/**
 * Reset test database state
 */
export async function resetDatabase(): Promise<void> {
  await cleanupTestData();
}
