/**
 * Test Setup for nextjs-nestjs-test-app Backend
 * Generated by ERDwithAI
 *
 * Provides test utilities, fixtures, and database setup
 */

import { INestApplication } from "@nestjs/common";
import { FastifyAdapter, type NestFastifyApplication } from "@nestjs/platform-fastify";
import { Test, type TestingModule } from "@nestjs/testing";
import Knex from "knex";
import knexConfig from "../knexfile";

// Test database instance
let testDb: Knex.Knex;

// Test application instance
let testApp: NestFastifyApplication;

/**
 * Initialize test database connection
 */
export async function initTestDatabase(): Promise<Knex.Knex> {
  if (!testDb) {
    testDb = Knex({
      client: "better-sqlite3",
      connection: {
        filename: ":memory:",
      },
      useNullAsDefault: true,
      migrations: {
        directory: "./migrations",
      },
      seeds: {
        directory: "./seeds",
      },
    });

    // Run migrations
    await testDb.migrate.latest();
    // Run seeds (only if seed files exist)
    try {
      await testDb.seed.run();
    } catch (_e) {
      // Seeds may not exist, continue
    }
  }
  return testDb;
}

/**
 * Close test database connection
 */
export async function closeTestDatabase(): Promise<void> {
  if (testDb) {
    await testDb.destroy();
    testDb = undefined as any;
  }
}

/**
 * Create test application
 */
export async function createTestApp(module: any): Promise<NestFastifyApplication> {
  const moduleFixture: TestingModule = await Test.createTestingModule({
    imports: [module],
  }).compile();

  const app = moduleFixture.createNestApplication<NestFastifyApplication>(new FastifyAdapter());

  await app.init();
  await app.getHttpAdapter().getInstance().ready();

  return app;
}

/**
 * Close test application
 */
export async function closeTestApp(app: NestFastifyApplication): Promise<void> {
  if (app) {
    await app.close();
  }
}

/**
 * Generate test UUID
 */
export function generateTestId(): string {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Test data factories
 */
export const TestDataFactory = {
  /**
   * Create test CUSTOMER data
   */
  createCUSTOMER(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: "Test Name",
      email: "Test Email",
      phone: "Test Phone",
      city: "Test City",
      status: "Test Status",
      created_at: "2024-01-15",
      ...overrides,
    };
  },

  /**
   * Create test ORDER data
   */
  createORDER(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      customer_id: "Test Customer Id",
      order_date: "2024-01-15",
      total_amount: 10.99,
      status: "Test Status",
      created_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test ORDER_ITEM data
   */
  createORDERITEM(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      order_id: "Test Order Id",
      product_id: "Test Product Id",
      quantity: 1,
      unit_price: 10.99,
      line_total: 10.99,
      ...overrides,
    };
  },

  /**
   * Create test PRODUCT data
   */
  createPRODUCT(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: "Test Name",
      description: "Test Description",
      price: 10.99,
      stock_quantity: 1,
      category: "Test Category",
      is_active: true,
      ...overrides,
    };
  },
};

/**
 * Clean up test data from database
 */
export async function cleanupTestData(): Promise<void> {
  const db = await initTestDatabase();

  // Delete in reverse order of dependencies
  await db("bus_customer").del();
  await db("bus_order").del();
  await db("bus_order_item").del();
  await db("bus_product").del();
}

/**
 * Reset test database state
 */
export async function resetDatabase(): Promise<void> {
  await cleanupTestData();
  const db = await initTestDatabase();
  await db.seed.run();
}
