/**
 * All OPA5 Journeys for openui5-odatav4-test-app
 * Generated by ERDwithAI
 *
 * Aggregates all test journeys including CRUD operations
 */

sap.ui.define(
  [
    "sap/ui/test/Opa5",
    "./NavigationJourney",
    "./CUSTOMERCRUDJourney",
    "./ORDERCRUDJourney",
    "./ORDERITEMCRUDJourney",
    "./PRODUCTCRUDJourney",
  ],
  (
    Opa5,
    NavigationJourney,
    CUSTOMERCRUDJourney,
    ORDERCRUDJourney,
    ORDERITEMCRUDJourney,
    PRODUCTCRUDJourney
  ) => ({
    run: () => {
      // Run navigation tests
      QUnit.module("Navigation Journey");
      NavigationJourney.run();

      // Run CUSTOMER CRUD tests
      QUnit.module("CUSTOMER CRUD Journey");
      CUSTOMERCRUDJourney.run();

      // Run ORDER CRUD tests
      QUnit.module("ORDER CRUD Journey");
      ORDERCRUDJourney.run();

      // Run ORDER_ITEM CRUD tests
      QUnit.module("ORDERITEM CRUD Journey");
      ORDERITEMCRUDJourney.run();

      // Run PRODUCT CRUD tests
      QUnit.module("PRODUCT CRUD Journey");
      PRODUCTCRUDJourney.run();
    },
  })
);
