/**
 * OPA5 Integration Tests for openui5-odatav4-test-app
 * Generated by ERDwithAI
 *
 * Comprehensive UI integration tests using SAP OPA5 framework
 */

sap.ui.define(
  [
    "sap/ui/test/Opa5",
    "sap/ui/test/opaQunit",
    "./pages/App",
    "./pages/List",
    "./pages/Detail",
    "./AllJourneys",
  ],
  (Opa5, opaQunit, App, List, Detail, AllJourneys) => {
    // Configure OPA5
    Opa5.extendConfig({
      viewNamespace: "openui5-odatav4-test-app.view",
      autoWait: true,
      timeout: 15,
      pollingInterval: 100,
      asyncPolling: true,
    });

    // Run all journeys
    AllJourneys.run();
  }
);
