/**
 * Test Setup for CRM App Frontend
 * Generated by ERDwithAI
 *
 * Provides test utilities and mocks for React/TanStack Start testing
 */

import React from 'react';
import { vi } from 'vitest';
import { render, RenderOptions } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '@testing-library/jest-dom';

// Mock auth context - Sidebar and other components use useAuth
vi.mock('../src/contexts/auth-context', () => ({
  useAuth: () => ({
    user: { id: 'test-user', email: 'test@example.com', name: 'Test User', role: 'admin' },
    isLoading: false,
    isAuthenticated: true,
    isAdmin: () => true,
    hasRole: (_role: string) => true,
    hasPermission: (_perm: string) => true,
    signIn: vi.fn(),
    signOut: vi.fn(),
  }),
  AuthProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock translations - DynamicTable and other components use useTranslations
vi.mock('../src/lib/translations', () => ({
  useTranslations: () => ({
    t: (key: string) => key,
    locale: 'en',
  }),
  TranslationProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock @tanstack/react-router
vi.mock('@tanstack/react-router', async () => {
  const actual = await vi.importActual('@tanstack/react-router');
  return {
    ...actual,
    useNavigate: () => vi.fn(),
    useLocation: () => ({ pathname: '/', search: '', hash: '', state: null, key: '' }),
    useSearch: () => ({}),
    Link: ({ children, to, ...props }: { children: React.ReactNode; to: string; [key: string]: unknown }) =>
      React.createElement('a', { href: to, ...props }, children),
  };
});

// Create a test query client
export function createTestQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: 0,
        staleTime: 0,
      },
      mutations: {
        retry: false,
      },
    },
  });
}

// Custom render function with providers
interface CustomRenderOptions extends Omit<RenderOptions, 'wrapper'> {
  queryClient?: QueryClient;
}

export function renderWithProviders(
  ui: React.ReactElement,
  options: CustomRenderOptions = {}
) {
  const { queryClient = createTestQueryClient(), ...renderOptions } = options;

  function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <QueryClientProvider client={queryClient}>
        {children}
      </QueryClientProvider>
    );
  }

  return {
    ...render(ui, { wrapper: Wrapper, ...renderOptions }),
    queryClient,
  };
}

// Re-export everything from testing-library
export * from '@testing-library/react';
export { renderWithProviders as render };

/**
 * Mock API responses
 */
export const mockApiResponses = {
  aCCOUNT: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        email: 'Test Email 1',
        phone: 'Test Phone 1',
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        email: 'Test Email 2',
        phone: 'Test Phone 2',
        created_at: '2024-01-16T10:00:00Z',
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      email: 'Test Email',
      phone: 'Test Phone',
      created_at: '2024-01-15T10:00:00Z',
    },
  },
  cONTACT: {
    list: [
      {
        id: 'test-id-1',
        first_name: 'Test First Name 1',
        last_name: 'Test Last Name 1',
        email: 'Test Email 1',
        phone: 'Test Phone 1',
        account_id: 1,
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'test-id-2',
        first_name: 'Test First Name 2',
        last_name: 'Test Last Name 2',
        email: 'Test Email 2',
        phone: 'Test Phone 2',
        account_id: 2,
        created_at: '2024-01-16T10:00:00Z',
      },
    ],
    single: {
      id: 'test-id-1',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      email: 'Test Email',
      phone: 'Test Phone',
      account_id: 1,
      created_at: '2024-01-15T10:00:00Z',
    },
  },
  oPPORTUNITY: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        amount: 10.99,
        stage: 'Test Stage 1',
        account_id: 1,
        close_date: '2024-01-15T10:00:00Z',
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        amount: 20.99,
        stage: 'Test Stage 2',
        account_id: 2,
        close_date: '2024-01-16T10:00:00Z',
        created_at: '2024-01-16T10:00:00Z',
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      amount: 10.99,
      stage: 'Test Stage',
      account_id: 1,
      close_date: '2024-01-15T10:00:00Z',
      created_at: '2024-01-15T10:00:00Z',
    },
  },
  aCTIVITY: {
    list: [
      {
        id: 'test-id-1',
        type: 'Test Type 1',
        description: 'Test Description 1',
        contact_id: 1,
        opportunity_id: 1,
        activity_date: '2024-01-15T10:00:00Z',
        created_at: '2024-01-15T10:00:00Z',
      },
      {
        id: 'test-id-2',
        type: 'Test Type 2',
        description: 'Test Description 2',
        contact_id: 2,
        opportunity_id: 2,
        activity_date: '2024-01-16T10:00:00Z',
        created_at: '2024-01-16T10:00:00Z',
      },
    ],
    single: {
      id: 'test-id-1',
      type: 'Test Type',
      description: 'Test Description',
      contact_id: 1,
      opportunity_id: 1,
      activity_date: '2024-01-15T10:00:00Z',
      created_at: '2024-01-15T10:00:00Z',
    },
  },
};

/**
 * Create mock fetch function
 */
export function createMockFetch(responses: Record<string, unknown>) {
  return vi.fn((input: RequestInfo | URL, options?: RequestInit) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    const path = url.replace(/^https?:\/\/[^/]+/, '');

    // Find matching response
    for (const [pattern, response] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        return Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve(response),
          text: () => Promise.resolve(JSON.stringify(response)),
          headers: new Headers({ 'content-type': 'application/json' }),
        } as Response);
      }
    }

    // Default 404 response
    return Promise.resolve({
      ok: false,
      status: 404,
      json: () => Promise.resolve({ message: 'Not found' }),
      text: () => Promise.resolve('{"message": "Not found"}'),
      headers: new Headers({ 'content-type': 'application/json' }),
    } as Response);
  }) as unknown as typeof fetch;
}

/**
 * Wait for async operations
 */
export async function waitFor(callback: () => boolean | void, timeout = 5000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    try {
      const result = callback();
      if (result !== false) return;
    } catch {
      // Continue waiting
    }
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  throw new Error('Timeout waiting for condition');
}
