/**
 * OPA5 App Page Object
 * Generated by ERDwithAI
 */

sap.ui.define(
  [
    "sap/ui/test/Opa5",
    "sap/ui/test/actions/Press",
    "sap/ui/test/matchers/PropertyStrictEquals",
    "sap/ui/test/matchers/AggregationLengthEquals",
  ],
  (Opa5, Press, PropertyStrictEquals, AggregationLengthEquals) => {
    var sViewName = "App";

    Opa5.createPageObjects({
      onTheAppPage: {
        viewName: sViewName,

        actions: {
          /**
           * Navigate to a specific entity
           */
          iNavigateToEntity: function (sEntity) {
            return this.waitFor({
              controlType: "sap.m.StandardListItem",
              matchers: new PropertyStrictEquals({
                name: "title",
                value: sEntity,
              }),
              actions: new Press(),
              errorMessage: "Could not find entity: " + sEntity,
            });
          },

          /**
           * Press the Create button
           */
          iPressCreate: function () {
            return this.waitFor({
              controlType: "sap.m.Button",
              matchers: new PropertyStrictEquals({
                name: "icon",
                value: "sap-icon://add",
              }),
              actions: new Press(),
              errorMessage: "Could not find Create button",
            });
          },

          /**
           * Press the Back button
           */
          iPressBack: function () {
            return this.waitFor({
              controlType: "sap.m.Button",
              matchers: new PropertyStrictEquals({
                name: "icon",
                value: "sap-icon://nav-back",
              }),
              actions: new Press(),
              errorMessage: "Could not find Back button",
            });
          },
        },

        assertions: {
          /**
           * Verify the app is loaded
           */
          iShouldSeeTheApp: function () {
            return this.waitFor({
              controlType: "sap.f.FlexibleColumnLayout",
              success: () => {
                Opa5.assert.ok(true, "The app is displayed with Flexible Column Layout");
              },
              errorMessage: "Could not find Flexible Column Layout",
            });
          },

          /**
           * Verify the title is displayed
           */
          iShouldSeeTitle: function (sTitle) {
            return this.waitFor({
              controlType: "sap.m.Title",
              matchers: new PropertyStrictEquals({
                name: "text",
                value: sTitle,
              }),
              success: () => {
                Opa5.assert.ok(true, "Title '" + sTitle + "' is displayed");
              },
              errorMessage: "Could not find title: " + sTitle,
            });
          },

          /**
           * Verify busy indicator is shown
           */
          iShouldSeeBusyIndicator: function () {
            return this.waitFor({
              controlType: "sap.m.BusyIndicator",
              success: () => {
                Opa5.assert.ok(true, "Busy indicator is displayed");
              },
              errorMessage: "Could not find busy indicator",
            });
          },
        },
      },
    });
  }
);
