/**
 * Comprehensive E2E Tests for CRM Regenerated 2
 * Generated by ERDwithAI — TanStack Start + NestJS Stack
 *
 * Entities: Company, Contact, Deal, DealStage, Pipeline, Activity, Note, Task, EmailMessage, EmailTemplate, Product, Quote, QuoteItem, User, Team
 *
 * Frontend: process.env.FRONTEND_URL (default: http://localhost:3000)
 * Backend:  process.env.BACKEND_URL  (default: http://localhost:3001)
 */

import { test, expect } from '@playwright/test';

// ============================================================================
// Configuration
// ============================================================================

const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:3000';
const BACKEND_URL  = process.env.BACKEND_URL  || 'http://localhost:3001';
const API_BASE     = `${BACKEND_URL}/api/bus`;

// Entity paths
const COMPANY_PATH = '/bus_company';
const CONTACT_PATH = '/bus_contact';
const DEAL_PATH = '/bus_deal';
const DEAL_STAGE_PATH = '/bus_deal_stage';
const PIPELINE_PATH = '/bus_pipeline';
const ACTIVITY_PATH = '/bus_activity';
const NOTE_PATH = '/bus_note';
const TASK_PATH = '/bus_task';
const EMAIL_MESSAGE_PATH = '/bus_email_message';
const EMAIL_TEMPLATE_PATH = '/bus_email_template';
const PRODUCT_PATH = '/bus_product';
const QUOTE_PATH = '/bus_quote';
const QUOTE_ITEM_PATH = '/bus_quote_item';
const USER_PATH = '/bus_user';
const TEAM_PATH = '/bus_team';

// ============================================================================
// Helpers
// ============================================================================

async function waitForPageReady(page: any) {
  await page.waitForLoadState('networkidle');
  await page.waitForTimeout(500);
}

// ============================================================================
// API Health Checks
// ============================================================================

test.describe('CRM Regenerated 2 — API Health', () => {
  test('GET /api/bus/companies should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/companies`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/contacts should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/contacts`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/deals should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/deals`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/deal_stages should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/deal_stages`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/pipelines should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/pipelines`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/activities should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/activities`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/notes should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/notes`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/tasks should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/tasks`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/email_messages should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/email_messages`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/email_templates should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/email_templates`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/products should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/products`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/quotes should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/quotes`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/quote_items should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/quote_items`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/users should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/users`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

  test('GET /api/bus/teams should respond 200', async ({ request }) => {
    const res = await request.get(`${API_BASE}/teams`);
    expect(res.status()).toBe(200);
    const data = await res.json();
    expect(data).toHaveProperty('data');
    expect(Array.isArray(data.data)).toBe(true);
  });

});

// ============================================================================
// Entity CRUD Tests (via API)
// ============================================================================

test.describe('Company — CRUD', () => {
  test('should create a Company via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
      industry: 'test_value',
      website: 'test_value',
      phone: '+1234567890',
      email: 'test@example.com',
      employee_count: 123,
      annual_revenue: 123.45,
      status: 'test_value',
    };

    const res = await request.post(`${API_BASE}/companies`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/companies/${created.id}`);
    }
  });

  test('should read a Company via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
      industry: `test_value_0`,
      website: `test_value_0`,
      phone: `test_value_0`,
      email: `test0@example.com`,
      employee_count: 100,
      annual_revenue: 100.50,
      status: `test_value_0`,
    };

    const createRes = await request.post(`${API_BASE}/companies`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/companies/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/companies/${created.id}`);
    }
  });

  test('should update a Company via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/companies`, {
      data: {
        name: `Test Name 1`,
        industry: `test_value_1`,
        website: `test_value_1`,
        phone: `test_value_1`,
        email: `test1@example.com`,
        employee_count: 101,
        annual_revenue: 101.50,
        status: `test_value_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/companies/${created.id}`, {
        data: {
          name: `Test Name 2`,
          industry: `test_value_2`,
          website: `test_value_2`,
          phone: `test_value_2`,
          email: `test2@example.com`,
          employee_count: 102,
          annual_revenue: 102.50,
          status: `test_value_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/companies/${created.id}`);
    }
  });

  test('should delete a Company via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/companies`, {
      data: {
        name: `Test Name 3`,
        industry: `test_value_3`,
        website: `test_value_3`,
        phone: `test_value_3`,
        email: `test3@example.com`,
        employee_count: 103,
        annual_revenue: 103.50,
        status: `test_value_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/companies/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/companies/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Contact — CRUD', () => {
  test('should create a Contact via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      first_name: 'Test Name',
      last_name: 'Test Name',
      email: 'test@example.com',
      phone: '+1234567890',
      mobile: 'test_value',
      job_title: 'test_value',
      department: 'test_value',
      status: 'test_value',
      lead_source: 'test_value',
    };

    const res = await request.post(`${API_BASE}/contacts`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/contacts/${created.id}`);
    }
  });

  test('should read a Contact via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      first_name: `Test Name 0`,
      last_name: `Test Name 0`,
      email: `test0@example.com`,
      phone: `test_value_0`,
      mobile: `test_value_0`,
      job_title: `test_value_0`,
      department: `test_value_0`,
      status: `test_value_0`,
      lead_source: `test_value_0`,
    };

    const createRes = await request.post(`${API_BASE}/contacts`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/contacts/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/contacts/${created.id}`);
    }
  });

  test('should update a Contact via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/contacts`, {
      data: {
        first_name: `Test Name 1`,
        last_name: `Test Name 1`,
        email: `test1@example.com`,
        phone: `test_value_1`,
        mobile: `test_value_1`,
        job_title: `test_value_1`,
        department: `test_value_1`,
        status: `test_value_1`,
        lead_source: `test_value_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/contacts/${created.id}`, {
        data: {
          first_name: `Test Name 2`,
          last_name: `Test Name 2`,
          email: `test2@example.com`,
          phone: `test_value_2`,
          mobile: `test_value_2`,
          job_title: `test_value_2`,
          department: `test_value_2`,
          status: `test_value_2`,
          lead_source: `test_value_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/contacts/${created.id}`);
    }
  });

  test('should delete a Contact via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/contacts`, {
      data: {
        first_name: `Test Name 3`,
        last_name: `Test Name 3`,
        email: `test3@example.com`,
        phone: `test_value_3`,
        mobile: `test_value_3`,
        job_title: `test_value_3`,
        department: `test_value_3`,
        status: `test_value_3`,
        lead_source: `test_value_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/contacts/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/contacts/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Deal — CRUD', () => {
  test('should create a Deal via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
      amount: 123.45,
      currency: 'test_value',
      stage: 'test_value',
      probability: 123,
      expected_close_date: new Date().toISOString(),
      actual_close_date: new Date().toISOString(),
      status: 'test_value',
      description: 'test_value',
    };

    const res = await request.post(`${API_BASE}/deals`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/deals/${created.id}`);
    }
  });

  test('should read a Deal via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
      amount: 100.50,
      currency: `test_value_0`,
      stage: `test_value_0`,
      probability: 100,
      expected_close_date: `test_0`,
      actual_close_date: `test_0`,
      status: `test_value_0`,
      description: `test_value_0`,
    };

    const createRes = await request.post(`${API_BASE}/deals`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/deals/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/deals/${created.id}`);
    }
  });

  test('should update a Deal via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/deals`, {
      data: {
        name: `Test Name 1`,
        amount: 101.50,
        currency: `test_value_1`,
        stage: `test_value_1`,
        probability: 101,
        expected_close_date: `test_1`,
        actual_close_date: `test_1`,
        status: `test_value_1`,
        description: `test_value_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/deals/${created.id}`, {
        data: {
          name: `Test Name 2`,
          amount: 102.50,
          currency: `test_value_2`,
          stage: `test_value_2`,
          probability: 102,
          expected_close_date: `test_2`,
          actual_close_date: `test_2`,
          status: `test_value_2`,
          description: `test_value_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/deals/${created.id}`);
    }
  });

  test('should delete a Deal via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/deals`, {
      data: {
        name: `Test Name 3`,
        amount: 103.50,
        currency: `test_value_3`,
        stage: `test_value_3`,
        probability: 103,
        expected_close_date: `test_3`,
        actual_close_date: `test_3`,
        status: `test_value_3`,
        description: `test_value_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/deals/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/deals/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Deal Stage — CRUD', () => {
  test('should create a Deal Stage via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
      sort_order: 123,
      default_probability: 123,
      is_won: true,
      is_lost: true,
    };

    const res = await request.post(`${API_BASE}/deal_stages`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/deal_stages/${created.id}`);
    }
  });

  test('should read a Deal Stage via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
      sort_order: 100,
      default_probability: 100,
      is_won: `test_0`,
      is_lost: `test_0`,
    };

    const createRes = await request.post(`${API_BASE}/deal_stages`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/deal_stages/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/deal_stages/${created.id}`);
    }
  });

  test('should update a Deal Stage via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/deal_stages`, {
      data: {
        name: `Test Name 1`,
        sort_order: 101,
        default_probability: 101,
        is_won: `test_1`,
        is_lost: `test_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/deal_stages/${created.id}`, {
        data: {
          name: `Test Name 2`,
          sort_order: 102,
          default_probability: 102,
          is_won: `test_2`,
          is_lost: `test_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/deal_stages/${created.id}`);
    }
  });

  test('should delete a Deal Stage via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/deal_stages`, {
      data: {
        name: `Test Name 3`,
        sort_order: 103,
        default_probability: 103,
        is_won: `test_3`,
        is_lost: `test_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/deal_stages/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/deal_stages/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Pipeline — CRUD', () => {
  test('should create a Pipeline via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
      is_default: true,
      is_active: true,
    };

    const res = await request.post(`${API_BASE}/pipelines`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/pipelines/${created.id}`);
    }
  });

  test('should read a Pipeline via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
      is_default: `test_0`,
      is_active: `test_0`,
    };

    const createRes = await request.post(`${API_BASE}/pipelines`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/pipelines/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/pipelines/${created.id}`);
    }
  });

  test('should update a Pipeline via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/pipelines`, {
      data: {
        name: `Test Name 1`,
        is_default: `test_1`,
        is_active: `test_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/pipelines/${created.id}`, {
        data: {
          name: `Test Name 2`,
          is_default: `test_2`,
          is_active: `test_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/pipelines/${created.id}`);
    }
  });

  test('should delete a Pipeline via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/pipelines`, {
      data: {
        name: `Test Name 3`,
        is_default: `test_3`,
        is_active: `test_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/pipelines/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/pipelines/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Activity — CRUD', () => {
  test('should create a Activity via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      activity_type: 'test_value',
      subject: 'test_value',
      description: 'test_value',
      scheduled_at: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      duration_minutes: 123,
      status: 'test_value',
    };

    const res = await request.post(`${API_BASE}/activities`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/activities/${created.id}`);
    }
  });

  test('should read a Activity via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      activity_type: `test_value_0`,
      subject: `test_value_0`,
      description: `test_value_0`,
      scheduled_at: `test_0`,
      completed_at: `test_0`,
      duration_minutes: 100,
      status: `test_value_0`,
    };

    const createRes = await request.post(`${API_BASE}/activities`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/activities/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/activities/${created.id}`);
    }
  });

  test('should update a Activity via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/activities`, {
      data: {
        activity_type: `test_value_1`,
        subject: `test_value_1`,
        description: `test_value_1`,
        scheduled_at: `test_1`,
        completed_at: `test_1`,
        duration_minutes: 101,
        status: `test_value_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/activities/${created.id}`, {
        data: {
          activity_type: `test_value_2`,
          subject: `test_value_2`,
          description: `test_value_2`,
          scheduled_at: `test_2`,
          completed_at: `test_2`,
          duration_minutes: 102,
          status: `test_value_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/activities/${created.id}`);
    }
  });

  test('should delete a Activity via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/activities`, {
      data: {
        activity_type: `test_value_3`,
        subject: `test_value_3`,
        description: `test_value_3`,
        scheduled_at: `test_3`,
        completed_at: `test_3`,
        duration_minutes: 103,
        status: `test_value_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/activities/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/activities/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Note — CRUD', () => {
  test('should create a Note via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      content: 'test_value',
      is_pinned: true,
    };

    const res = await request.post(`${API_BASE}/notes`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/notes/${created.id}`);
    }
  });

  test('should read a Note via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      content: `test_value_0`,
      is_pinned: `test_0`,
    };

    const createRes = await request.post(`${API_BASE}/notes`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/notes/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/notes/${created.id}`);
    }
  });

  test('should update a Note via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/notes`, {
      data: {
        content: `test_value_1`,
        is_pinned: `test_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/notes/${created.id}`, {
        data: {
          content: `test_value_2`,
          is_pinned: `test_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/notes/${created.id}`);
    }
  });

  test('should delete a Note via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/notes`, {
      data: {
        content: `test_value_3`,
        is_pinned: `test_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/notes/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/notes/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Task — CRUD', () => {
  test('should create a Task via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      title: 'test_value',
      description: 'test_value',
      priority: 'test_value',
      status: 'test_value',
      due_date: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      assigned_to: 'test_value',
      created_by: 'test_value',
    };

    const res = await request.post(`${API_BASE}/tasks`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/tasks/${created.id}`);
    }
  });

  test('should read a Task via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      title: `test_value_0`,
      description: `test_value_0`,
      priority: `test_value_0`,
      status: `test_value_0`,
      due_date: `test_0`,
      completed_at: `test_0`,
      assigned_to: `test_value_0`,
      created_by: `test_value_0`,
    };

    const createRes = await request.post(`${API_BASE}/tasks`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/tasks/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/tasks/${created.id}`);
    }
  });

  test('should update a Task via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/tasks`, {
      data: {
        title: `test_value_1`,
        description: `test_value_1`,
        priority: `test_value_1`,
        status: `test_value_1`,
        due_date: `test_1`,
        completed_at: `test_1`,
        assigned_to: `test_value_1`,
        created_by: `test_value_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/tasks/${created.id}`, {
        data: {
          title: `test_value_2`,
          description: `test_value_2`,
          priority: `test_value_2`,
          status: `test_value_2`,
          due_date: `test_2`,
          completed_at: `test_2`,
          assigned_to: `test_value_2`,
          created_by: `test_value_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/tasks/${created.id}`);
    }
  });

  test('should delete a Task via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/tasks`, {
      data: {
        title: `test_value_3`,
        description: `test_value_3`,
        priority: `test_value_3`,
        status: `test_value_3`,
        due_date: `test_3`,
        completed_at: `test_3`,
        assigned_to: `test_value_3`,
        created_by: `test_value_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/tasks/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/tasks/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Email Message — CRUD', () => {
  test('should create a Email Message via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      subject: 'test_value',
      body_text: 'test_value',
      body_html: 'test_value',
      direction: 'test_value',
      sent_at: new Date().toISOString(),
      received_at: new Date().toISOString(),
      opened_at: new Date().toISOString(),
      open_count: 123,
    };

    const res = await request.post(`${API_BASE}/email_messages`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/email_messages/${created.id}`);
    }
  });

  test('should read a Email Message via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      subject: `test_value_0`,
      body_text: `test_value_0`,
      body_html: `test_value_0`,
      direction: `test_value_0`,
      sent_at: `test_0`,
      received_at: `test_0`,
      opened_at: `test_0`,
      open_count: 100,
    };

    const createRes = await request.post(`${API_BASE}/email_messages`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/email_messages/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/email_messages/${created.id}`);
    }
  });

  test('should update a Email Message via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/email_messages`, {
      data: {
        subject: `test_value_1`,
        body_text: `test_value_1`,
        body_html: `test_value_1`,
        direction: `test_value_1`,
        sent_at: `test_1`,
        received_at: `test_1`,
        opened_at: `test_1`,
        open_count: 101,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/email_messages/${created.id}`, {
        data: {
          subject: `test_value_2`,
          body_text: `test_value_2`,
          body_html: `test_value_2`,
          direction: `test_value_2`,
          sent_at: `test_2`,
          received_at: `test_2`,
          opened_at: `test_2`,
          open_count: 102,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/email_messages/${created.id}`);
    }
  });

  test('should delete a Email Message via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/email_messages`, {
      data: {
        subject: `test_value_3`,
        body_text: `test_value_3`,
        body_html: `test_value_3`,
        direction: `test_value_3`,
        sent_at: `test_3`,
        received_at: `test_3`,
        opened_at: `test_3`,
        open_count: 103,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/email_messages/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/email_messages/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Email Template — CRUD', () => {
  test('should create a Email Template via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
      subject: 'test_value',
      body_html: 'test_value',
      body_text: 'test_value',
      category: 'test_value',
      is_active: true,
    };

    const res = await request.post(`${API_BASE}/email_templates`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/email_templates/${created.id}`);
    }
  });

  test('should read a Email Template via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
      subject: `test_value_0`,
      body_html: `test_value_0`,
      body_text: `test_value_0`,
      category: `test_value_0`,
      is_active: `test_0`,
    };

    const createRes = await request.post(`${API_BASE}/email_templates`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/email_templates/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/email_templates/${created.id}`);
    }
  });

  test('should update a Email Template via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/email_templates`, {
      data: {
        name: `Test Name 1`,
        subject: `test_value_1`,
        body_html: `test_value_1`,
        body_text: `test_value_1`,
        category: `test_value_1`,
        is_active: `test_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/email_templates/${created.id}`, {
        data: {
          name: `Test Name 2`,
          subject: `test_value_2`,
          body_html: `test_value_2`,
          body_text: `test_value_2`,
          category: `test_value_2`,
          is_active: `test_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/email_templates/${created.id}`);
    }
  });

  test('should delete a Email Template via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/email_templates`, {
      data: {
        name: `Test Name 3`,
        subject: `test_value_3`,
        body_html: `test_value_3`,
        body_text: `test_value_3`,
        category: `test_value_3`,
        is_active: `test_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/email_templates/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/email_templates/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Product — CRUD', () => {
  test('should create a Product via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
      sku: 'test_value',
      description: 'test_value',
      unit_price: 123.45,
      currency: 'test_value',
      is_active: true,
    };

    const res = await request.post(`${API_BASE}/products`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/products/${created.id}`);
    }
  });

  test('should read a Product via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
      sku: `test_value_0`,
      description: `test_value_0`,
      unit_price: 100.50,
      currency: `test_value_0`,
      is_active: `test_0`,
    };

    const createRes = await request.post(`${API_BASE}/products`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/products/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/products/${created.id}`);
    }
  });

  test('should update a Product via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/products`, {
      data: {
        name: `Test Name 1`,
        sku: `test_value_1`,
        description: `test_value_1`,
        unit_price: 101.50,
        currency: `test_value_1`,
        is_active: `test_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/products/${created.id}`, {
        data: {
          name: `Test Name 2`,
          sku: `test_value_2`,
          description: `test_value_2`,
          unit_price: 102.50,
          currency: `test_value_2`,
          is_active: `test_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/products/${created.id}`);
    }
  });

  test('should delete a Product via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/products`, {
      data: {
        name: `Test Name 3`,
        sku: `test_value_3`,
        description: `test_value_3`,
        unit_price: 103.50,
        currency: `test_value_3`,
        is_active: `test_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/products/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/products/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Quote — CRUD', () => {
  test('should create a Quote via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      quote_number: 'test_value',
      status: 'test_value',
      valid_until: new Date().toISOString(),
      subtotal: 123.45,
      discount_amount: 123.45,
      tax_amount: 123.45,
      total_amount: 123.45,
      terms: 'test_value',
      notes: 'test_value',
    };

    const res = await request.post(`${API_BASE}/quotes`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/quotes/${created.id}`);
    }
  });

  test('should read a Quote via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      quote_number: `test_value_0`,
      status: `test_value_0`,
      valid_until: `test_0`,
      subtotal: 100.50,
      discount_amount: 100.50,
      tax_amount: 100.50,
      total_amount: 100.50,
      terms: `test_value_0`,
      notes: `test_value_0`,
    };

    const createRes = await request.post(`${API_BASE}/quotes`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/quotes/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/quotes/${created.id}`);
    }
  });

  test('should update a Quote via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/quotes`, {
      data: {
        quote_number: `test_value_1`,
        status: `test_value_1`,
        valid_until: `test_1`,
        subtotal: 101.50,
        discount_amount: 101.50,
        tax_amount: 101.50,
        total_amount: 101.50,
        terms: `test_value_1`,
        notes: `test_value_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/quotes/${created.id}`, {
        data: {
          quote_number: `test_value_2`,
          status: `test_value_2`,
          valid_until: `test_2`,
          subtotal: 102.50,
          discount_amount: 102.50,
          tax_amount: 102.50,
          total_amount: 102.50,
          terms: `test_value_2`,
          notes: `test_value_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/quotes/${created.id}`);
    }
  });

  test('should delete a Quote via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/quotes`, {
      data: {
        quote_number: `test_value_3`,
        status: `test_value_3`,
        valid_until: `test_3`,
        subtotal: 103.50,
        discount_amount: 103.50,
        tax_amount: 103.50,
        total_amount: 103.50,
        terms: `test_value_3`,
        notes: `test_value_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/quotes/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/quotes/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Quote Item — CRUD', () => {
  test('should create a Quote Item via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      description: 'test_value',
      quantity: 123,
      unit_price: 123.45,
      discount_percent: 123.45,
      total_price: 123.45,
    };

    const res = await request.post(`${API_BASE}/quote_items`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/quote_items/${created.id}`);
    }
  });

  test('should read a Quote Item via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      description: `test_value_0`,
      quantity: 100,
      unit_price: 100.50,
      discount_percent: 100.50,
      total_price: 100.50,
    };

    const createRes = await request.post(`${API_BASE}/quote_items`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/quote_items/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/quote_items/${created.id}`);
    }
  });

  test('should update a Quote Item via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/quote_items`, {
      data: {
        description: `test_value_1`,
        quantity: 101,
        unit_price: 101.50,
        discount_percent: 101.50,
        total_price: 101.50,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/quote_items/${created.id}`, {
        data: {
          description: `test_value_2`,
          quantity: 102,
          unit_price: 102.50,
          discount_percent: 102.50,
          total_price: 102.50,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/quote_items/${created.id}`);
    }
  });

  test('should delete a Quote Item via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/quote_items`, {
      data: {
        description: `test_value_3`,
        quantity: 103,
        unit_price: 103.50,
        discount_percent: 103.50,
        total_price: 103.50,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/quote_items/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/quote_items/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('User — CRUD', () => {
  test('should create a User via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      email: 'test@example.com',
      first_name: 'Test Name',
      last_name: 'Test Name',
      role: 'test_value',
      is_active: true,
      last_login: new Date().toISOString(),
    };

    const res = await request.post(`${API_BASE}/users`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/users/${created.id}`);
    }
  });

  test('should read a User via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      email: `test0@example.com`,
      first_name: `Test Name 0`,
      last_name: `Test Name 0`,
      role: `test_value_0`,
      is_active: `test_0`,
      last_login: `test_0`,
    };

    const createRes = await request.post(`${API_BASE}/users`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/users/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/users/${created.id}`);
    }
  });

  test('should update a User via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/users`, {
      data: {
        email: `test1@example.com`,
        first_name: `Test Name 1`,
        last_name: `Test Name 1`,
        role: `test_value_1`,
        is_active: `test_1`,
        last_login: `test_1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/users/${created.id}`, {
        data: {
          email: `test2@example.com`,
          first_name: `Test Name 2`,
          last_name: `Test Name 2`,
          role: `test_value_2`,
          is_active: `test_2`,
          last_login: `test_2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/users/${created.id}`);
    }
  });

  test('should delete a User via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/users`, {
      data: {
        email: `test3@example.com`,
        first_name: `Test Name 3`,
        last_name: `Test Name 3`,
        role: `test_value_3`,
        is_active: `test_3`,
        last_login: `test_3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/users/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/users/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});

test.describe('Team — CRUD', () => {
  test('should create a Team via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: 'Test Name',
    };

    const res = await request.post(`${API_BASE}/teams`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    expect([200, 201]).toContain(res.status());
    const created = await res.json();
    expect(created).toHaveProperty('id');

    if (created.id) {
      await request.delete(`${API_BASE}/teams/${created.id}`);
    }
  });

  test('should read a Team via API', async ({ request }) => {
    const payload: Record<string, unknown> = {
      name: `Test Name 0`,
    };

    const createRes = await request.post(`${API_BASE}/teams`, {
      data: payload,
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const getRes = await request.get(`${API_BASE}/teams/${created.id}`);
      expect(getRes.status()).toBe(200);
      await request.delete(`${API_BASE}/teams/${created.id}`);
    }
  });

  test('should update a Team via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/teams`, {
      data: {
        name: `Test Name 1`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const updateRes = await request.patch(`${API_BASE}/teams/${created.id}`, {
        data: {
          name: `Test Name 2`,
        },
        headers: { 'Content-Type': 'application/json' },
      });
      expect([200, 201]).toContain(updateRes.status());
      await request.delete(`${API_BASE}/teams/${created.id}`);
    }
  });

  test('should delete a Team via API', async ({ request }) => {
    const createRes = await request.post(`${API_BASE}/teams`, {
      data: {
        name: `Test Name 3`,
      },
      headers: { 'Content-Type': 'application/json' },
    });
    const created = await createRes.json();

    if (created.id) {
      const delRes = await request.delete(`${API_BASE}/teams/${created.id}`);
      expect([200, 204]).toContain(delRes.status());
      const getRes = await request.get(`${API_BASE}/teams/${created.id}`);
      expect([400, 404]).toContain(getRes.status());
    }
  });
});


// ============================================================================
// Frontend Page Tests
// ============================================================================

test.describe('Company — Frontend', () => {
  test('should display Company list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_company`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Company page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_company/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Company page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_company/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Contact — Frontend', () => {
  test('should display Contact list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_contact`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Contact page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_contact/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Contact page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_contact/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Deal — Frontend', () => {
  test('should display Deal list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Deal page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Deal page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Deal Stage — Frontend', () => {
  test('should display Deal Stage list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal_stage`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Deal Stage page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal_stage/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Deal Stage page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal_stage/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Pipeline — Frontend', () => {
  test('should display Pipeline list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_pipeline`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Pipeline page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_pipeline/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Pipeline page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_pipeline/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Activity — Frontend', () => {
  test('should display Activity list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_activity`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Activity page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_activity/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Activity page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_activity/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Note — Frontend', () => {
  test('should display Note list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_note`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Note page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_note/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Note page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_note/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Task — Frontend', () => {
  test('should display Task list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_task`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Task page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_task/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Task page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_task/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Email Message — Frontend', () => {
  test('should display Email Message list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_message`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Email Message page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_message/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Email Message page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_message/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Email Template — Frontend', () => {
  test('should display Email Template list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_template`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Email Template page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_template/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Email Template page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_template/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Product — Frontend', () => {
  test('should display Product list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_product`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Product page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_product/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Product page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_product/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Quote — Frontend', () => {
  test('should display Quote list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Quote page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Quote page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Quote Item — Frontend', () => {
  test('should display Quote Item list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote_item`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Quote Item page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote_item/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Quote Item page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote_item/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('User — Frontend', () => {
  test('should display User list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_user`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create User page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_user/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create User page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_user/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});

test.describe('Team — Frontend', () => {
  test('should display Team list page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_team`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('table').first()).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Create"), button:has-text("New"), button:has-text("Add")').first()
    ).toBeVisible();
  });

  test('should show form fields on create Team page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_team/new`);
    await waitForPageReady(page);
    const form = page.locator('form').first();
    await expect(form).toBeVisible({ timeout: 10000 });
    const inputs = page.locator('input, select, textarea');
    expect(await inputs.count()).toBeGreaterThan(0);
  });

  test('should have save and cancel buttons on create Team page', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_team/new`);
    await waitForPageReady(page);
    await expect(
      page.locator('button[type="submit"], button:has-text("Save"), button:has-text("Create")').first()
    ).toBeVisible({ timeout: 10000 });
    await expect(
      page.locator('button:has-text("Cancel"), button:has-text("Back"), a:has-text("Back")').first()
    ).toBeVisible({ timeout: 10000 });
  });
});


// ============================================================================
// Navigation Tests
// ============================================================================

test.describe('CRM Regenerated 2 — Navigation', () => {
  test('should load home/dashboard without error', async ({ page }) => {
    await page.goto(FRONTEND_URL);
    await waitForPageReady(page);
    await expect(page).not.toHaveURL(/error/);
    await expect(page.locator('body')).toBeVisible();
  });

  test('should navigate to Company list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_company`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Contact list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_contact`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Deal list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Deal Stage list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_deal_stage`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Pipeline list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_pipeline`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Activity list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_activity`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Note list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_note`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Task list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_task`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Email Message list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_message`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Email Template list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_email_template`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Product list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_product`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Quote list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Quote Item list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_quote_item`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to User list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_user`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should navigate to Team list', async ({ page }) => {
    await page.goto(`${FRONTEND_URL}/bus_team`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

});

// ============================================================================
// Responsive Design
// ============================================================================

test.describe('CRM Regenerated 2 — Responsive Design', () => {
  test('should be usable on tablet (768 × 1024)', async ({ page }) => {
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.goto(`${FRONTEND_URL}/bus_company`);
    await waitForPageReady(page);
    await expect(page.locator('h1, h2').first()).toBeVisible({ timeout: 10000 });
  });

  test('should be usable on mobile (375 × 812)', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(`${FRONTEND_URL}/bus_company`);
    await waitForPageReady(page);
    await expect(page.locator('body')).toBeVisible();
  });
});

// ============================================================================
// Error Handling
// ============================================================================

test.describe('CRM Regenerated 2 — API Error Handling', () => {
  test('should return 404 for non-existent record', async ({ request }) => {
    const res = await request.get(
      `${API_BASE}/companies/00000000-0000-0000-0000-000000000000`
    );
    expect([400, 404]).toContain(res.status());
  });

  test('should return error for non-existent entity endpoint', async ({ request }) => {
    const res = await request.get(`${API_BASE}/nonexistententity`);
    expect([400, 404, 500]).toContain(res.status());
  });

  test('should handle malformed request body gracefully', async ({ request }) => {
    const res = await request.post(`${API_BASE}/companies`, {
      data: 'not-valid-json-object',
      headers: { 'Content-Type': 'application/json' },
    });
    expect([400, 422]).toContain(res.status());
  });
});
