/**
 * Test Data Fixtures for CRM Regenerated 2
 * Generated by ERDwithAI
 */

// Test data for all entities
export const testData = {
  Company: {
    create: {
      name: 'Test Name',
      industry: 'test_value',
      website: 'test_value',
      phone: '+1234567890',
      email: 'test@example.com',
      employee_count: 123,
      annual_revenue: 123.45,
      status: 'test_value',
    },
    update: {
      name: `Test Name 1`,
      industry: `test_value_1`,
      website: `test_value_1`,
      phone: `test_value_1`,
      email: `test1@example.com`,
      employee_count: 101,
      annual_revenue: 101.50,
      status: `test_value_1`,
    },
  },
  Contact: {
    create: {
      first_name: 'Test Name',
      last_name: 'Test Name',
      email: 'test@example.com',
      phone: '+1234567890',
      mobile: 'test_value',
      job_title: 'test_value',
      department: 'test_value',
      status: 'test_value',
      lead_source: 'test_value',
    },
    update: {
      first_name: `Test Name 1`,
      last_name: `Test Name 1`,
      email: `test1@example.com`,
      phone: `test_value_1`,
      mobile: `test_value_1`,
      job_title: `test_value_1`,
      department: `test_value_1`,
      status: `test_value_1`,
      lead_source: `test_value_1`,
    },
  },
  Deal: {
    create: {
      name: 'Test Name',
      amount: 123.45,
      currency: 'test_value',
      stage: 'test_value',
      probability: 123,
      expected_close_date: new Date().toISOString(),
      actual_close_date: new Date().toISOString(),
      status: 'test_value',
      description: 'test_value',
    },
    update: {
      name: `Test Name 1`,
      amount: 101.50,
      currency: `test_value_1`,
      stage: `test_value_1`,
      probability: 101,
      expected_close_date: `test_1`,
      actual_close_date: `test_1`,
      status: `test_value_1`,
      description: `test_value_1`,
    },
  },
  DealStage: {
    create: {
      name: 'Test Name',
      sort_order: 123,
      default_probability: 123,
      is_won: true,
      is_lost: true,
    },
    update: {
      name: `Test Name 1`,
      sort_order: 101,
      default_probability: 101,
      is_won: `test_1`,
      is_lost: `test_1`,
    },
  },
  Pipeline: {
    create: {
      name: 'Test Name',
      is_default: true,
      is_active: true,
    },
    update: {
      name: `Test Name 1`,
      is_default: `test_1`,
      is_active: `test_1`,
    },
  },
  Activity: {
    create: {
      activity_type: 'test_value',
      subject: 'test_value',
      description: 'test_value',
      scheduled_at: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      duration_minutes: 123,
      status: 'test_value',
    },
    update: {
      activity_type: `test_value_1`,
      subject: `test_value_1`,
      description: `test_value_1`,
      scheduled_at: `test_1`,
      completed_at: `test_1`,
      duration_minutes: 101,
      status: `test_value_1`,
    },
  },
  Note: {
    create: {
      content: 'test_value',
      is_pinned: true,
    },
    update: {
      content: `test_value_1`,
      is_pinned: `test_1`,
    },
  },
  Task: {
    create: {
      title: 'test_value',
      description: 'test_value',
      priority: 'test_value',
      status: 'test_value',
      due_date: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      assigned_to: 'test_value',
      created_by: 'test_value',
    },
    update: {
      title: `test_value_1`,
      description: `test_value_1`,
      priority: `test_value_1`,
      status: `test_value_1`,
      due_date: `test_1`,
      completed_at: `test_1`,
      assigned_to: `test_value_1`,
      created_by: `test_value_1`,
    },
  },
  EmailMessage: {
    create: {
      subject: 'test_value',
      body_text: 'test_value',
      body_html: 'test_value',
      direction: 'test_value',
      sent_at: new Date().toISOString(),
      received_at: new Date().toISOString(),
      opened_at: new Date().toISOString(),
      open_count: 123,
    },
    update: {
      subject: `test_value_1`,
      body_text: `test_value_1`,
      body_html: `test_value_1`,
      direction: `test_value_1`,
      sent_at: `test_1`,
      received_at: `test_1`,
      opened_at: `test_1`,
      open_count: 101,
    },
  },
  EmailTemplate: {
    create: {
      name: 'Test Name',
      subject: 'test_value',
      body_html: 'test_value',
      body_text: 'test_value',
      category: 'test_value',
      is_active: true,
    },
    update: {
      name: `Test Name 1`,
      subject: `test_value_1`,
      body_html: `test_value_1`,
      body_text: `test_value_1`,
      category: `test_value_1`,
      is_active: `test_1`,
    },
  },
  Product: {
    create: {
      name: 'Test Name',
      sku: 'test_value',
      description: 'test_value',
      unit_price: 123.45,
      currency: 'test_value',
      is_active: true,
    },
    update: {
      name: `Test Name 1`,
      sku: `test_value_1`,
      description: `test_value_1`,
      unit_price: 101.50,
      currency: `test_value_1`,
      is_active: `test_1`,
    },
  },
  Quote: {
    create: {
      quote_number: 'test_value',
      status: 'test_value',
      valid_until: new Date().toISOString(),
      subtotal: 123.45,
      discount_amount: 123.45,
      tax_amount: 123.45,
      total_amount: 123.45,
      terms: 'test_value',
      notes: 'test_value',
    },
    update: {
      quote_number: `test_value_1`,
      status: `test_value_1`,
      valid_until: `test_1`,
      subtotal: 101.50,
      discount_amount: 101.50,
      tax_amount: 101.50,
      total_amount: 101.50,
      terms: `test_value_1`,
      notes: `test_value_1`,
    },
  },
  QuoteItem: {
    create: {
      description: 'test_value',
      quantity: 123,
      unit_price: 123.45,
      discount_percent: 123.45,
      total_price: 123.45,
    },
    update: {
      description: `test_value_1`,
      quantity: 101,
      unit_price: 101.50,
      discount_percent: 101.50,
      total_price: 101.50,
    },
  },
  User: {
    create: {
      email: 'test@example.com',
      first_name: 'Test Name',
      last_name: 'Test Name',
      role: 'test_value',
      is_active: true,
      last_login: new Date().toISOString(),
    },
    update: {
      email: `test1@example.com`,
      first_name: `Test Name 1`,
      last_name: `Test Name 1`,
      role: `test_value_1`,
      is_active: `test_1`,
      last_login: `test_1`,
    },
  },
  Team: {
    create: {
      name: 'Test Name',
    },
    update: {
      name: `Test Name 1`,
    },
  },
};

// Mock value helper
function mockValue(type: string, fieldName: string): any {
  const typeLower = type.toLowerCase();

  if (typeLower.includes('string') || typeLower.includes('text') || typeLower.includes('varchar')) {
    if (fieldName.includes('email')) {
      return 'test@example.com';
    }
    if (fieldName.includes('name')) {
      return 'Test Name';
    }
    return 'test_value';
  }

  if (typeLower.includes('int') || typeLower.includes('number') || typeLower.includes('integer')) {
    return 123;
  }

  if (typeLower.includes('decimal') || typeLower.includes('float') || typeLower.includes('double')) {
    return 123.45;
  }

  if (typeLower.includes('bool') || typeLower.includes('boolean')) {
    return true;
  }

  if (typeLower.includes('date') || typeLower.includes('time')) {
    return new Date().toISOString();
  }

  return 'test_value';
}

// Mock unique value helper
function mockUniqueValue(type: string, fieldName: string, index: number): any {
  const typeLower = type.toLowerCase();

  if (typeLower.includes('string') || typeLower.includes('text') || typeLower.includes('varchar')) {
    if (fieldName.includes('email')) {
      return `test${index}@example.com`;
    }
    if (fieldName.includes('name')) {
      return `Test Name ${index}`;
    }
    return `test_value_${index}`;
  }

  if (typeLower.includes('int') || typeLower.includes('number') || typeLower.includes('integer')) {
    return 100 + index;
  }

  if (typeLower.includes('decimal') || typeLower.includes('float') || typeLower.includes('double')) {
    return (100.50 + index).toFixed(2);
  }

  return `test_${index}`;
}
