/**
 * `pg`, backed by PostgreSQL compiled to WebAssembly.
 *
 * This package is installed under the name `pg`, so every `import { Pool } from
 * "pg"` in the generated backend resolves here instead of to the network
 * driver. That is the entire database difference between an application
 * generated by `appwithai` and one generated by `appwithai-wasm`: not one line
 * of the backend's own source changes — not the Nest database module, not
 * better-auth, not the migration runner, not the seeds — because none of them
 * ever knew what was on the other side of a `Pool`.
 *
 * The alternative was to rewrite those five files in the generated output. That
 * works until someone edits one of them upstream, at which point the rewrite
 * silently stops matching and the overlay produces an application that still
 * dials TCP. Substituting the driver cannot go stale that way.
 *
 * What it implements is the surface Kysely's `PostgresDialect` and better-auth's
 * Kysely adapter actually use: `new Pool(config)`, `pool.connect()`, a client
 * with `query(sql, params)` and `release()`, `pool.query(...)`, `pool.end()`.
 * Cursors and COPY are not implemented and say so, because a driver that
 * pretends to stream and instead buffers a table is worse than one that
 * refuses.
 *
 * There is one PGlite instance per process, shared by every Pool. PGlite is an
 * embedded server, not a connection: a second instance on the same directory is
 * a second Postgres on the same files, and it fails in ways that read like
 * corruption rather than like a mistake.
 */

const { PGlite } = require("@electric-sql/pglite");

let instance = null;
/**
 * How many pools are open.
 *
 * PGlite is one embedded server shared by every `Pool` in the process, so
 * `end()` cannot simply close it: `main.ts` opens a pool to seed the
 * administrator and ends it while the Nest module's pool is still serving.
 * Nor can `end()` do nothing, which is where this started — the server stays
 * up, the event loop never empties, and `npm run db:setup` finishes its work
 * and then hangs forever with nothing left to do.
 *
 * Counting is the answer to both: the last pool out closes the database.
 */
let openPools = 0;

/**
 * Where the database lives.
 *
 * `PGLITE_DATA_DIR` wins. A `DATABASE_URL` that is not a `postgres://` URL is
 * taken as a path, so an application can be pointed at a directory the same way
 * it would be pointed at a server. Otherwise `./pgdata` beside the backend.
 * `memory://` is honoured, which is what a test run wants.
 */
function resolveDataDir() {
  const explicit = process.env.PGLITE_DATA_DIR;
  if (explicit) return explicit;

  const url = process.env.DATABASE_URL;
  if (url && !/^postgres(ql)?:\/\//i.test(url)) return url;

  return "./pgdata";
}

function client() {
  if (!instance) {
    const dataDir = resolveDataDir();
    instance = PGlite.create(dataDir).then((created) => {
      if (process.env.PGLITE_QUIET !== "true") {
        console.log(`✓ PostgreSQL (WebAssembly) ready at ${dataDir}`);
      }
      return created;
    });
  }
  return instance;
}

/** `INSERT INTO x …` -> `INSERT`. Kysely reads `command` to shape its result. */
function commandOf(sql) {
  const match = String(sql).trim().match(/^[a-zA-Z]+/);
  return match ? match[0].toUpperCase() : "SELECT";
}

async function run(sql, parameters) {
  const pg = await client();
  const text = typeof sql === "string" ? sql : sql.text;
  const values = parameters ?? (typeof sql === "object" ? sql.values : undefined) ?? [];

  // `exec` handles multi-statement scripts, which `query` refuses; migrations
  // and seeds routinely send one. Only used when there is nothing to bind,
  // because `exec` takes no parameters.
  if (!values.length && /;\s*\S/.test(text.replace(/;\s*$/, ""))) {
    const results = await pg.exec(text);
    const last = results[results.length - 1] ?? {};
    return {
      command: commandOf(text),
      rowCount: last.affectedRows ?? (last.rows ? last.rows.length : 0),
      rows: last.rows ?? [],
      fields: last.fields ?? [],
    };
  }

  const result = await pg.query(text, values);
  return {
    command: commandOf(text),
    // `rowCount` is what `pg` reports and what Kysely turns into
    // `numAffectedRows`. For a SELECT, PGlite reports 0 affected rows, and a
    // caller checking rowCount on a read would conclude it found nothing.
    rowCount: result.rows && result.rows.length ? result.rows.length : (result.affectedRows ?? 0),
    rows: result.rows ?? [],
    fields: result.fields ?? [],
  };
}

class Client {
  constructor(config) {
    this.config = config ?? {};
  }

  async connect() {
    await client();
    return this;
  }

  query(sql, parameters, callback) {
    if (typeof parameters === "function") {
      callback = parameters;
      parameters = undefined;
    }
    const promise = run(sql, parameters);
    if (!callback) return promise;
    promise.then((result) => callback(null, result), (error) => callback(error));
    return undefined;
  }

  release() {
    // One embedded server, one connection: there is nothing to hand back.
  }

  async end() {
    // A client released back to its pool closes nothing.
  }

  on() {
    return this;
  }
}

class Pool extends Client {
  constructor(config) {
    super(config);
    openPools += 1;
    this.ended = false;
  }

  async connect() {
    await client();
    return new Client(this.config);
  }

  async end() {
    if (this.ended) return;
    this.ended = true;
    openPools -= 1;
    if (openPools <= 0) await shutdown();
  }

  get totalCount() { return 1; }
  get idleCount() { return 1; }
  get waitingCount() { return 0; }
}

/**
 * Shut the embedded server down.
 *
 * Called when the last pool ends, and available directly for tests. Safe to
 * call twice, and safe to call before anything opened the database.
 */
async function shutdown() {
  if (!instance) return;
  const pending = instance;
  instance = null;
  openPools = 0;
  const pg = await pending;
  await pg.close();
}

class Cursor {
  constructor() {
    throw new Error(
      "Cursors are not supported by the WebAssembly Postgres driver. " +
        "Use LIMIT/OFFSET, or the server build of this application."
    );
  }
}

module.exports = {
  Pool,
  Client,
  Cursor,
  shutdown,
  resolveDataDir,
  types: { setTypeParser: () => {}, getTypeParser: () => (value) => value },
  escapeIdentifier: (value) => `"${String(value).replace(/"/g, '""')}"`,
  escapeLiteral: (value) => `'${String(value).replace(/'/g, "''")}'`,
};
module.exports.default = module.exports;
