/**
 * Navigation Journey Tests for QA Test Project
 * Generated by ERDwithAI
 */

sap.ui.define(
  ["sap/ui/test/opaQunit", "./pages/App", "./pages/List", "./pages/Detail"],
  (opaTest) => ({
    run: () => {
      QUnit.module("Navigation");

      opaTest("Should see the app", (Given, When, Then) => {
        // Arrangements
        Given.iStartMyApp();

        // Assertions
        Then.onTheAppPage.iShouldSeeTheApp();

        // Cleanup
        Then.iTeardownMyApp();
      });

      opaTest("Should navigate to list view", (Given, When, Then) => {
        Given.iStartMyApp();

        // Navigate to first entity
        When.onTheAppPage.iNavigateToEntity("USERS");
        Then.onTheListPage.iShouldSeeTheList();

        Then.iTeardownMyApp();
      });

      opaTest("Should navigate from list to detail", (Given, When, Then) => {
        Given.iStartMyApp();

        When.onTheAppPage.iNavigateToEntity("USERS");
        When.onTheListPage.iSelectItem(0);
        Then.onTheDetailPage.iShouldSeeTheDetailView();

        Then.iTeardownMyApp();
      });

      opaTest("Should navigate back from detail to list", (Given, When, Then) => {
        Given.iStartMyApp();

        When.onTheAppPage.iNavigateToEntity("USERS");
        When.onTheListPage.iSelectItem(0);
        When.onTheDetailPage.iPressBack();
        Then.onTheListPage.iShouldSeeTheList();

        Then.iTeardownMyApp();
      });

      opaTest("Should handle deep linking", (Given, When, Then) => {
        Given.iStartMyAppWithHash("#/bus-users");
        Then.onTheListPage.iShouldSeeTheList();

        Then.iTeardownMyApp();
      });
    },
  })
);
