/**
 * Database Service with Knex.js
 *
 * Generated: 2026-05-09T16:10:52.339Z
 */

import { Injectable, Inject, NotFoundException, ConflictException } from '@nestjs/common';
import type { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';
import { KNEX_CONNECTION } from './database.constants';

export interface PaginationOptions {
  page?: number;
  limit?: number;
  orderBy?: string;
  orderDir?: 'asc' | 'desc';
}

export interface PaginatedResult<T> {
  data: T[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}

@Injectable()
export class DatabaseService {
  public readonly knex: Knex;

  constructor(
    @Inject(KNEX_CONNECTION) knex: Knex,
  ) {
    this.knex = knex;
  }

  /**
   * Get the Knex instance for direct queries
   * @deprecated Use the public `knex` property directly
   */
  getKnex(): Knex {
    return this.knex;
  }

  /**
   * Start a transaction
   */
  async transaction<T>(callback: (trx: Knex.Transaction) => Promise<T>): Promise<T> {
    return this.knex.transaction(callback);
  }

  /**
   * Find all records in a table with pagination
   */
  async findAll<T>(
    tableName: string,
    options: PaginationOptions = {},
    filters: Record<string, any> = {},
  ): Promise<PaginatedResult<T>> {
    const {
      page = 1,
      limit = 20,
      orderBy = 'created_at',
      orderDir = 'desc',
    } = options;

    const offset = (page - 1) * limit;

    // Build query
    let query = this.knex(tableName)
      .whereNull('deleted_at');

    // Apply filters
    for (const [key, value] of Object.entries(filters)) {
      if (value !== undefined && value !== null && value !== '') {
        if (typeof value === 'object' && value !== null && 'operator' in value && 'value' in value) {
          // Handle operator objects for comparison queries: { operator: '>', value: '...' }
          const { operator, value: filterValue } = value;
          query = query.where(key, operator, filterValue);
        } else if (typeof value === 'string' && value.includes('%')) {
          query = query.where(key, 'ilike', value);
        } else {
          query = query.where(key, value);
        }
      }
    }

    // Get total count
    const [{ count }] = await query.clone().count('* as count');
    const total = parseInt(count as string, 10);

    // Get data with pagination
    const data = await query
      .orderBy(orderBy, orderDir)
      .limit(limit)
      .offset(offset);

    return {
      data: data as T[],
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Find a single record by ID
   */
  async findById<T>(tableName: string, id: string): Promise<T | null> {
    // The primary key column is always 'id' in the database schema
    const record = await this.knex(tableName)
      .where('id', id)
      .whereNull('deleted_at')
      .first();

    return record as T | null;
  }

  /**
   * Find a single record by ID or throw NotFoundException
   */
  async findByIdOrFail<T>(tableName: string, id: string): Promise<T> {
    const record = await this.findById<T>(tableName, id);

    if (!record) {
      throw new NotFoundException(`Record not found in ${tableName} with id ${id}`);
    }

    return record;
  }

  /**
   * Find records by a specific field
   */
  async findBy<T>(
    tableName: string,
    field: string,
    value: any,
  ): Promise<T[]> {
    return this.knex(tableName)
      .where(field, value)
      .whereNull('deleted_at') as Promise<T[]>;
  }

  /**
   * Create a new record
   */
  async create<T>(tableName: string, data: Partial<T>): Promise<T> {
    // Use provided id (e.g. pre-generated by caller) or generate a new one
    const id = (data as any).id || uuidv4();

    const record = {
      ...data,
      id,
      version: 1,
      created_at: Date.now(),
      updated_at: Date.now(),
    };

    await this.knex(tableName).insert(record);

    return this.findByIdOrFail<T>(tableName, id);
  }

  /**
   * Update an existing record with optimistic concurrency control
   */
  async update<T>(
    tableName: string,
    id: string,
    data: Partial<T>,
    expectedVersion?: number,
  ): Promise<T> {
    // Check if record exists
    const existing = await this.findByIdOrFail<T & { version: number }>(tableName, id);

    // Optimistic concurrency check
    if (expectedVersion !== undefined && existing.version !== expectedVersion) {
      throw new ConflictException(
        `Record has been modified by another user. Expected version ${expectedVersion}, current version ${existing.version}`,
      );
    }

    // Update record - use 'id' as the primary key column
    await this.knex(tableName)
      .where('id', id)
      .update({
        ...data,
        version: this.knex.raw('version + 1'),
        updated_at: new Date(),
      });

    return this.findByIdOrFail<T>(tableName, id);
  }

  /**
   * Soft delete a record
   */
  async softDelete(tableName: string, id: string): Promise<boolean> {
    // Check if record exists
    await this.findByIdOrFail(tableName, id);

    // Soft delete - use 'id' as the primary key column
    const result = await this.knex(tableName)
      .where('id', id)
      .update({
        deleted_at: new Date(),
        updated_at: new Date(),
      });

    return result > 0;
  }

  /**
   * Permanently delete a record
   */
  async hardDelete(tableName: string, id: string): Promise<boolean> {
    // Hard delete - use 'id' as the primary key column
    const result = await this.knex(tableName)
      .where('id', id)
      .delete();

    return result > 0;
  }

  /**
   * Restore a soft-deleted record
   */
  async restore(tableName: string, id: string): Promise<boolean> {
    // Restore - use 'id' as the primary key column
    const result = await this.knex(tableName)
      .where('id', id)
      .whereNotNull('deleted_at')
      .update({
        deleted_at: null,
        updated_at: new Date(),
      });

    return result > 0;
  }

  /**
   * Count records in a table
   */
  async count(tableName: string, filters: Record<string, any> = {}): Promise<number> {
    let query = this.knex(tableName).whereNull('deleted_at');

    for (const [key, value] of Object.entries(filters)) {
      if (value !== undefined && value !== null) {
        query = query.where(key, value);
      }
    }

    const [{ count }] = await query.count('* as count');
    return parseInt(count as string, 10);
  }

  /**
   * Check if a record exists
   */
  async exists(tableName: string, id: string): Promise<boolean> {
    // Use 'id' as the primary key column
    const result = await this.knex(tableName)
      .where('id', id)
      .whereNull('deleted_at')
      .first();

    return !!result;
  }

  /**
   * Execute a raw query
   */
  async raw<T>(sql: string, bindings: any[] = []): Promise<T> {
    const result = await this.knex.raw(sql, bindings);
    return result.rows as T;
  }

  /**
   * Close database connection
   */
  async destroy(): Promise<void> {
    await this.knex.destroy();
    console.log('✓ Database connection closed');
  }
}
