/**
 * Test Setup for openui5-odatav4-test-app OData Backend
 * Generated by ERDwithAI
 *
 * Provides test utilities and fixtures for OData V4 server testing
 */

import express, { type Express } from "express";
import Knex from "knex";
import { vi } from "vitest";
import knexConfig from "../knexfile";

// Test database instance
let testDb: Knex.Knex;

// Test express app
let testApp: Express;

/**
 * Initialize test database connection
 */
export async function initTestDatabase(): Promise<Knex.Knex> {
  if (!testDb) {
    testDb = Knex({
      client: "better-sqlite3",
      connection: {
        filename: ":memory:",
      },
      useNullAsDefault: true,
      migrations: {
        directory: "./migrations",
      },
      seeds: {
        directory: "./seeds",
      },
    });

    // Run migrations
    await testDb.migrate.latest();
    // Run seeds (only if seed files exist)
    try {
      await testDb.seed.run();
    } catch (_e) {
      // Seeds may not exist, continue
    }
  }
  return testDb;
}

/**
 * Close test database connection
 */
export async function closeTestDatabase(): Promise<void> {
  if (testDb) {
    await testDb.destroy();
    testDb = undefined as any;
  }
}

/**
 * Get test database instance
 */
export function getTestDatabase(): Knex.Knex {
  if (!testDb) {
    throw new Error("Test database not initialized");
  }
  return testDb;
}

/**
 * Create test express app with OData routes
 */
export async function createTestApp(): Promise<Express> {
  const app = express();
  app.use(express.json());

  // Import and setup OData routes
  // This should be customized based on your OData server setup

  return app;
}

/**
 * Generate test UUID
 */
export function generateTestId(): string {
  return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Test data factories for entities
 */
export const TestDataFactory = {
  /**
   * Create test CUSTOMER data
   */
  createCUSTOMER(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: "Test ",
      email: "Test ",
      phone: "Test ",
      city: "Test ",
      status: "Test ",
      created_at: "2024-01-15",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test ORDER data
   */
  createORDER(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      customer_id: "Test ",
      order_date: "2024-01-15",
      total_amount: 10.99,
      status: "Test ",
      created_at: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test ORDER_ITEM data
   */
  createORDERITEM(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      order_id: "Test ",
      product_id: "Test ",
      quantity: 1,
      unit_price: 10.99,
      line_total: 10.99,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test PRODUCT data
   */
  createPRODUCT(overrides: Partial<any> = {}): any {
    return {
      id: generateTestId(),
      name: "Test ",
      description: "Test ",
      price: 10.99,
      stock_quantity: 1,
      category: "Test ",
      is_active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      ...overrides,
    };
  },
};

/**
 * Clean up test data from database
 */
export async function cleanupTestData(): Promise<void> {
  const db = await initTestDatabase();

  // Delete in reverse order of dependencies
  await db("bus_customer").del();
  await db("bus_order").del();
  await db("bus_order_item").del();
  await db("bus_product").del();
}

/**
 * Reset test database state
 */
export async function resetDatabase(): Promise<void> {
  await cleanupTestData();
  const db = await initTestDatabase();
  await db.seed.run();
}

/**
 * OData query helpers
 */
export const ODataTestHelpers = {
  /**
   * Build OData filter query string
   */
  buildFilter(field: string, operator: string, value: any): string {
    switch (operator) {
      case "eq":
        return `${field} eq '${value}'`;
      case "ne":
        return `${field} ne '${value}'`;
      case "gt":
        return `${field} gt ${value}`;
      case "ge":
        return `${field} ge ${value}`;
      case "lt":
        return `${field} lt ${value}`;
      case "le":
        return `${field} le ${value}`;
      case "contains":
        return `contains(${field}, '${value}')`;
      case "startswith":
        return `startswith(${field}, '${value}')`;
      case "endswith":
        return `endswith(${field}, '${value}')`;
      default:
        return `${field} eq '${value}'`;
    }
  },

  /**
   * Build OData orderby query string
   */
  buildOrderBy(field: string, direction: "asc" | "desc" = "asc"): string {
    return `${field} ${direction}`;
  },

  /**
   * Build OData select query string
   */
  buildSelect(fields: string[]): string {
    return fields.join(",");
  },

  /**
   * Build OData expand query string
   */
  buildExpand(associations: string[]): string {
    return associations.join(",");
  },

  /**
   * Parse OData response
   */
  parseODataResponse(response: any): any {
    if (response.value) {
      return response.value;
    }
    return response;
  },

  /**
   * Verify OData metadata response
   */
  verifyMetadata(metadata: string): boolean {
    return metadata.includes("$metadata") && metadata.includes("EntityType");
  },
};

/**
 * Assert OData response structure
 */
export function assertODataResponse(response: any) {
  expect(response).toBeDefined();
  if (Array.isArray(response.value)) {
    // Collection response
    expect(response["@odata.context"]).toBeDefined();
  } else if (response["@odata.context"]) {
    // Single entity response
    expect(response["@odata.context"]).toBeDefined();
  }
}

/**
 * Assert OData error response
 */
export function assertODataError(response: any, expectedStatus: number) {
  expect(response.error).toBeDefined();
  expect(response.error.code).toBeDefined();
  expect(response.error.message).toBeDefined();
}
