/**
 * Test Data Fixtures for CRM App
 * Generated by ERDwithAI
 */

// Test data for all entities
export const testData = {
  ACCOUNT: {
    create: {
      name: 'Test Name',
      email: 'test@example.com',
      phone: '+1234567890',
    },
    update: {
      name: `Test Name 1`,
      email: `test1@example.com`,
      phone: `test_value_1`,
    },
  },
  CONTACT: {
    create: {
      first_name: 'Test Name',
      last_name: 'Test Name',
      email: 'test@example.com',
      phone: '+1234567890',
    },
    update: {
      first_name: `Test Name 1`,
      last_name: `Test Name 1`,
      email: `test1@example.com`,
      phone: `test_value_1`,
    },
  },
  OPPORTUNITY: {
    create: {
      name: 'Test Name',
      amount: 123.45,
      stage: 'test_value',
      close_date: new Date().toISOString(),
    },
    update: {
      name: `Test Name 1`,
      amount: 101.50,
      stage: `test_value_1`,
      close_date: `test_1`,
    },
  },
  ACTIVITY: {
    create: {
      type: 'test_value',
      description: 'test_value',
      activity_date: new Date().toISOString(),
    },
    update: {
      type: `test_value_1`,
      description: `test_value_1`,
      activity_date: `test_1`,
    },
  },
};

// Mock value helper
function mockValue(type: string, fieldName: string): any {
  const typeLower = type.toLowerCase();

  if (typeLower.includes('string') || typeLower.includes('text') || typeLower.includes('varchar')) {
    if (fieldName.includes('email')) {
      return 'test@example.com';
    }
    if (fieldName.includes('name')) {
      return 'Test Name';
    }
    return 'test_value';
  }

  if (typeLower.includes('int') || typeLower.includes('number') || typeLower.includes('integer')) {
    return 123;
  }

  if (typeLower.includes('decimal') || typeLower.includes('float') || typeLower.includes('double')) {
    return 123.45;
  }

  if (typeLower.includes('bool') || typeLower.includes('boolean')) {
    return true;
  }

  if (typeLower.includes('date') || typeLower.includes('time')) {
    return new Date().toISOString();
  }

  return 'test_value';
}

// Mock unique value helper
function mockUniqueValue(type: string, fieldName: string, index: number): any {
  const typeLower = type.toLowerCase();

  if (typeLower.includes('string') || typeLower.includes('text') || typeLower.includes('varchar')) {
    if (fieldName.includes('email')) {
      return `test${index}@example.com`;
    }
    if (fieldName.includes('name')) {
      return `Test Name ${index}`;
    }
    return `test_value_${index}`;
  }

  if (typeLower.includes('int') || typeLower.includes('number') || typeLower.includes('integer')) {
    return 100 + index;
  }

  if (typeLower.includes('decimal') || typeLower.includes('float') || typeLower.includes('double')) {
    return (100.50 + index).toFixed(2);
  }

  return `test_${index}`;
}
