/**
 * Test Setup for CRM Regenerated Backend
 * Generated by ERDwithAI
 *
 * Provides test utilities, fixtures, and database setup
 */

import { Test, TestingModule } from '@nestjs/testing';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { KYSELY_CONNECTION } from '../src/database/database.constants';
import { Kysely, MemoryDialect } from 'kysely';

// Use in-memory dialect for tests instead of SQLite
// This avoids native module loading issues in test environments

// Test database instance
let testDb: Kysely<any>;

// Test application instance
let testApp: NestFastifyApplication;

/**
 * Initialize test database connection
 */
export async function initTestDatabase(): Promise<Kysely<any>> {
  if (!testDb) {
    // Use in-memory dialect for tests (no native modules required)
    testDb = new Kysely({
      dialect: new MemoryDialect(),
    });
  }
  return testDb;
}

/**
 * Close test database connection
 */
export async function closeTestDatabase(): Promise<void> {
  if (testDb) {
    try {
      await testDb.destroy();
    } catch (_e) {
      // Already closed
    }
    testDb = undefined as any;
  }
}

/**
 * Create test application
 */
export async function createTestApp(module: any): Promise<NestFastifyApplication> {
  const builder = Test.createTestingModule({
    imports: [module],
  });

  // Override KYSELY_CONNECTION with the shared test database so the NestJS app
  // uses the same in-memory SQLite database as the test helpers.
  if (testDb) {
    builder.overrideProvider(KYSELY_CONNECTION).useValue(testDb);
  }

  const moduleFixture: TestingModule = await builder.compile();

  const app = moduleFixture.createNestApplication<NestFastifyApplication>(
    new FastifyAdapter()
  );

  // Match production configuration
  app.setGlobalPrefix('api');

  await app.init();
  await app.getHttpAdapter().getInstance().ready();

  return app;
}

/**
 * Close test application
 */
export async function closeTestApp(app: NestFastifyApplication): Promise<void> {
  if (app) {
    await app.close();
  }
}

/**
 * Generate test UUID
 */
export function generateTestId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Test data factories
 */
export const TestDataFactory = {
  /**
   * Create test Company data
   */
  createCompany(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      industry: `Test Industry ${uid}`,
      website: `Test Website ${uid}`,
      phone: `Test Phone ${uid}`,
      email: `Test Email ${uid}`,
      employee_count: 1,
      annual_revenue: 10.99,
      status: `Test Status ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Contact data
   */
  createContact(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      company_id: `Test Company Id ${uid}`,
      first_name: `Test First Name ${uid}`,
      last_name: `Test Last Name ${uid}`,
      email: `Test Email ${uid}`,
      phone: `Test Phone ${uid}`,
      mobile: `Test Mobile ${uid}`,
      job_title: `Test Job Title ${uid}`,
      department: `Test Department ${uid}`,
      status: `Test Status ${uid}`,
      lead_source: `Test Lead Source ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Deal data
   */
  createDeal(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      company_id: `Test Company Id ${uid}`,
      contact_id: `Test Contact Id ${uid}`,
      name: `Test Name ${uid}`,
      amount: 10.99,
      currency: `Test Currency ${uid}`,
      stage: `Test Stage ${uid}`,
      probability: 1,
      expected_close_date: '2024-01-15',
      actual_close_date: '2024-01-15',
      status: `Test Status ${uid}`,
      description: 'Test text content',
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test DealStage data
   */
  createDealStage(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      pipeline_id: `Test Pipeline Id ${uid}`,
      name: `Test Name ${uid}`,
      sort_order: 1,
      default_probability: 1,
      is_won: true,
      is_lost: true,
      ...overrides,
    };
  },

  /**
   * Create test Pipeline data
   */
  createPipeline(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      is_default: true,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Activity data
   */
  createActivity(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      contact_id: `Test Contact Id ${uid}`,
      company_id: `Test Company Id ${uid}`,
      deal_id: `Test Deal Id ${uid}`,
      activity_type: `Test Activity Type ${uid}`,
      subject: `Test Subject ${uid}`,
      description: 'Test text content',
      scheduled_at: new Date().toISOString(),
      completed_at: new Date().toISOString(),
      duration_minutes: 1,
      status: `Test Status ${uid}`,
      owner_id: `Test Owner Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Note data
   */
  createNote(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      contact_id: `Test Contact Id ${uid}`,
      company_id: `Test Company Id ${uid}`,
      deal_id: `Test Deal Id ${uid}`,
      content: 'Test text content',
      is_pinned: true,
      author_id: `Test Author Id ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test Task data
   */
  createTask(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      contact_id: `Test Contact Id ${uid}`,
      company_id: `Test Company Id ${uid}`,
      deal_id: `Test Deal Id ${uid}`,
      title: `Test Title ${uid}`,
      description: 'Test text content',
      priority: `Test Priority ${uid}`,
      status: `Test Status ${uid}`,
      due_date: '2024-01-15',
      completed_at: new Date().toISOString(),
      assigned_to: `Test Assigned To ${uid}`,
      created_by: `Test Created By ${uid}`,
      ...overrides,
    };
  },

  /**
   * Create test EmailMessage data
   */
  createEmailMessage(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      contact_id: `Test Contact Id ${uid}`,
      deal_id: `Test Deal Id ${uid}`,
      thread_id: `Test Thread Id ${uid}`,
      subject: `Test Subject ${uid}`,
      body_text: 'Test text content',
      body_html: 'Test text content',
      direction: `Test Direction ${uid}`,
      sent_at: new Date().toISOString(),
      received_at: new Date().toISOString(),
      opened_at: new Date().toISOString(),
      open_count: 1,
      ...overrides,
    };
  },

  /**
   * Create test EmailTemplate data
   */
  createEmailTemplate(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      subject: `Test Subject ${uid}`,
      body_html: 'Test text content',
      body_text: 'Test text content',
      category: `Test Category ${uid}`,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Product data
   */
  createProduct(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      sku: `Test Sku ${uid}`,
      description: 'Test text content',
      unit_price: 10.99,
      currency: `Test Currency ${uid}`,
      is_active: true,
      ...overrides,
    };
  },

  /**
   * Create test Quote data
   */
  createQuote(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      deal_id: `Test Deal Id ${uid}`,
      quote_number: `Test Quote Number ${uid}`,
      status: `Test Status ${uid}`,
      valid_until: '2024-01-15',
      subtotal: 10.99,
      discount_amount: 10.99,
      tax_amount: 10.99,
      total_amount: 10.99,
      terms: 'Test text content',
      notes: 'Test text content',
      ...overrides,
    };
  },

  /**
   * Create test QuoteItem data
   */
  createQuoteItem(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      quote_id: `Test Quote Id ${uid}`,
      product_id: `Test Product Id ${uid}`,
      description: `Test Description ${uid}`,
      quantity: 1,
      unit_price: 10.99,
      discount_percent: 10.99,
      total_price: 10.99,
      ...overrides,
    };
  },

  /**
   * Create test User data
   */
  createUser(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      email: `Test Email ${uid}`,
      first_name: `Test First Name ${uid}`,
      last_name: `Test Last Name ${uid}`,
      role: `Test Role ${uid}`,
      team_id: `Test Team Id ${uid}`,
      is_active: true,
      last_login: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test Team data
   */
  createTeam(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      manager_id: `Test Manager Id ${uid}`,
      ...overrides,
    };
  },

};

/**
 * Clean up test data from database
 */
export async function cleanupTestData(): Promise<void> {
  const db = await initTestDatabase();

  // Delete in reverse order of dependencies
  try {
    await db.deleteFrom('bus_company').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_contact').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_deal').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_deal_stage').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_pipeline').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_activity').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_note').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_task').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_email_message').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_email_template').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_product').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_quote').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_quote_item').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_user').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_team').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
}

/**
 * Reset test database state
 */
export async function resetDatabase(): Promise<void> {
  await cleanupTestData();
}
