/**
 * Test Setup for my-app Frontend
 * Generated by ERDwithAI
 *
 * Provides test utilities and mocks for React/Next.js testing
 */

import React from 'react';
import { vi } from 'vitest';
import { render, RenderOptions } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '@testing-library/jest-dom';

// Mock auth context - Sidebar and other components use useAuth
vi.mock('../src/contexts/auth-context', () => ({
  useAuth: () => ({
    user: { id: 'test-user', email: 'test@example.com', name: 'Test User', role: 'admin' },
    isLoading: false,
    isAuthenticated: true,
    isAdmin: () => true,
    hasRole: (_role: string) => true,
    hasPermission: (_perm: string) => true,
    signIn: vi.fn(),
    signOut: vi.fn(),
  }),
  AuthProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock translations - DynamicTable and other components use useTranslations
vi.mock('../src/lib/translations', () => ({
  useTranslations: () => ({
    t: (key: string) => key,
    locale: 'en',
  }),
  TranslationProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock next/navigation
vi.mock('next/navigation', () => ({
  useRouter: () => ({
    push: vi.fn(),
    replace: vi.fn(),
    prefetch: vi.fn(),
    back: vi.fn(),
    forward: vi.fn(),
    refresh: vi.fn(),
  }),
  usePathname: () => '/',
  useSearchParams: () => new URLSearchParams(),
  useParams: () => ({}),
}));

// Mock next/link
vi.mock('next/link', () => ({
  default: ({ children, href }: { children: React.ReactNode; href: string }) => (
    <a href={href}>{children}</a>
  ),
}));

// Create a test query client
export function createTestQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: 0,
        staleTime: 0,
      },
      mutations: {
        retry: false,
      },
    },
  });
}

// Custom render function with providers
interface CustomRenderOptions extends Omit<RenderOptions, 'wrapper'> {
  queryClient?: QueryClient;
}

export function renderWithProviders(
  ui: React.ReactElement,
  options: CustomRenderOptions = {}
) {
  const { queryClient = createTestQueryClient(), ...renderOptions } = options;

  function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <QueryClientProvider client={queryClient}>
        {children}
      </QueryClientProvider>
    );
  }

  return {
    ...render(ui, { wrapper: Wrapper, ...renderOptions }),
    queryClient,
  };
}

// Re-export everything from testing-library
export * from '@testing-library/react';
export { renderWithProviders as render };

/**
 * Mock API responses
 */
export const mockApiResponses = {
  company: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        industry: 'Test Industry 1',
        website: 'Test Website 1',
        phone: 'Test Phone 1',
        email: 'Test Email 1',
        employee_count: 1,
        annual_revenue: 10.99,
        status: 'Test Status 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        industry: 'Test Industry 2',
        website: 'Test Website 2',
        phone: 'Test Phone 2',
        email: 'Test Email 2',
        employee_count: 2,
        annual_revenue: 20.99,
        status: 'Test Status 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      industry: 'Test Industry',
      website: 'Test Website',
      phone: 'Test Phone',
      email: 'Test Email',
      employee_count: 1,
      annual_revenue: 10.99,
      status: 'Test Status',
      owner_id: 'Test Owner Id',
    },
  },
  contact: {
    list: [
      {
        id: 'test-id-1',
        company_id: 'Test Company Id 1',
        first_name: 'Test First Name 1',
        last_name: 'Test Last Name 1',
        email: 'Test Email 1',
        phone: 'Test Phone 1',
        mobile: 'Test Mobile 1',
        job_title: 'Test Job Title 1',
        department: 'Test Department 1',
        status: 'Test Status 1',
        lead_source: 'Test Lead Source 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        company_id: 'Test Company Id 2',
        first_name: 'Test First Name 2',
        last_name: 'Test Last Name 2',
        email: 'Test Email 2',
        phone: 'Test Phone 2',
        mobile: 'Test Mobile 2',
        job_title: 'Test Job Title 2',
        department: 'Test Department 2',
        status: 'Test Status 2',
        lead_source: 'Test Lead Source 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      company_id: 'Test Company Id',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      email: 'Test Email',
      phone: 'Test Phone',
      mobile: 'Test Mobile',
      job_title: 'Test Job Title',
      department: 'Test Department',
      status: 'Test Status',
      lead_source: 'Test Lead Source',
      owner_id: 'Test Owner Id',
    },
  },
  deal: {
    list: [
      {
        id: 'test-id-1',
        company_id: 'Test Company Id 1',
        contact_id: 'Test Contact Id 1',
        name: 'Test Name 1',
        amount: 10.99,
        currency: 'Test Currency 1',
        stage: 'Test Stage 1',
        probability: 1,
        expected_close_date: '2024-01-15',
        actual_close_date: '2024-01-15',
        status: 'Test Status 1',
        description: 'Test text content',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        company_id: 'Test Company Id 2',
        contact_id: 'Test Contact Id 2',
        name: 'Test Name 2',
        amount: 20.99,
        currency: 'Test Currency 2',
        stage: 'Test Stage 2',
        probability: 2,
        expected_close_date: '2024-01-16',
        actual_close_date: '2024-01-16',
        status: 'Test Status 2',
        description: 'Test text content 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      company_id: 'Test Company Id',
      contact_id: 'Test Contact Id',
      name: 'Test Name',
      amount: 10.99,
      currency: 'Test Currency',
      stage: 'Test Stage',
      probability: 1,
      expected_close_date: '2024-01-15',
      actual_close_date: '2024-01-15',
      status: 'Test Status',
      description: 'Test text content',
      owner_id: 'Test Owner Id',
    },
  },
  dealStage: {
    list: [
      {
        id: 'test-id-1',
        pipeline_id: 'Test Pipeline Id 1',
        name: 'Test Name 1',
        sort_order: 1,
        default_probability: 1,
        is_won: true,
        is_lost: true,
      },
      {
        id: 'test-id-2',
        pipeline_id: 'Test Pipeline Id 2',
        name: 'Test Name 2',
        sort_order: 2,
        default_probability: 2,
        is_won: false,
        is_lost: false,
      },
    ],
    single: {
      id: 'test-id-1',
      pipeline_id: 'Test Pipeline Id',
      name: 'Test Name',
      sort_order: 1,
      default_probability: 1,
      is_won: true,
      is_lost: true,
    },
  },
  pipeline: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        is_default: true,
        is_active: true,
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        is_default: false,
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      is_default: true,
      is_active: true,
    },
  },
  activity: {
    list: [
      {
        id: 'test-id-1',
        contact_id: 'Test Contact Id 1',
        company_id: 'Test Company Id 1',
        deal_id: 'Test Deal Id 1',
        activity_type: 'Test Activity Type 1',
        subject: 'Test Subject 1',
        description: 'Test text content',
        scheduled_at: '2024-01-15T10:00:00Z',
        completed_at: '2024-01-15T10:00:00Z',
        duration_minutes: 1,
        status: 'Test Status 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        contact_id: 'Test Contact Id 2',
        company_id: 'Test Company Id 2',
        deal_id: 'Test Deal Id 2',
        activity_type: 'Test Activity Type 2',
        subject: 'Test Subject 2',
        description: 'Test text content 2',
        scheduled_at: '2024-01-16T10:00:00Z',
        completed_at: '2024-01-16T10:00:00Z',
        duration_minutes: 2,
        status: 'Test Status 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      contact_id: 'Test Contact Id',
      company_id: 'Test Company Id',
      deal_id: 'Test Deal Id',
      activity_type: 'Test Activity Type',
      subject: 'Test Subject',
      description: 'Test text content',
      scheduled_at: '2024-01-15T10:00:00Z',
      completed_at: '2024-01-15T10:00:00Z',
      duration_minutes: 1,
      status: 'Test Status',
      owner_id: 'Test Owner Id',
    },
  },
  note: {
    list: [
      {
        id: 'test-id-1',
        contact_id: 'Test Contact Id 1',
        company_id: 'Test Company Id 1',
        deal_id: 'Test Deal Id 1',
        content: 'Test text content',
        is_pinned: true,
        author_id: 'Test Author Id 1',
      },
      {
        id: 'test-id-2',
        contact_id: 'Test Contact Id 2',
        company_id: 'Test Company Id 2',
        deal_id: 'Test Deal Id 2',
        content: 'Test text content 2',
        is_pinned: false,
        author_id: 'Test Author Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      contact_id: 'Test Contact Id',
      company_id: 'Test Company Id',
      deal_id: 'Test Deal Id',
      content: 'Test text content',
      is_pinned: true,
      author_id: 'Test Author Id',
    },
  },
  task: {
    list: [
      {
        id: 'test-id-1',
        contact_id: 'Test Contact Id 1',
        company_id: 'Test Company Id 1',
        deal_id: 'Test Deal Id 1',
        title: 'Test Title 1',
        description: 'Test text content',
        priority: 'Test Priority 1',
        status: 'Test Status 1',
        due_date: '2024-01-15',
        completed_at: '2024-01-15T10:00:00Z',
        assigned_to: 'Test Assigned To 1',
        created_by: 'Test Created By 1',
      },
      {
        id: 'test-id-2',
        contact_id: 'Test Contact Id 2',
        company_id: 'Test Company Id 2',
        deal_id: 'Test Deal Id 2',
        title: 'Test Title 2',
        description: 'Test text content 2',
        priority: 'Test Priority 2',
        status: 'Test Status 2',
        due_date: '2024-01-16',
        completed_at: '2024-01-16T10:00:00Z',
        assigned_to: 'Test Assigned To 2',
        created_by: 'Test Created By 2',
      },
    ],
    single: {
      id: 'test-id-1',
      contact_id: 'Test Contact Id',
      company_id: 'Test Company Id',
      deal_id: 'Test Deal Id',
      title: 'Test Title',
      description: 'Test text content',
      priority: 'Test Priority',
      status: 'Test Status',
      due_date: '2024-01-15',
      completed_at: '2024-01-15T10:00:00Z',
      assigned_to: 'Test Assigned To',
      created_by: 'Test Created By',
    },
  },
  emailMessage: {
    list: [
      {
        id: 'test-id-1',
        contact_id: 'Test Contact Id 1',
        deal_id: 'Test Deal Id 1',
        thread_id: 'Test Thread Id 1',
        subject: 'Test Subject 1',
        body_text: 'Test text content',
        body_html: 'Test text content',
        direction: 'Test Direction 1',
        sent_at: '2024-01-15T10:00:00Z',
        received_at: '2024-01-15T10:00:00Z',
        opened_at: '2024-01-15T10:00:00Z',
        open_count: 1,
      },
      {
        id: 'test-id-2',
        contact_id: 'Test Contact Id 2',
        deal_id: 'Test Deal Id 2',
        thread_id: 'Test Thread Id 2',
        subject: 'Test Subject 2',
        body_text: 'Test text content 2',
        body_html: 'Test text content 2',
        direction: 'Test Direction 2',
        sent_at: '2024-01-16T10:00:00Z',
        received_at: '2024-01-16T10:00:00Z',
        opened_at: '2024-01-16T10:00:00Z',
        open_count: 2,
      },
    ],
    single: {
      id: 'test-id-1',
      contact_id: 'Test Contact Id',
      deal_id: 'Test Deal Id',
      thread_id: 'Test Thread Id',
      subject: 'Test Subject',
      body_text: 'Test text content',
      body_html: 'Test text content',
      direction: 'Test Direction',
      sent_at: '2024-01-15T10:00:00Z',
      received_at: '2024-01-15T10:00:00Z',
      opened_at: '2024-01-15T10:00:00Z',
      open_count: 1,
    },
  },
  emailTemplate: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        subject: 'Test Subject 1',
        body_html: 'Test text content',
        body_text: 'Test text content',
        category: 'Test Category 1',
        is_active: true,
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        subject: 'Test Subject 2',
        body_html: 'Test text content 2',
        body_text: 'Test text content 2',
        category: 'Test Category 2',
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      subject: 'Test Subject',
      body_html: 'Test text content',
      body_text: 'Test text content',
      category: 'Test Category',
      is_active: true,
    },
  },
  product: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        sku: 'Test Sku 1',
        description: 'Test text content',
        unit_price: 10.99,
        currency: 'Test Currency 1',
        is_active: true,
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        sku: 'Test Sku 2',
        description: 'Test text content 2',
        unit_price: 20.99,
        currency: 'Test Currency 2',
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      sku: 'Test Sku',
      description: 'Test text content',
      unit_price: 10.99,
      currency: 'Test Currency',
      is_active: true,
    },
  },
  quote: {
    list: [
      {
        id: 'test-id-1',
        deal_id: 'Test Deal Id 1',
        quote_number: 'Test Quote Number 1',
        status: 'Test Status 1',
        valid_until: '2024-01-15',
        subtotal: 10.99,
        discount_amount: 10.99,
        tax_amount: 10.99,
        total_amount: 10.99,
        terms: 'Test text content',
        notes: 'Test text content',
      },
      {
        id: 'test-id-2',
        deal_id: 'Test Deal Id 2',
        quote_number: 'Test Quote Number 2',
        status: 'Test Status 2',
        valid_until: '2024-01-16',
        subtotal: 20.99,
        discount_amount: 20.99,
        tax_amount: 20.99,
        total_amount: 20.99,
        terms: 'Test text content 2',
        notes: 'Test text content 2',
      },
    ],
    single: {
      id: 'test-id-1',
      deal_id: 'Test Deal Id',
      quote_number: 'Test Quote Number',
      status: 'Test Status',
      valid_until: '2024-01-15',
      subtotal: 10.99,
      discount_amount: 10.99,
      tax_amount: 10.99,
      total_amount: 10.99,
      terms: 'Test text content',
      notes: 'Test text content',
    },
  },
  quoteItem: {
    list: [
      {
        id: 'test-id-1',
        quote_id: 'Test Quote Id 1',
        product_id: 'Test Product Id 1',
        description: 'Test Description 1',
        quantity: 1,
        unit_price: 10.99,
        discount_percent: 10.99,
        total_price: 10.99,
      },
      {
        id: 'test-id-2',
        quote_id: 'Test Quote Id 2',
        product_id: 'Test Product Id 2',
        description: 'Test Description 2',
        quantity: 2,
        unit_price: 20.99,
        discount_percent: 20.99,
        total_price: 20.99,
      },
    ],
    single: {
      id: 'test-id-1',
      quote_id: 'Test Quote Id',
      product_id: 'Test Product Id',
      description: 'Test Description',
      quantity: 1,
      unit_price: 10.99,
      discount_percent: 10.99,
      total_price: 10.99,
    },
  },
  user: {
    list: [
      {
        id: 'test-id-1',
        email: 'Test Email 1',
        first_name: 'Test First Name 1',
        last_name: 'Test Last Name 1',
        role: 'Test Role 1',
        team_id: 'Test Team Id 1',
        is_active: true,
        last_login: '2024-01-15T10:00:00Z',
      },
      {
        id: 'test-id-2',
        email: 'Test Email 2',
        first_name: 'Test First Name 2',
        last_name: 'Test Last Name 2',
        role: 'Test Role 2',
        team_id: 'Test Team Id 2',
        is_active: false,
        last_login: '2024-01-16T10:00:00Z',
      },
    ],
    single: {
      id: 'test-id-1',
      email: 'Test Email',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      role: 'Test Role',
      team_id: 'Test Team Id',
      is_active: true,
      last_login: '2024-01-15T10:00:00Z',
    },
  },
  team: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        manager_id: 'Test Manager Id 1',
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        manager_id: 'Test Manager Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      manager_id: 'Test Manager Id',
    },
  },
};

/**
 * Create mock fetch function
 */
export function createMockFetch(responses: Record<string, unknown>) {
  return vi.fn((input: RequestInfo | URL, options?: RequestInit) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    const path = url.replace(/^https?:\/\/[^/]+/, '');

    // Find matching response
    for (const [pattern, response] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        return Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve(response),
          text: () => Promise.resolve(JSON.stringify(response)),
          headers: new Headers({ 'content-type': 'application/json' }),
        } as Response);
      }
    }

    // Default 404 response
    return Promise.resolve({
      ok: false,
      status: 404,
      json: () => Promise.resolve({ message: 'Not found' }),
      text: () => Promise.resolve('{"message": "Not found"}'),
      headers: new Headers({ 'content-type': 'application/json' }),
    } as Response);
  }) as unknown as typeof fetch;
}

/**
 * Wait for async operations
 */
export async function waitFor(callback: () => boolean | void, timeout = 5000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    try {
      const result = callback();
      if (result !== false) return;
    } catch {
      // Continue waiting
    }
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  throw new Error('Timeout waiting for condition');
}
