/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as BusopportunityImport } from './routes/bus_opportunity'
import { Route as BuscontactImport } from './routes/bus_contact'
import { Route as BusactivityImport } from './routes/bus_activity'
import { Route as BusaccountImport } from './routes/bus_account'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as BusopportunityIdImport } from './routes/bus_opportunity.$id'
import { Route as BuscontactIdImport } from './routes/bus_contact.$id'
import { Route as BusactivityIdImport } from './routes/bus_activity.$id'
import { Route as BusaccountIdImport } from './routes/bus_account.$id'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminWorkflowsImport } from './routes/admin/workflows'
import { Route as AdminRulesImport } from './routes/admin/rules'
import { Route as AdminFieldsImport } from './routes/admin/fields'
import { Route as AdminTablesTableNameImport } from './routes/admin/tables.$tableName'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BusopportunityRoute = BusopportunityImport.update({
  id: '/bus_opportunity',
  path: '/bus_opportunity',
  getParentRoute: () => rootRoute,
} as any)

const BuscontactRoute = BuscontactImport.update({
  id: '/bus_contact',
  path: '/bus_contact',
  getParentRoute: () => rootRoute,
} as any)

const BusactivityRoute = BusactivityImport.update({
  id: '/bus_activity',
  path: '/bus_activity',
  getParentRoute: () => rootRoute,
} as any)

const BusaccountRoute = BusaccountImport.update({
  id: '/bus_account',
  path: '/bus_account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const BusopportunityIdRoute = BusopportunityIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusopportunityRoute,
} as any)

const BuscontactIdRoute = BuscontactIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuscontactRoute,
} as any)

const BusactivityIdRoute = BusactivityIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusactivityRoute,
} as any)

const BusaccountIdRoute = BusaccountIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusaccountRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminWorkflowsRoute = AdminWorkflowsImport.update({
  id: '/admin/workflows',
  path: '/admin/workflows',
  getParentRoute: () => rootRoute,
} as any)

const AdminRulesRoute = AdminRulesImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRoute,
} as any)

const AdminFieldsRoute = AdminFieldsImport.update({
  id: '/admin/fields',
  path: '/admin/fields',
  getParentRoute: () => rootRoute,
} as any)

const AdminTablesTableNameRoute = AdminTablesTableNameImport.update({
  id: '/admin/tables/$tableName',
  path: '/admin/tables/$tableName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_account': {
      id: '/bus_account'
      path: '/bus_account'
      fullPath: '/bus_account'
      preLoaderRoute: typeof BusaccountImport
      parentRoute: typeof rootRoute
    }
    '/bus_activity': {
      id: '/bus_activity'
      path: '/bus_activity'
      fullPath: '/bus_activity'
      preLoaderRoute: typeof BusactivityImport
      parentRoute: typeof rootRoute
    }
    '/bus_contact': {
      id: '/bus_contact'
      path: '/bus_contact'
      fullPath: '/bus_contact'
      preLoaderRoute: typeof BuscontactImport
      parentRoute: typeof rootRoute
    }
    '/bus_opportunity': {
      id: '/bus_opportunity'
      path: '/bus_opportunity'
      fullPath: '/bus_opportunity'
      preLoaderRoute: typeof BusopportunityImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsImport
      parentRoute: typeof rootRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesImport
      parentRoute: typeof rootRoute
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/bus_account/$id': {
      id: '/bus_account/$id'
      path: '/$id'
      fullPath: '/bus_account/$id'
      preLoaderRoute: typeof BusaccountIdImport
      parentRoute: typeof BusaccountImport
    }
    '/bus_activity/$id': {
      id: '/bus_activity/$id'
      path: '/$id'
      fullPath: '/bus_activity/$id'
      preLoaderRoute: typeof BusactivityIdImport
      parentRoute: typeof BusactivityImport
    }
    '/bus_contact/$id': {
      id: '/bus_contact/$id'
      path: '/$id'
      fullPath: '/bus_contact/$id'
      preLoaderRoute: typeof BuscontactIdImport
      parentRoute: typeof BuscontactImport
    }
    '/bus_opportunity/$id': {
      id: '/bus_opportunity/$id'
      path: '/$id'
      fullPath: '/bus_opportunity/$id'
      preLoaderRoute: typeof BusopportunityIdImport
      parentRoute: typeof BusopportunityImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tables/$tableName': {
      id: '/admin/tables/$tableName'
      path: '/admin/tables/$tableName'
      fullPath: '/admin/tables/$tableName'
      preLoaderRoute: typeof AdminTablesTableNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface BusaccountRouteChildren {
  BusaccountIdRoute: typeof BusaccountIdRoute
}

const BusaccountRouteChildren: BusaccountRouteChildren = {
  BusaccountIdRoute: BusaccountIdRoute,
}

const BusaccountRouteWithChildren = BusaccountRoute._addFileChildren(
  BusaccountRouteChildren,
)

interface BusactivityRouteChildren {
  BusactivityIdRoute: typeof BusactivityIdRoute
}

const BusactivityRouteChildren: BusactivityRouteChildren = {
  BusactivityIdRoute: BusactivityIdRoute,
}

const BusactivityRouteWithChildren = BusactivityRoute._addFileChildren(
  BusactivityRouteChildren,
)

interface BuscontactRouteChildren {
  BuscontactIdRoute: typeof BuscontactIdRoute
}

const BuscontactRouteChildren: BuscontactRouteChildren = {
  BuscontactIdRoute: BuscontactIdRoute,
}

const BuscontactRouteWithChildren = BuscontactRoute._addFileChildren(
  BuscontactRouteChildren,
)

interface BusopportunityRouteChildren {
  BusopportunityIdRoute: typeof BusopportunityIdRoute
}

const BusopportunityRouteChildren: BusopportunityRouteChildren = {
  BusopportunityIdRoute: BusopportunityIdRoute,
}

const BusopportunityRouteWithChildren = BusopportunityRoute._addFileChildren(
  BusopportunityRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus_account': typeof BusaccountRouteWithChildren
  '/bus_activity': typeof BusactivityRouteWithChildren
  '/bus_contact': typeof BuscontactRouteWithChildren
  '/bus_opportunity': typeof BusopportunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_account/$id': typeof BusaccountIdRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_opportunity/$id': typeof BusopportunityIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tables/$tableName': typeof AdminTablesTableNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus_account': typeof BusaccountRouteWithChildren
  '/bus_activity': typeof BusactivityRouteWithChildren
  '/bus_contact': typeof BuscontactRouteWithChildren
  '/bus_opportunity': typeof BusopportunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_account/$id': typeof BusaccountIdRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_opportunity/$id': typeof BusopportunityIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tables/$tableName': typeof AdminTablesTableNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bus_account': typeof BusaccountRouteWithChildren
  '/bus_activity': typeof BusactivityRouteWithChildren
  '/bus_contact': typeof BuscontactRouteWithChildren
  '/bus_opportunity': typeof BusopportunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_account/$id': typeof BusaccountIdRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_opportunity/$id': typeof BusopportunityIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tables/$tableName': typeof AdminTablesTableNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus_account'
    | '/bus_activity'
    | '/bus_contact'
    | '/bus_opportunity'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_account/$id'
    | '/bus_activity/$id'
    | '/bus_contact/$id'
    | '/bus_opportunity/$id'
    | '/admin'
    | '/admin/tables/$tableName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus_account'
    | '/bus_activity'
    | '/bus_contact'
    | '/bus_opportunity'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_account/$id'
    | '/bus_activity/$id'
    | '/bus_contact/$id'
    | '/bus_opportunity/$id'
    | '/admin'
    | '/admin/tables/$tableName'
  id:
    | '__root__'
    | '/'
    | '/bus_account'
    | '/bus_activity'
    | '/bus_contact'
    | '/bus_opportunity'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_account/$id'
    | '/bus_activity/$id'
    | '/bus_contact/$id'
    | '/bus_opportunity/$id'
    | '/admin/'
    | '/admin/tables/$tableName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusaccountRoute: typeof BusaccountRouteWithChildren
  BusactivityRoute: typeof BusactivityRouteWithChildren
  BuscontactRoute: typeof BuscontactRouteWithChildren
  BusopportunityRoute: typeof BusopportunityRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AdminFieldsRoute: typeof AdminFieldsRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTablesTableNameRoute: typeof AdminTablesTableNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusaccountRoute: BusaccountRouteWithChildren,
  BusactivityRoute: BusactivityRouteWithChildren,
  BuscontactRoute: BuscontactRouteWithChildren,
  BusopportunityRoute: BusopportunityRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AdminFieldsRoute: AdminFieldsRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTablesTableNameRoute: AdminTablesTableNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bus_account",
        "/bus_activity",
        "/bus_contact",
        "/bus_opportunity",
        "/dashboard",
        "/admin/fields",
        "/admin/rules",
        "/admin/workflows",
        "/auth/login",
        "/auth/signup",
        "/admin/",
        "/admin/tables/$tableName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bus_account": {
      "filePath": "bus_account.tsx",
      "children": [
        "/bus_account/$id"
      ]
    },
    "/bus_activity": {
      "filePath": "bus_activity.tsx",
      "children": [
        "/bus_activity/$id"
      ]
    },
    "/bus_contact": {
      "filePath": "bus_contact.tsx",
      "children": [
        "/bus_contact/$id"
      ]
    },
    "/bus_opportunity": {
      "filePath": "bus_opportunity.tsx",
      "children": [
        "/bus_opportunity/$id"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/admin/fields": {
      "filePath": "admin/fields.tsx"
    },
    "/admin/rules": {
      "filePath": "admin/rules.tsx"
    },
    "/admin/workflows": {
      "filePath": "admin/workflows.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/bus_account/$id": {
      "filePath": "bus_account.$id.tsx",
      "parent": "/bus_account"
    },
    "/bus_activity/$id": {
      "filePath": "bus_activity.$id.tsx",
      "parent": "/bus_activity"
    },
    "/bus_contact/$id": {
      "filePath": "bus_contact.$id.tsx",
      "parent": "/bus_contact"
    },
    "/bus_opportunity/$id": {
      "filePath": "bus_opportunity.$id.tsx",
      "parent": "/bus_opportunity"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/admin/tables/$tableName": {
      "filePath": "admin/tables.$tableName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
