/**
 * Test Setup for my-app Frontend
 * Generated by APPWITHAI
 *
 * Provides test utilities and mocks for React/TanStack Start testing
 */

import React from 'react';
import { vi } from 'vitest';
import { render, RenderOptions } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '@testing-library/jest-dom';

// Mock auth context - Sidebar and other components use useAuth
vi.mock('../src/contexts/auth-context', () => ({
  useAuth: () => ({
    user: { id: 'test-user', email: 'test@example.com', name: 'Test User', role: 'admin' },
    isLoading: false,
    isAuthenticated: true,
    isAdmin: () => true,
    hasRole: (_role: string) => true,
    hasPermission: (_perm: string) => true,
    signIn: vi.fn(),
    signOut: vi.fn(),
  }),
  AuthProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock translations - DynamicTable and other components use useTranslations
vi.mock('../src/lib/translations', () => ({
  useTranslations: () => ({
    t: (key: string) => key,
    locale: 'en',
  }),
  TranslationProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

// Mock @tanstack/react-router
vi.mock('@tanstack/react-router', async () => {
  const actual = await vi.importActual('@tanstack/react-router');
  return {
    ...actual,
    useNavigate: () => vi.fn(),
    useLocation: () => ({ pathname: '/', search: '', hash: '', state: null, key: '' }),
    useSearch: () => ({}),
    Link: ({ children, to, ...props }: { children: React.ReactNode; to: string; [key: string]: unknown }) =>
      React.createElement('a', { href: to, ...props }, children),
  };
});

// Create a test query client
export function createTestQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: 0,
        staleTime: 0,
      },
      mutations: {
        retry: false,
      },
    },
  });
}

// Custom render function with providers
interface CustomRenderOptions extends Omit<RenderOptions, 'wrapper'> {
  queryClient?: QueryClient;
}

export function renderWithProviders(
  ui: React.ReactElement,
  options: CustomRenderOptions = {}
) {
  const { queryClient = createTestQueryClient(), ...renderOptions } = options;

  function Wrapper({ children }: { children: React.ReactNode }) {
    return (
      <QueryClientProvider client={queryClient}>
        {children}
      </QueryClientProvider>
    );
  }

  return {
    ...render(ui, { wrapper: Wrapper, ...renderOptions }),
    queryClient,
  };
}

// Re-export everything from testing-library
export * from '@testing-library/react';
export { renderWithProviders as render };

/**
 * Mock API responses
 */
export const mockApiResponses = {
  user: {
    list: [
      {
        id: 'test-id-1',
        email: 'Test Email 1',
        first_name: 'Test First Name 1',
        last_name: 'Test Last Name 1',
        role: 'Test Role 1',
        job_title: 'Test Job Title 1',
        phone: 'Test Phone 1',
        team_id: 'Test Team Id 1',
        quota_annual: 10.99,
        is_active: true,
        last_login: '2024-01-15T10:00:00Z',
      },
      {
        id: 'test-id-2',
        email: 'Test Email 2',
        first_name: 'Test First Name 2',
        last_name: 'Test Last Name 2',
        role: 'Test Role 2',
        job_title: 'Test Job Title 2',
        phone: 'Test Phone 2',
        team_id: 'Test Team Id 2',
        quota_annual: 20.99,
        is_active: false,
        last_login: '2024-01-16T10:00:00Z',
      },
    ],
    single: {
      id: 'test-id-1',
      email: 'Test Email',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      role: 'Test Role',
      job_title: 'Test Job Title',
      phone: 'Test Phone',
      team_id: 'Test Team Id',
      quota_annual: 10.99,
      is_active: true,
      last_login: '2024-01-15T10:00:00Z',
    },
  },
  team: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        manager_id: 'Test Manager Id 1',
        region: 'Test Region 1',
        quota_annual: 10.99,
        is_active: true,
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        manager_id: 'Test Manager Id 2',
        region: 'Test Region 2',
        quota_annual: 20.99,
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      manager_id: 'Test Manager Id',
      region: 'Test Region',
      quota_annual: 10.99,
      is_active: true,
    },
  },
  territory: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        region: 'Test Region 1',
        country_code: 'Test Country Code 1',
        manager_id: 'Test Manager Id 1',
        employee_count_floor: 1,
        employee_count_ceiling: 1,
        is_active: true,
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        region: 'Test Region 2',
        country_code: 'Test Country Code 2',
        manager_id: 'Test Manager Id 2',
        employee_count_floor: 2,
        employee_count_ceiling: 2,
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      region: 'Test Region',
      country_code: 'Test Country Code',
      manager_id: 'Test Manager Id',
      employee_count_floor: 1,
      employee_count_ceiling: 1,
      is_active: true,
    },
  },
  account: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        account_number: 'Test Account Number 1',
        account_type: 'Test Account Type 1',
        tier: 'Test Tier 1',
        industry: 'Test Industry 1',
        website: 'Test Website 1',
        phone: 'Test Phone 1',
        billing_street: 'Test Billing Street 1',
        billing_city: 'Test Billing City 1',
        billing_postal_code: 'Test Billing Postal Code 1',
        billing_country: 'Test Billing Country 1',
        employee_count: 1,
        annual_revenue: 10.99,
        health_score: 1,
        territory_id: 'Test Territory Id 1',
        sla_policy_id: 'Test Sla Policy Id 1',
        status: 'Test Status 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        account_number: 'Test Account Number 2',
        account_type: 'Test Account Type 2',
        tier: 'Test Tier 2',
        industry: 'Test Industry 2',
        website: 'Test Website 2',
        phone: 'Test Phone 2',
        billing_street: 'Test Billing Street 2',
        billing_city: 'Test Billing City 2',
        billing_postal_code: 'Test Billing Postal Code 2',
        billing_country: 'Test Billing Country 2',
        employee_count: 2,
        annual_revenue: 20.99,
        health_score: 2,
        territory_id: 'Test Territory Id 2',
        sla_policy_id: 'Test Sla Policy Id 2',
        status: 'Test Status 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      account_number: 'Test Account Number',
      account_type: 'Test Account Type',
      tier: 'Test Tier',
      industry: 'Test Industry',
      website: 'Test Website',
      phone: 'Test Phone',
      billing_street: 'Test Billing Street',
      billing_city: 'Test Billing City',
      billing_postal_code: 'Test Billing Postal Code',
      billing_country: 'Test Billing Country',
      employee_count: 1,
      annual_revenue: 10.99,
      health_score: 1,
      territory_id: 'Test Territory Id',
      sla_policy_id: 'Test Sla Policy Id',
      status: 'Test Status',
      owner_id: 'Test Owner Id',
    },
  },
  contact: {
    list: [
      {
        id: 'test-id-1',
        account_id: 'Test Account Id 1',
        first_name: 'Test First Name 1',
        last_name: 'Test Last Name 1',
        email: 'Test Email 1',
        phone: 'Test Phone 1',
        mobile: 'Test Mobile 1',
        job_title: 'Test Job Title 1',
        department: 'Test Department 1',
        lead_source: 'Test Lead Source 1',
        is_primary: true,
        email_opt_out: true,
        do_not_call: true,
        status: 'Test Status 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        account_id: 'Test Account Id 2',
        first_name: 'Test First Name 2',
        last_name: 'Test Last Name 2',
        email: 'Test Email 2',
        phone: 'Test Phone 2',
        mobile: 'Test Mobile 2',
        job_title: 'Test Job Title 2',
        department: 'Test Department 2',
        lead_source: 'Test Lead Source 2',
        is_primary: false,
        email_opt_out: false,
        do_not_call: false,
        status: 'Test Status 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      account_id: 'Test Account Id',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      email: 'Test Email',
      phone: 'Test Phone',
      mobile: 'Test Mobile',
      job_title: 'Test Job Title',
      department: 'Test Department',
      lead_source: 'Test Lead Source',
      is_primary: true,
      email_opt_out: true,
      do_not_call: true,
      status: 'Test Status',
      owner_id: 'Test Owner Id',
    },
  },
  lead: {
    list: [
      {
        id: 'test-id-1',
        first_name: 'Test First Name 1',
        last_name: 'Test Last Name 1',
        company_name: 'Test Company Name 1',
        email: 'Test Email 1',
        phone: 'Test Phone 1',
        job_title: 'Test Job Title 1',
        industry: 'Test Industry 1',
        employee_count: 1,
        annual_revenue: 10.99,
        lead_source: 'Test Lead Source 1',
        rating: 'Test Rating 1',
        score: 1,
        campaign_id: 'Test Campaign Id 1',
        status: 'Test Status 1',
        owner_id: 'Test Owner Id 1',
        converted_at: '2024-01-15T10:00:00Z',
        disqualification_reason: 'Test Disqualification Reason 1',
      },
      {
        id: 'test-id-2',
        first_name: 'Test First Name 2',
        last_name: 'Test Last Name 2',
        company_name: 'Test Company Name 2',
        email: 'Test Email 2',
        phone: 'Test Phone 2',
        job_title: 'Test Job Title 2',
        industry: 'Test Industry 2',
        employee_count: 2,
        annual_revenue: 20.99,
        lead_source: 'Test Lead Source 2',
        rating: 'Test Rating 2',
        score: 2,
        campaign_id: 'Test Campaign Id 2',
        status: 'Test Status 2',
        owner_id: 'Test Owner Id 2',
        converted_at: '2024-01-16T10:00:00Z',
        disqualification_reason: 'Test Disqualification Reason 2',
      },
    ],
    single: {
      id: 'test-id-1',
      first_name: 'Test First Name',
      last_name: 'Test Last Name',
      company_name: 'Test Company Name',
      email: 'Test Email',
      phone: 'Test Phone',
      job_title: 'Test Job Title',
      industry: 'Test Industry',
      employee_count: 1,
      annual_revenue: 10.99,
      lead_source: 'Test Lead Source',
      rating: 'Test Rating',
      score: 1,
      campaign_id: 'Test Campaign Id',
      status: 'Test Status',
      owner_id: 'Test Owner Id',
      converted_at: '2024-01-15T10:00:00Z',
      disqualification_reason: 'Test Disqualification Reason',
    },
  },
  campaign: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        campaign_type: 'Test Campaign Type 1',
        status: 'Test Status 1',
        start_date: '2024-01-15',
        end_date: '2024-01-15',
        budgeted_cost: 10.99,
        actual_cost: 10.99,
        expected_revenue: 10.99,
        expected_response_count: 1,
        target_audience: 'Test Target Audience 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        campaign_type: 'Test Campaign Type 2',
        status: 'Test Status 2',
        start_date: '2024-01-16',
        end_date: '2024-01-16',
        budgeted_cost: 20.99,
        actual_cost: 20.99,
        expected_revenue: 20.99,
        expected_response_count: 2,
        target_audience: 'Test Target Audience 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      campaign_type: 'Test Campaign Type',
      status: 'Test Status',
      start_date: '2024-01-15',
      end_date: '2024-01-15',
      budgeted_cost: 10.99,
      actual_cost: 10.99,
      expected_revenue: 10.99,
      expected_response_count: 1,
      target_audience: 'Test Target Audience',
      owner_id: 'Test Owner Id',
    },
  },
  campaignMember: {
    list: [
      {
        id: 'test-id-1',
        campaign_id: 'Test Campaign Id 1',
        lead_id: 'Test Lead Id 1',
        contact_id: 'Test Contact Id 1',
        member_status: 'Test Member Status 1',
        responded_at: '2024-01-15T10:00:00Z',
        has_responded: true,
      },
      {
        id: 'test-id-2',
        campaign_id: 'Test Campaign Id 2',
        lead_id: 'Test Lead Id 2',
        contact_id: 'Test Contact Id 2',
        member_status: 'Test Member Status 2',
        responded_at: '2024-01-16T10:00:00Z',
        has_responded: false,
      },
    ],
    single: {
      id: 'test-id-1',
      campaign_id: 'Test Campaign Id',
      lead_id: 'Test Lead Id',
      contact_id: 'Test Contact Id',
      member_status: 'Test Member Status',
      responded_at: '2024-01-15T10:00:00Z',
      has_responded: true,
    },
  },
  opportunity: {
    list: [
      {
        id: 'test-id-1',
        account_id: 'Test Account Id 1',
        contact_id: 'Test Contact Id 1',
        campaign_id: 'Test Campaign Id 1',
        name: 'Test Name 1',
        description: 'Test text content',
        amount: 10.99,
        currency_code: 'Test Currency Code 1',
        stage: 'Test Stage 1',
        probability: 1,
        forecast_category: 'Test Forecast Category 1',
        expected_close_date: '2024-01-15',
        actual_close_date: '2024-01-15',
        lead_source: 'Test Lead Source 1',
        next_step: 'Test Next Step 1',
        loss_reason: 'Test Loss Reason 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        account_id: 'Test Account Id 2',
        contact_id: 'Test Contact Id 2',
        campaign_id: 'Test Campaign Id 2',
        name: 'Test Name 2',
        description: 'Test text content 2',
        amount: 20.99,
        currency_code: 'Test Currency Code 2',
        stage: 'Test Stage 2',
        probability: 2,
        forecast_category: 'Test Forecast Category 2',
        expected_close_date: '2024-01-16',
        actual_close_date: '2024-01-16',
        lead_source: 'Test Lead Source 2',
        next_step: 'Test Next Step 2',
        loss_reason: 'Test Loss Reason 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      account_id: 'Test Account Id',
      contact_id: 'Test Contact Id',
      campaign_id: 'Test Campaign Id',
      name: 'Test Name',
      description: 'Test text content',
      amount: 10.99,
      currency_code: 'Test Currency Code',
      stage: 'Test Stage',
      probability: 1,
      forecast_category: 'Test Forecast Category',
      expected_close_date: '2024-01-15',
      actual_close_date: '2024-01-15',
      lead_source: 'Test Lead Source',
      next_step: 'Test Next Step',
      loss_reason: 'Test Loss Reason',
      owner_id: 'Test Owner Id',
    },
  },
  opportunityLineItem: {
    list: [
      {
        id: 'test-id-1',
        opportunity_id: 'Test Opportunity Id 1',
        product_id: 'Test Product Id 1',
        quantity: 10.99,
        unit_price: 10.99,
        discount_percent: 10.99,
        line_total: 10.99,
        line_description: 'Test Line Description 1',
      },
      {
        id: 'test-id-2',
        opportunity_id: 'Test Opportunity Id 2',
        product_id: 'Test Product Id 2',
        quantity: 20.99,
        unit_price: 20.99,
        discount_percent: 20.99,
        line_total: 20.99,
        line_description: 'Test Line Description 2',
      },
    ],
    single: {
      id: 'test-id-1',
      opportunity_id: 'Test Opportunity Id',
      product_id: 'Test Product Id',
      quantity: 10.99,
      unit_price: 10.99,
      discount_percent: 10.99,
      line_total: 10.99,
      line_description: 'Test Line Description',
    },
  },
  product: {
    list: [
      {
        id: 'test-id-1',
        product_code: 'Test Product Code 1',
        name: 'Test Name 1',
        description: 'Test text content',
        family: 'Test Family 1',
        list_price: 10.99,
        unit_cost: 10.99,
        billing_frequency: 'Test Billing Frequency 1',
        is_active: true,
      },
      {
        id: 'test-id-2',
        product_code: 'Test Product Code 2',
        name: 'Test Name 2',
        description: 'Test text content 2',
        family: 'Test Family 2',
        list_price: 20.99,
        unit_cost: 20.99,
        billing_frequency: 'Test Billing Frequency 2',
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      product_code: 'Test Product Code',
      name: 'Test Name',
      description: 'Test text content',
      family: 'Test Family',
      list_price: 10.99,
      unit_cost: 10.99,
      billing_frequency: 'Test Billing Frequency',
      is_active: true,
    },
  },
  quote: {
    list: [
      {
        id: 'test-id-1',
        quote_number: 'Test Quote Number 1',
        opportunity_id: 'Test Opportunity Id 1',
        account_id: 'Test Account Id 1',
        name: 'Test Name 1',
        status: 'Test Status 1',
        version_number: 1,
        valid_until: '2024-01-15',
        subtotal: 10.99,
        discount_percent: 10.99,
        discount_amount: 10.99,
        tax_amount: 10.99,
        grand_total: 10.99,
        approved_by_id: 'Test Approved By Id 1',
        approved_at: '2024-01-15T10:00:00Z',
        approval_notes: 'Test text content',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        quote_number: 'Test Quote Number 2',
        opportunity_id: 'Test Opportunity Id 2',
        account_id: 'Test Account Id 2',
        name: 'Test Name 2',
        status: 'Test Status 2',
        version_number: 2,
        valid_until: '2024-01-16',
        subtotal: 20.99,
        discount_percent: 20.99,
        discount_amount: 20.99,
        tax_amount: 20.99,
        grand_total: 20.99,
        approved_by_id: 'Test Approved By Id 2',
        approved_at: '2024-01-16T10:00:00Z',
        approval_notes: 'Test text content 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      quote_number: 'Test Quote Number',
      opportunity_id: 'Test Opportunity Id',
      account_id: 'Test Account Id',
      name: 'Test Name',
      status: 'Test Status',
      version_number: 1,
      valid_until: '2024-01-15',
      subtotal: 10.99,
      discount_percent: 10.99,
      discount_amount: 10.99,
      tax_amount: 10.99,
      grand_total: 10.99,
      approved_by_id: 'Test Approved By Id',
      approved_at: '2024-01-15T10:00:00Z',
      approval_notes: 'Test text content',
      owner_id: 'Test Owner Id',
    },
  },
  quoteLineItem: {
    list: [
      {
        id: 'test-id-1',
        quote_id: 'Test Quote Id 1',
        product_id: 'Test Product Id 1',
        quantity: 10.99,
        unit_price: 10.99,
        discount_percent: 10.99,
        line_total: 10.99,
        sort_order: 1,
      },
      {
        id: 'test-id-2',
        quote_id: 'Test Quote Id 2',
        product_id: 'Test Product Id 2',
        quantity: 20.99,
        unit_price: 20.99,
        discount_percent: 20.99,
        line_total: 20.99,
        sort_order: 2,
      },
    ],
    single: {
      id: 'test-id-1',
      quote_id: 'Test Quote Id',
      product_id: 'Test Product Id',
      quantity: 10.99,
      unit_price: 10.99,
      discount_percent: 10.99,
      line_total: 10.99,
      sort_order: 1,
    },
  },
  contract: {
    list: [
      {
        id: 'test-id-1',
        contract_number: 'Test Contract Number 1',
        account_id: 'Test Account Id 1',
        quote_id: 'Test Quote Id 1',
        status: 'Test Status 1',
        start_date: '2024-01-15',
        end_date: '2024-01-15',
        term_months: 1,
        annual_value: 10.99,
        auto_renew: true,
        renewal_notice_days: 1,
        signed_by_id: 'Test Signed By Id 1',
        signed_at: '2024-01-15T10:00:00Z',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        contract_number: 'Test Contract Number 2',
        account_id: 'Test Account Id 2',
        quote_id: 'Test Quote Id 2',
        status: 'Test Status 2',
        start_date: '2024-01-16',
        end_date: '2024-01-16',
        term_months: 2,
        annual_value: 20.99,
        auto_renew: false,
        renewal_notice_days: 2,
        signed_by_id: 'Test Signed By Id 2',
        signed_at: '2024-01-16T10:00:00Z',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      contract_number: 'Test Contract Number',
      account_id: 'Test Account Id',
      quote_id: 'Test Quote Id',
      status: 'Test Status',
      start_date: '2024-01-15',
      end_date: '2024-01-15',
      term_months: 1,
      annual_value: 10.99,
      auto_renew: true,
      renewal_notice_days: 1,
      signed_by_id: 'Test Signed By Id',
      signed_at: '2024-01-15T10:00:00Z',
      owner_id: 'Test Owner Id',
    },
  },
  supportCase: {
    list: [
      {
        id: 'test-id-1',
        case_number: 'Test Case Number 1',
        account_id: 'Test Account Id 1',
        contact_id: 'Test Contact Id 1',
        sla_policy_id: 'Test Sla Policy Id 1',
        subject: 'Test Subject 1',
        description: 'Test text content',
        case_type: 'Test Case Type 1',
        priority: 'Test Priority 1',
        origin: 'Test Origin 1',
        status: 'Test Status 1',
        first_response_due_at: '2024-01-15T10:00:00Z',
        first_response_at: '2024-01-15T10:00:00Z',
        resolution_due_at: '2024-01-15T10:00:00Z',
        resolved_at: '2024-01-15T10:00:00Z',
        is_sla_breached: true,
        resolution_notes: 'Test text content',
        satisfaction_score: 1,
        escalated_by_id: 'Test Escalated By Id 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        case_number: 'Test Case Number 2',
        account_id: 'Test Account Id 2',
        contact_id: 'Test Contact Id 2',
        sla_policy_id: 'Test Sla Policy Id 2',
        subject: 'Test Subject 2',
        description: 'Test text content 2',
        case_type: 'Test Case Type 2',
        priority: 'Test Priority 2',
        origin: 'Test Origin 2',
        status: 'Test Status 2',
        first_response_due_at: '2024-01-16T10:00:00Z',
        first_response_at: '2024-01-16T10:00:00Z',
        resolution_due_at: '2024-01-16T10:00:00Z',
        resolved_at: '2024-01-16T10:00:00Z',
        is_sla_breached: false,
        resolution_notes: 'Test text content 2',
        satisfaction_score: 2,
        escalated_by_id: 'Test Escalated By Id 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      case_number: 'Test Case Number',
      account_id: 'Test Account Id',
      contact_id: 'Test Contact Id',
      sla_policy_id: 'Test Sla Policy Id',
      subject: 'Test Subject',
      description: 'Test text content',
      case_type: 'Test Case Type',
      priority: 'Test Priority',
      origin: 'Test Origin',
      status: 'Test Status',
      first_response_due_at: '2024-01-15T10:00:00Z',
      first_response_at: '2024-01-15T10:00:00Z',
      resolution_due_at: '2024-01-15T10:00:00Z',
      resolved_at: '2024-01-15T10:00:00Z',
      is_sla_breached: true,
      resolution_notes: 'Test text content',
      satisfaction_score: 1,
      escalated_by_id: 'Test Escalated By Id',
      owner_id: 'Test Owner Id',
    },
  },
  slaPolicy: {
    list: [
      {
        id: 'test-id-1',
        name: 'Test Name 1',
        tier: 'Test Tier 1',
        first_response_minutes: 1,
        resolution_hours: 1,
        business_hours_only: true,
        is_active: true,
      },
      {
        id: 'test-id-2',
        name: 'Test Name 2',
        tier: 'Test Tier 2',
        first_response_minutes: 2,
        resolution_hours: 2,
        business_hours_only: false,
        is_active: false,
      },
    ],
    single: {
      id: 'test-id-1',
      name: 'Test Name',
      tier: 'Test Tier',
      first_response_minutes: 1,
      resolution_hours: 1,
      business_hours_only: true,
      is_active: true,
    },
  },
  activity: {
    list: [
      {
        id: 'test-id-1',
        activity_type: 'Test Activity Type 1',
        subject: 'Test Subject 1',
        description: 'Test text content',
        status: 'Test Status 1',
        priority: 'Test Priority 1',
        due_at: '2024-01-15T10:00:00Z',
        completed_at: '2024-01-15T10:00:00Z',
        duration_minutes: 1,
        account_id: 'Test Account Id 1',
        contact_id: 'Test Contact Id 1',
        lead_id: 'Test Lead Id 1',
        opportunity_id: 'Test Opportunity Id 1',
        support_case_id: 'Test Support Case Id 1',
        contract_id: 'Test Contract Id 1',
        owner_id: 'Test Owner Id 1',
      },
      {
        id: 'test-id-2',
        activity_type: 'Test Activity Type 2',
        subject: 'Test Subject 2',
        description: 'Test text content 2',
        status: 'Test Status 2',
        priority: 'Test Priority 2',
        due_at: '2024-01-16T10:00:00Z',
        completed_at: '2024-01-16T10:00:00Z',
        duration_minutes: 2,
        account_id: 'Test Account Id 2',
        contact_id: 'Test Contact Id 2',
        lead_id: 'Test Lead Id 2',
        opportunity_id: 'Test Opportunity Id 2',
        support_case_id: 'Test Support Case Id 2',
        contract_id: 'Test Contract Id 2',
        owner_id: 'Test Owner Id 2',
      },
    ],
    single: {
      id: 'test-id-1',
      activity_type: 'Test Activity Type',
      subject: 'Test Subject',
      description: 'Test text content',
      status: 'Test Status',
      priority: 'Test Priority',
      due_at: '2024-01-15T10:00:00Z',
      completed_at: '2024-01-15T10:00:00Z',
      duration_minutes: 1,
      account_id: 'Test Account Id',
      contact_id: 'Test Contact Id',
      lead_id: 'Test Lead Id',
      opportunity_id: 'Test Opportunity Id',
      support_case_id: 'Test Support Case Id',
      contract_id: 'Test Contract Id',
      owner_id: 'Test Owner Id',
    },
  },
};

/**
 * Create mock fetch function
 */
export function createMockFetch(responses: Record<string, unknown>) {
  return vi.fn((input: RequestInfo | URL, options?: RequestInit) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    const path = url.replace(/^https?:\/\/[^/]+/, '');

    // Find matching response
    for (const [pattern, response] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        return Promise.resolve({
          ok: true,
          status: 200,
          json: () => Promise.resolve(response),
          text: () => Promise.resolve(JSON.stringify(response)),
          headers: new Headers({ 'content-type': 'application/json' }),
        } as Response);
      }
    }

    // Default 404 response
    return Promise.resolve({
      ok: false,
      status: 404,
      json: () => Promise.resolve({ message: 'Not found' }),
      text: () => Promise.resolve('{"message": "Not found"}'),
      headers: new Headers({ 'content-type': 'application/json' }),
    } as Response);
  }) as unknown as typeof fetch;
}

/**
 * Wait for async operations
 */
export async function waitFor(callback: () => boolean | void, timeout = 5000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    try {
      const result = callback();
      if (result !== false) return;
    } catch {
      // Continue waiting
    }
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  throw new Error('Timeout waiting for condition');
}
