#!/usr/bin/env bun
/**
 * Bundle the generator for the browser.
 *
 * Output goes to `html/assets/erdwithai-wasm.js`, which the upload page imports
 * as a module. Everything the bundle needs is already pure — the runtime was
 * inlined by build-wasm-runtime.ts, and parse-model.ts touches no filesystem —
 * so this is a plain esbuild pass with no shims and no polyfills.
 *
 *   bun run build:wasm-browser
 *   bun run build:wasm-browser --check    # fail if the checked-in bundle is stale
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const ENTRY = join(ROOT, "packages/generator/src/browser/index.ts");
const TARGET = join(ROOT, "html/assets/erdwithai-wasm.js");

/**
 * Stubs for the Node builtins the parser still names.
 *
 * `language-maps.ts` imports `node:fs` to find the language definition on disk.
 * The browser entry injects that definition directly, so the file lookup never
 * runs — but the import still has to resolve for the bundle to build. These
 * stubs make the lookup fail the way a missing file would, which is the branch
 * the loader already handles.
 */
const nodeStubs: Record<string, string> = {
  "node:fs":
    "export const existsSync = () => false;\n" +
    "export const readFileSync = () => { throw new Error('no filesystem in the browser'); };\n" +
    "export default { existsSync, readFileSync };",
  "node:path":
    "const dirname = (p) => String(p).replace(/\\/[^/]*$/, '') || '/';\n" +
    "const join = (...parts) => parts.filter(Boolean).join('/').replace(/\\/+/g, '/');\n" +
    "export { dirname, join };\nexport default { dirname, join };",
  "node:url":
    "export const fileURLToPath = (url) => String(url).replace(/^file:\\/\\//, '');\n" +
    "export default { fileURLToPath };",
};

const stubPlugin: import("bun").BunPlugin = {
  name: "node-builtin-stubs",
  setup(build) {
    build.onResolve({ filter: /^node:(fs|path|url)$/ }, (args) => ({
      path: args.path,
      namespace: "node-stub",
    }));
    build.onLoad({ filter: /.*/, namespace: "node-stub" }, (args) => ({
      contents: nodeStubs[args.path] ?? "export default {};",
      loader: "js",
    }));
  },
};

const result = await Bun.build({
  plugins: [stubPlugin],
  entrypoints: [ENTRY],
  target: "browser",
  format: "esm",
  minify: false,
  // Readable rather than minified on purpose: this file is served from a
  // documentation folder, and someone who wants to know what the page does to
  // their model should be able to read it. It compresses to a fraction of its
  // size over the wire anyway.
  define: { "process.env.NODE_ENV": '"production"' },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const artifact = result.outputs[0];
if (!artifact) {
  console.error("esbuild produced no output");
  process.exit(1);
}

const banner = `// Generated by scripts/build-wasm-browser.ts — do not edit.
// Source: packages/generator/src/browser/index.ts
// This is the same parser, rule compiler and application assembler that
// \`erdwithai-wasm generate\` runs; the page imports it so a model generates the
// same application whether it was submitted from a terminal or from a browser.
`;

const bundle = banner + (await artifact.text());

if (process.argv.includes("--check")) {
  const existing = await readFile(TARGET, "utf-8").catch(() => "");
  if (existing !== bundle) {
    console.error("html/assets/erdwithai-wasm.js is out of date.\nRun: bun run build:wasm-browser");
    process.exit(1);
  }
  const worker = await readFile(join(ROOT, "html/wasm-app/sw.js"), "utf-8").catch(() => "");
  const source = await readFile(join(ROOT, "packages/generator/templates/wasm/sw.js"), "utf-8");
  if (worker !== source) {
    console.error("html/wasm-app/sw.js is out of date.\nRun: bun run build:wasm-browser");
    process.exit(1);
  }
  console.log("✓ html/assets/erdwithai-wasm.js and html/wasm-app/sw.js are up to date");
} else {
  await mkdir(join(ROOT, "html/assets"), { recursive: true });
  await writeFile(TARGET, bundle, "utf-8");

  // The page's Service Worker has to be a real file at a real path — a worker
  // script is the one request a Service Worker does not get to answer, so it
  // cannot be served out of the bundle it serves everything else from.
  await mkdir(join(ROOT, "html/wasm-app"), { recursive: true });
  await writeFile(
    join(ROOT, "html/wasm-app/sw.js"),
    await readFile(join(ROOT, "packages/generator/templates/wasm/sw.js"), "utf-8"),
    "utf-8"
  );
  console.log(
    `✓ bundled the generator to ${relative(ROOT, TARGET)} (${(bundle.length / 1024).toFixed(0)}KB)`
  );
}
