#!/usr/bin/env bun
/**
 * Inline the browser stack's runtime into a TypeScript module.
 *
 * The generator has to be able to produce an application from inside a browser
 * tab — that is the whole point of the upload page in `html/` — and a browser
 * has no `fs.readFile` to load `templates/wasm/**` with. So the runtime is
 * checked in twice: once as real files that can be edited, linted and diffed,
 * and once as the generated module this script writes.
 *
 * The alternative was to keep the runtime as string literals in TypeScript, and
 * it is worse in every direction: no syntax highlighting, no `node --check`, and
 * every backtick in the generated JavaScript needing an escape.
 *
 *   bun run build:wasm-runtime      # regenerate after editing templates/wasm
 *   bun run build:wasm-runtime --check   # fail if the checked-in copy is stale
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { VERBATIM_NOTICE } from "./lib/build-env.ts";

const ROOT = resolve(import.meta.dir, "..");
/**
 * Two inlined sets, for two reasons.
 *
 * `wasm/` is the offline runtime; `wasm-overlay/` is what turns an application
 * generated by the ordinary pipeline into one that runs without a database
 * server. Both have to be readable by a generator that may be running inside a
 * browser tab, where there is no `fs.readFile`.
 */
const BUNDLES = [
  {
    source: join(ROOT, "packages/generator/templates/wasm"),
    target: join(ROOT, "packages/generator/src/generators/wasm/runtime-assets.generated.ts"),
    constant: "RUNTIME_ASSETS",
    bytes: "RUNTIME_BYTES",
    what: "the browser stack's runtime",
    origin: "packages/generator/templates/wasm/**",
  },
  {
    source: join(ROOT, "packages/generator/templates/wasm-overlay"),
    target: join(ROOT, "packages/generator/src/generators/wasm/overlay-assets.generated.ts"),
    constant: "OVERLAY_ASSETS",
    bytes: "OVERLAY_BYTES",
    what: "the WASM overlay",
    origin: "packages/generator/templates/wasm-overlay/**",
  },
] as const;

async function* walk(directory: string): AsyncGenerator<string> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) yield* walk(path);
    else yield path;
  }
}

type Bundle = (typeof BUNDLES)[number];

async function build(bundle: Bundle): Promise<{ source: string; count: number }> {
  const files: Array<[string, string]> = [];
  for await (const path of walk(bundle.source)) {
    files.push([
      relative(bundle.source, path).split("\\").join("/"),
      await readFile(path, "utf-8"),
    ]);
  }
  files.sort(([a], [b]) => a.localeCompare(b));

  const entries = files
    .map(([name, content]) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`)
    .join("\n");

  const source = `/**
 * Generated by scripts/build-wasm-runtime.ts — do not edit.
 *
 * The source of truth is ${bundle.origin}. Run
 * \`bun run build:wasm-runtime\` after changing it; CI runs the same script
 * with --check and fails if this file is stale.
 */

/** Every file of ${bundle.what}, keyed by its path in the application. */
export const ${bundle.constant}: Readonly<Record<string, string>> = Object.freeze({
${entries}
});

/** Bytes shipped into each generated application. */
export const ${bundle.bytes} = ${files.reduce((total, [, content]) => total + Buffer.byteLength(content), 0)};
`;

  return { source, count: files.length };
}

let stale = false;

for (const bundle of BUNDLES) {
  const { source: generated, count } = await build(bundle);

  if (process.argv.includes("--check")) {
    const existing = await readFile(bundle.target, "utf-8").catch(() => "");
    if (existing !== generated) {
      console.error(`${relative(ROOT, bundle.target)} is out of date.`);
      stale = true;
      continue;
    }
    console.log(`\u2713 ${relative(ROOT, bundle.target)} is up to date`);
  } else {
    await writeFile(bundle.target, generated, "utf-8");
    console.log(`\u2713 inlined ${count} files into ${relative(ROOT, bundle.target)}`);
  }
}

if (stale) {
  console.error("\nRun: bun run build:wasm-runtime");
  console.error(VERBATIM_NOTICE);
  process.exit(1);
}
