#!/usr/bin/env bun
/**
 * Bundle the model reader for the viewer page.
 *
 * `website/viewers/` is the visual half of what a language model writes: a
 * reader following `website/llmtext/llmdetailed.txt` builds a `.eml.mmd` a phase
 * at a time, and the viewers show the entities, the state machines and the
 * decision flows as they appear. Everything drawn there has to be the
 * generator's own reading of the document, or the picture is of an application
 * nobody will get — so `website/viewers/eml-model.js` is this repository's
 * parser, its rule and workflow compilers, its RBAC derivation and its checker,
 * bundled for a tab. The rendering beside it is hand-written and dependency
 * free; the reading is never re-implemented.
 *
 * It is a separate bundle from `html/assets/appwithai-wasm.js` on purpose:
 * that one carries the whole application assembler and the inlined browser
 * runtime, which a reader who wants a diagram should not have to download.
 *
 *   bun run build:viewers
 *   bun run build:viewers --check    # fail if the checked-in bundle is stale
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { bundlerEnvNotice } from "./lib/build-env.ts";

// Pinned to the repository root, not the working directory: Bun labels each
// bundled module with its path relative to the cwd, so a build from anywhere
// else produces different bytes — `--check` passing locally and failing on CI.
const ROOT = resolve(import.meta.dir, "..");
process.chdir(ROOT);

const ENTRY = "packages/generator/src/browser/viewers.ts";
const TARGET = "website/viewers/eml-model.js";

/**
 * Stubs for the Node builtins the reader still names.
 *
 * `language-maps.ts` and `language/index.ts` resolve the language definition
 * off disk, and `checker.ts` names the file operations its CLI half uses. The
 * entry injects the definition and calls only the pure functions, so none of
 * these ever run — the imports simply have to resolve. Identical to the stubs
 * `build-language-tools.ts` and `build-wasm-browser.ts` install, and for the
 * same reason: they fail rather than pretend.
 */
const nodeStubs: Record<string, string> = {
  "node:fs":
    "const missing = () => { throw new Error('no filesystem in the browser'); };\n" +
    "export const existsSync = () => false;\n" +
    "export const readFileSync = missing;\n" +
    "export const writeFileSync = missing;\n" +
    "export const readdirSync = missing;\n" +
    "export const statSync = missing;\n" +
    "export default { existsSync, readFileSync, writeFileSync, readdirSync, statSync };",
  "node:path":
    "const dirname = (p) => String(p).replace(/\\/[^/]*$/, '') || '/';\n" +
    "const basename = (p) => String(p).split('/').pop() || '';\n" +
    "const join = (...parts) => parts.filter(Boolean).join('/').replace(/\\/+/g, '/');\n" +
    "const resolve = (...parts) => join(...parts);\n" +
    "const relative = (_from, to) => String(to);\n" +
    "export { dirname, basename, join, resolve, relative };\n" +
    "export default { dirname, basename, join, resolve, relative };",
  "node:url":
    "export const fileURLToPath = (url) => String(url).replace(/^file:\\/\\//, '');\n" +
    "export default { fileURLToPath };",
};

const stubPlugin: import("bun").BunPlugin = {
  name: "node-builtin-stubs",
  setup(build) {
    build.onResolve({ filter: /^node:(fs|path|url)$/ }, (args) => ({
      path: args.path,
      namespace: "node-stub",
    }));
    build.onLoad({ filter: /.*/, namespace: "node-stub" }, (args) => ({
      contents: nodeStubs[args.path] ?? "export default {};",
      loader: "js",
    }));
  },
};

const result = await Bun.build({
  plugins: [stubPlugin],
  entrypoints: [join(ROOT, ENTRY)],
  target: "browser",
  format: "esm",
  minify: false,
  // Readable rather than minified, as with every other bundle this repository
  // publishes: it is served from a documentation site, and someone who wants to
  // know what the page does to their model should be able to read it.
  define: {
    "process.env.NODE_ENV": '"production"',
    "process.env.EML_DEBUG": "undefined",
    "import.meta.main": "false",
  },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const artifact = result.outputs[0];
if (!artifact) {
  console.error(`no output for ${ENTRY}`);
  process.exit(1);
}

const banner =
  "// Generated by scripts/build-viewers.ts — do not edit.\n" +
  `// Source: ${ENTRY}\n` +
  "// The parser, rule and workflow compilers, RBAC derivation and checker this\n" +
  "// repository generates applications with, bundled for the viewer page:\n" +
  "//   import { inspectModel } from './eml-model.js';\n" +
  "//   const { model, report } = inspectModel(source);\n" +
  "// Anything the viewers draw is read by this, never by a second parser.\n";

const bundle = banner + (await artifact.text());

if (process.argv.includes("--check")) {
  const existing = await readFile(join(ROOT, TARGET), "utf-8").catch(() => "");
  if (existing !== bundle) {
    console.error(`${TARGET} is out of date.\nRun: bun run build:viewers`);
    console.error(bundlerEnvNotice(ROOT));
    process.exit(1);
  }
  console.log(`✓ ${TARGET} is up to date`);
} else {
  await writeFile(join(ROOT, TARGET), bundle, "utf-8");
  console.log(
    `✓ bundled the model reader to ${relative(ROOT, join(ROOT, TARGET))} (${(bundle.length / 1024).toFixed(0)}KB)`
  );
}
