#!/usr/bin/env bun
/**
 * Inline the browser stack's runtime into a TypeScript module.
 *
 * The generator has to be able to produce an application from inside a browser
 * tab — that is the whole point of the upload page in `html/` — and a browser
 * has no `fs.readFile` to load `templates/wasm/**` with. So the runtime is
 * checked in twice: once as real files that can be edited, linted and diffed,
 * and once as the generated module this script writes.
 *
 * The alternative was to keep the runtime as string literals in TypeScript, and
 * it is worse in every direction: no syntax highlighting, no `node --check`, and
 * every backtick in the generated JavaScript needing an escape.
 *
 *   bun run build:wasm-runtime      # regenerate after editing templates/wasm
 *   bun run build:wasm-runtime --check   # fail if the checked-in copy is stale
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const SOURCE = join(ROOT, "packages/generator/templates/wasm");
const TARGET = join(ROOT, "packages/generator/src/generators/wasm/runtime-assets.generated.ts");

async function* walk(directory: string): AsyncGenerator<string> {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) yield* walk(path);
    else yield path;
  }
}

async function build(): Promise<{ source: string; count: number }> {
  const files: Array<[string, string]> = [];
  for await (const path of walk(SOURCE)) {
    files.push([relative(SOURCE, path).split("\\").join("/"), await readFile(path, "utf-8")]);
  }
  files.sort(([a], [b]) => a.localeCompare(b));

  const entries = files
    .map(([name, content]) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`)
    .join("\n");

  const source = `/**
 * Generated by scripts/build-wasm-runtime.ts — do not edit.
 *
 * The source of truth is packages/generator/templates/wasm/**. Run
 * \`bun run build:wasm-runtime\` after changing it; CI runs the same script
 * with --check and fails if this file is stale.
 */

/** Every file of the browser stack's runtime, keyed by its path in the app. */
export const RUNTIME_ASSETS: Readonly<Record<string, string>> = Object.freeze({
${entries}
});

/** Bytes of runtime shipped into each generated application. */
export const RUNTIME_BYTES = ${files.reduce((total, [, content]) => total + Buffer.byteLength(content), 0)};
`;

  return { source, count: files.length };
}

const { source: generated, count } = await build();

if (process.argv.includes("--check")) {
  const existing = await readFile(TARGET, "utf-8").catch(() => "");
  if (existing !== generated) {
    console.error("runtime-assets.generated.ts is out of date.\nRun: bun run build:wasm-runtime");
    process.exit(1);
  }
  console.log("✓ runtime-assets.generated.ts is up to date");
} else {
  await writeFile(TARGET, generated, "utf-8");
  console.log(`✓ inlined ${count} runtime files into ${relative(ROOT, TARGET)}`);
}
