/* eslint-disable */
// This file was automatically generated by TanStack Router.
// It will be regenerated when you run 'vinxi dev' or 'vinxi build'.
// Do not edit this file manually.

import { createRootRoute } from '@tanstack/react-router'

export interface FileRoutesByPath {}
export interface FileRoutesByFullPath {}

export const routeTree = {} as any
