/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as BususerImport } from './routes/bus_user'
import { Route as BusteamImport } from './routes/bus_team'
import { Route as BustaskImport } from './routes/bus_task'
import { Route as BusquoteitemImport } from './routes/bus_quote_item'
import { Route as BusquoteImport } from './routes/bus_quote'
import { Route as BusproductImport } from './routes/bus_product'
import { Route as BuspipelineImport } from './routes/bus_pipeline'
import { Route as BusnoteImport } from './routes/bus_note'
import { Route as BusemailtemplateImport } from './routes/bus_email_template'
import { Route as BusemailmessageImport } from './routes/bus_email_message'
import { Route as BusdealstageImport } from './routes/bus_deal_stage'
import { Route as BusdealImport } from './routes/bus_deal'
import { Route as BuscontactImport } from './routes/bus_contact'
import { Route as BuscompanyImport } from './routes/bus_company'
import { Route as BusactivityImport } from './routes/bus_activity'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as BususerIdImport } from './routes/bus_user.$id'
import { Route as BusteamIdImport } from './routes/bus_team.$id'
import { Route as BustaskIdImport } from './routes/bus_task.$id'
import { Route as BusquoteitemIdImport } from './routes/bus_quote_item.$id'
import { Route as BusquoteIdImport } from './routes/bus_quote.$id'
import { Route as BusproductIdImport } from './routes/bus_product.$id'
import { Route as BuspipelineIdImport } from './routes/bus_pipeline.$id'
import { Route as BusnoteIdImport } from './routes/bus_note.$id'
import { Route as BusemailtemplateIdImport } from './routes/bus_email_template.$id'
import { Route as BusemailmessageIdImport } from './routes/bus_email_message.$id'
import { Route as BusdealstageIdImport } from './routes/bus_deal_stage.$id'
import { Route as BusdealIdImport } from './routes/bus_deal.$id'
import { Route as BuscontactIdImport } from './routes/bus_contact.$id'
import { Route as BuscompanyIdImport } from './routes/bus_company.$id'
import { Route as BusactivityIdImport } from './routes/bus_activity.$id'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AdminWorkflowsImport } from './routes/admin/workflows'
import { Route as AdminRulesImport } from './routes/admin/rules'
import { Route as AdminFieldsImport } from './routes/admin/fields'
import { Route as AdminTablesTableNameImport } from './routes/admin/tables.$tableName'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const BususerRoute = BususerImport.update({
  id: '/bus_user',
  path: '/bus_user',
  getParentRoute: () => rootRoute,
} as any)

const BusteamRoute = BusteamImport.update({
  id: '/bus_team',
  path: '/bus_team',
  getParentRoute: () => rootRoute,
} as any)

const BustaskRoute = BustaskImport.update({
  id: '/bus_task',
  path: '/bus_task',
  getParentRoute: () => rootRoute,
} as any)

const BusquoteitemRoute = BusquoteitemImport.update({
  id: '/bus_quote_item',
  path: '/bus_quote_item',
  getParentRoute: () => rootRoute,
} as any)

const BusquoteRoute = BusquoteImport.update({
  id: '/bus_quote',
  path: '/bus_quote',
  getParentRoute: () => rootRoute,
} as any)

const BusproductRoute = BusproductImport.update({
  id: '/bus_product',
  path: '/bus_product',
  getParentRoute: () => rootRoute,
} as any)

const BuspipelineRoute = BuspipelineImport.update({
  id: '/bus_pipeline',
  path: '/bus_pipeline',
  getParentRoute: () => rootRoute,
} as any)

const BusnoteRoute = BusnoteImport.update({
  id: '/bus_note',
  path: '/bus_note',
  getParentRoute: () => rootRoute,
} as any)

const BusemailtemplateRoute = BusemailtemplateImport.update({
  id: '/bus_email_template',
  path: '/bus_email_template',
  getParentRoute: () => rootRoute,
} as any)

const BusemailmessageRoute = BusemailmessageImport.update({
  id: '/bus_email_message',
  path: '/bus_email_message',
  getParentRoute: () => rootRoute,
} as any)

const BusdealstageRoute = BusdealstageImport.update({
  id: '/bus_deal_stage',
  path: '/bus_deal_stage',
  getParentRoute: () => rootRoute,
} as any)

const BusdealRoute = BusdealImport.update({
  id: '/bus_deal',
  path: '/bus_deal',
  getParentRoute: () => rootRoute,
} as any)

const BuscontactRoute = BuscontactImport.update({
  id: '/bus_contact',
  path: '/bus_contact',
  getParentRoute: () => rootRoute,
} as any)

const BuscompanyRoute = BuscompanyImport.update({
  id: '/bus_company',
  path: '/bus_company',
  getParentRoute: () => rootRoute,
} as any)

const BusactivityRoute = BusactivityImport.update({
  id: '/bus_activity',
  path: '/bus_activity',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const BususerIdRoute = BususerIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BususerRoute,
} as any)

const BusteamIdRoute = BusteamIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusteamRoute,
} as any)

const BustaskIdRoute = BustaskIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BustaskRoute,
} as any)

const BusquoteitemIdRoute = BusquoteitemIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusquoteitemRoute,
} as any)

const BusquoteIdRoute = BusquoteIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusquoteRoute,
} as any)

const BusproductIdRoute = BusproductIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusproductRoute,
} as any)

const BuspipelineIdRoute = BuspipelineIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuspipelineRoute,
} as any)

const BusnoteIdRoute = BusnoteIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusnoteRoute,
} as any)

const BusemailtemplateIdRoute = BusemailtemplateIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusemailtemplateRoute,
} as any)

const BusemailmessageIdRoute = BusemailmessageIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusemailmessageRoute,
} as any)

const BusdealstageIdRoute = BusdealstageIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusdealstageRoute,
} as any)

const BusdealIdRoute = BusdealIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusdealRoute,
} as any)

const BuscontactIdRoute = BuscontactIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuscontactRoute,
} as any)

const BuscompanyIdRoute = BuscompanyIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BuscompanyRoute,
} as any)

const BusactivityIdRoute = BusactivityIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusactivityRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminWorkflowsRoute = AdminWorkflowsImport.update({
  id: '/admin/workflows',
  path: '/admin/workflows',
  getParentRoute: () => rootRoute,
} as any)

const AdminRulesRoute = AdminRulesImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRoute,
} as any)

const AdminFieldsRoute = AdminFieldsImport.update({
  id: '/admin/fields',
  path: '/admin/fields',
  getParentRoute: () => rootRoute,
} as any)

const AdminTablesTableNameRoute = AdminTablesTableNameImport.update({
  id: '/admin/tables/$tableName',
  path: '/admin/tables/$tableName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bus_activity': {
      id: '/bus_activity'
      path: '/bus_activity'
      fullPath: '/bus_activity'
      preLoaderRoute: typeof BusactivityImport
      parentRoute: typeof rootRoute
    }
    '/bus_company': {
      id: '/bus_company'
      path: '/bus_company'
      fullPath: '/bus_company'
      preLoaderRoute: typeof BuscompanyImport
      parentRoute: typeof rootRoute
    }
    '/bus_contact': {
      id: '/bus_contact'
      path: '/bus_contact'
      fullPath: '/bus_contact'
      preLoaderRoute: typeof BuscontactImport
      parentRoute: typeof rootRoute
    }
    '/bus_deal': {
      id: '/bus_deal'
      path: '/bus_deal'
      fullPath: '/bus_deal'
      preLoaderRoute: typeof BusdealImport
      parentRoute: typeof rootRoute
    }
    '/bus_deal_stage': {
      id: '/bus_deal_stage'
      path: '/bus_deal_stage'
      fullPath: '/bus_deal_stage'
      preLoaderRoute: typeof BusdealstageImport
      parentRoute: typeof rootRoute
    }
    '/bus_email_message': {
      id: '/bus_email_message'
      path: '/bus_email_message'
      fullPath: '/bus_email_message'
      preLoaderRoute: typeof BusemailmessageImport
      parentRoute: typeof rootRoute
    }
    '/bus_email_template': {
      id: '/bus_email_template'
      path: '/bus_email_template'
      fullPath: '/bus_email_template'
      preLoaderRoute: typeof BusemailtemplateImport
      parentRoute: typeof rootRoute
    }
    '/bus_note': {
      id: '/bus_note'
      path: '/bus_note'
      fullPath: '/bus_note'
      preLoaderRoute: typeof BusnoteImport
      parentRoute: typeof rootRoute
    }
    '/bus_pipeline': {
      id: '/bus_pipeline'
      path: '/bus_pipeline'
      fullPath: '/bus_pipeline'
      preLoaderRoute: typeof BuspipelineImport
      parentRoute: typeof rootRoute
    }
    '/bus_product': {
      id: '/bus_product'
      path: '/bus_product'
      fullPath: '/bus_product'
      preLoaderRoute: typeof BusproductImport
      parentRoute: typeof rootRoute
    }
    '/bus_quote': {
      id: '/bus_quote'
      path: '/bus_quote'
      fullPath: '/bus_quote'
      preLoaderRoute: typeof BusquoteImport
      parentRoute: typeof rootRoute
    }
    '/bus_quote_item': {
      id: '/bus_quote_item'
      path: '/bus_quote_item'
      fullPath: '/bus_quote_item'
      preLoaderRoute: typeof BusquoteitemImport
      parentRoute: typeof rootRoute
    }
    '/bus_task': {
      id: '/bus_task'
      path: '/bus_task'
      fullPath: '/bus_task'
      preLoaderRoute: typeof BustaskImport
      parentRoute: typeof rootRoute
    }
    '/bus_team': {
      id: '/bus_team'
      path: '/bus_team'
      fullPath: '/bus_team'
      preLoaderRoute: typeof BusteamImport
      parentRoute: typeof rootRoute
    }
    '/bus_user': {
      id: '/bus_user'
      path: '/bus_user'
      fullPath: '/bus_user'
      preLoaderRoute: typeof BususerImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsImport
      parentRoute: typeof rootRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesImport
      parentRoute: typeof rootRoute
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/bus_activity/$id': {
      id: '/bus_activity/$id'
      path: '/$id'
      fullPath: '/bus_activity/$id'
      preLoaderRoute: typeof BusactivityIdImport
      parentRoute: typeof BusactivityImport
    }
    '/bus_company/$id': {
      id: '/bus_company/$id'
      path: '/$id'
      fullPath: '/bus_company/$id'
      preLoaderRoute: typeof BuscompanyIdImport
      parentRoute: typeof BuscompanyImport
    }
    '/bus_contact/$id': {
      id: '/bus_contact/$id'
      path: '/$id'
      fullPath: '/bus_contact/$id'
      preLoaderRoute: typeof BuscontactIdImport
      parentRoute: typeof BuscontactImport
    }
    '/bus_deal/$id': {
      id: '/bus_deal/$id'
      path: '/$id'
      fullPath: '/bus_deal/$id'
      preLoaderRoute: typeof BusdealIdImport
      parentRoute: typeof BusdealImport
    }
    '/bus_deal_stage/$id': {
      id: '/bus_deal_stage/$id'
      path: '/$id'
      fullPath: '/bus_deal_stage/$id'
      preLoaderRoute: typeof BusdealstageIdImport
      parentRoute: typeof BusdealstageImport
    }
    '/bus_email_message/$id': {
      id: '/bus_email_message/$id'
      path: '/$id'
      fullPath: '/bus_email_message/$id'
      preLoaderRoute: typeof BusemailmessageIdImport
      parentRoute: typeof BusemailmessageImport
    }
    '/bus_email_template/$id': {
      id: '/bus_email_template/$id'
      path: '/$id'
      fullPath: '/bus_email_template/$id'
      preLoaderRoute: typeof BusemailtemplateIdImport
      parentRoute: typeof BusemailtemplateImport
    }
    '/bus_note/$id': {
      id: '/bus_note/$id'
      path: '/$id'
      fullPath: '/bus_note/$id'
      preLoaderRoute: typeof BusnoteIdImport
      parentRoute: typeof BusnoteImport
    }
    '/bus_pipeline/$id': {
      id: '/bus_pipeline/$id'
      path: '/$id'
      fullPath: '/bus_pipeline/$id'
      preLoaderRoute: typeof BuspipelineIdImport
      parentRoute: typeof BuspipelineImport
    }
    '/bus_product/$id': {
      id: '/bus_product/$id'
      path: '/$id'
      fullPath: '/bus_product/$id'
      preLoaderRoute: typeof BusproductIdImport
      parentRoute: typeof BusproductImport
    }
    '/bus_quote/$id': {
      id: '/bus_quote/$id'
      path: '/$id'
      fullPath: '/bus_quote/$id'
      preLoaderRoute: typeof BusquoteIdImport
      parentRoute: typeof BusquoteImport
    }
    '/bus_quote_item/$id': {
      id: '/bus_quote_item/$id'
      path: '/$id'
      fullPath: '/bus_quote_item/$id'
      preLoaderRoute: typeof BusquoteitemIdImport
      parentRoute: typeof BusquoteitemImport
    }
    '/bus_task/$id': {
      id: '/bus_task/$id'
      path: '/$id'
      fullPath: '/bus_task/$id'
      preLoaderRoute: typeof BustaskIdImport
      parentRoute: typeof BustaskImport
    }
    '/bus_team/$id': {
      id: '/bus_team/$id'
      path: '/$id'
      fullPath: '/bus_team/$id'
      preLoaderRoute: typeof BusteamIdImport
      parentRoute: typeof BusteamImport
    }
    '/bus_user/$id': {
      id: '/bus_user/$id'
      path: '/$id'
      fullPath: '/bus_user/$id'
      preLoaderRoute: typeof BususerIdImport
      parentRoute: typeof BususerImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/tables/$tableName': {
      id: '/admin/tables/$tableName'
      path: '/admin/tables/$tableName'
      fullPath: '/admin/tables/$tableName'
      preLoaderRoute: typeof AdminTablesTableNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface BusactivityRouteChildren {
  BusactivityIdRoute: typeof BusactivityIdRoute
}

const BusactivityRouteChildren: BusactivityRouteChildren = {
  BusactivityIdRoute: BusactivityIdRoute,
}

const BusactivityRouteWithChildren = BusactivityRoute._addFileChildren(
  BusactivityRouteChildren,
)

interface BuscompanyRouteChildren {
  BuscompanyIdRoute: typeof BuscompanyIdRoute
}

const BuscompanyRouteChildren: BuscompanyRouteChildren = {
  BuscompanyIdRoute: BuscompanyIdRoute,
}

const BuscompanyRouteWithChildren = BuscompanyRoute._addFileChildren(
  BuscompanyRouteChildren,
)

interface BuscontactRouteChildren {
  BuscontactIdRoute: typeof BuscontactIdRoute
}

const BuscontactRouteChildren: BuscontactRouteChildren = {
  BuscontactIdRoute: BuscontactIdRoute,
}

const BuscontactRouteWithChildren = BuscontactRoute._addFileChildren(
  BuscontactRouteChildren,
)

interface BusdealRouteChildren {
  BusdealIdRoute: typeof BusdealIdRoute
}

const BusdealRouteChildren: BusdealRouteChildren = {
  BusdealIdRoute: BusdealIdRoute,
}

const BusdealRouteWithChildren =
  BusdealRoute._addFileChildren(BusdealRouteChildren)

interface BusdealstageRouteChildren {
  BusdealstageIdRoute: typeof BusdealstageIdRoute
}

const BusdealstageRouteChildren: BusdealstageRouteChildren = {
  BusdealstageIdRoute: BusdealstageIdRoute,
}

const BusdealstageRouteWithChildren = BusdealstageRoute._addFileChildren(
  BusdealstageRouteChildren,
)

interface BusemailmessageRouteChildren {
  BusemailmessageIdRoute: typeof BusemailmessageIdRoute
}

const BusemailmessageRouteChildren: BusemailmessageRouteChildren = {
  BusemailmessageIdRoute: BusemailmessageIdRoute,
}

const BusemailmessageRouteWithChildren = BusemailmessageRoute._addFileChildren(
  BusemailmessageRouteChildren,
)

interface BusemailtemplateRouteChildren {
  BusemailtemplateIdRoute: typeof BusemailtemplateIdRoute
}

const BusemailtemplateRouteChildren: BusemailtemplateRouteChildren = {
  BusemailtemplateIdRoute: BusemailtemplateIdRoute,
}

const BusemailtemplateRouteWithChildren =
  BusemailtemplateRoute._addFileChildren(BusemailtemplateRouteChildren)

interface BusnoteRouteChildren {
  BusnoteIdRoute: typeof BusnoteIdRoute
}

const BusnoteRouteChildren: BusnoteRouteChildren = {
  BusnoteIdRoute: BusnoteIdRoute,
}

const BusnoteRouteWithChildren =
  BusnoteRoute._addFileChildren(BusnoteRouteChildren)

interface BuspipelineRouteChildren {
  BuspipelineIdRoute: typeof BuspipelineIdRoute
}

const BuspipelineRouteChildren: BuspipelineRouteChildren = {
  BuspipelineIdRoute: BuspipelineIdRoute,
}

const BuspipelineRouteWithChildren = BuspipelineRoute._addFileChildren(
  BuspipelineRouteChildren,
)

interface BusproductRouteChildren {
  BusproductIdRoute: typeof BusproductIdRoute
}

const BusproductRouteChildren: BusproductRouteChildren = {
  BusproductIdRoute: BusproductIdRoute,
}

const BusproductRouteWithChildren = BusproductRoute._addFileChildren(
  BusproductRouteChildren,
)

interface BusquoteRouteChildren {
  BusquoteIdRoute: typeof BusquoteIdRoute
}

const BusquoteRouteChildren: BusquoteRouteChildren = {
  BusquoteIdRoute: BusquoteIdRoute,
}

const BusquoteRouteWithChildren = BusquoteRoute._addFileChildren(
  BusquoteRouteChildren,
)

interface BusquoteitemRouteChildren {
  BusquoteitemIdRoute: typeof BusquoteitemIdRoute
}

const BusquoteitemRouteChildren: BusquoteitemRouteChildren = {
  BusquoteitemIdRoute: BusquoteitemIdRoute,
}

const BusquoteitemRouteWithChildren = BusquoteitemRoute._addFileChildren(
  BusquoteitemRouteChildren,
)

interface BustaskRouteChildren {
  BustaskIdRoute: typeof BustaskIdRoute
}

const BustaskRouteChildren: BustaskRouteChildren = {
  BustaskIdRoute: BustaskIdRoute,
}

const BustaskRouteWithChildren =
  BustaskRoute._addFileChildren(BustaskRouteChildren)

interface BusteamRouteChildren {
  BusteamIdRoute: typeof BusteamIdRoute
}

const BusteamRouteChildren: BusteamRouteChildren = {
  BusteamIdRoute: BusteamIdRoute,
}

const BusteamRouteWithChildren =
  BusteamRoute._addFileChildren(BusteamRouteChildren)

interface BususerRouteChildren {
  BususerIdRoute: typeof BususerIdRoute
}

const BususerRouteChildren: BususerRouteChildren = {
  BususerIdRoute: BususerIdRoute,
}

const BususerRouteWithChildren =
  BususerRoute._addFileChildren(BususerRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus_activity': typeof BusactivityRouteWithChildren
  '/bus_company': typeof BuscompanyRouteWithChildren
  '/bus_contact': typeof BuscontactRouteWithChildren
  '/bus_deal': typeof BusdealRouteWithChildren
  '/bus_deal_stage': typeof BusdealstageRouteWithChildren
  '/bus_email_message': typeof BusemailmessageRouteWithChildren
  '/bus_email_template': typeof BusemailtemplateRouteWithChildren
  '/bus_note': typeof BusnoteRouteWithChildren
  '/bus_pipeline': typeof BuspipelineRouteWithChildren
  '/bus_product': typeof BusproductRouteWithChildren
  '/bus_quote': typeof BusquoteRouteWithChildren
  '/bus_quote_item': typeof BusquoteitemRouteWithChildren
  '/bus_task': typeof BustaskRouteWithChildren
  '/bus_team': typeof BusteamRouteWithChildren
  '/bus_user': typeof BususerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_company/$id': typeof BuscompanyIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_deal/$id': typeof BusdealIdRoute
  '/bus_deal_stage/$id': typeof BusdealstageIdRoute
  '/bus_email_message/$id': typeof BusemailmessageIdRoute
  '/bus_email_template/$id': typeof BusemailtemplateIdRoute
  '/bus_note/$id': typeof BusnoteIdRoute
  '/bus_pipeline/$id': typeof BuspipelineIdRoute
  '/bus_product/$id': typeof BusproductIdRoute
  '/bus_quote/$id': typeof BusquoteIdRoute
  '/bus_quote_item/$id': typeof BusquoteitemIdRoute
  '/bus_task/$id': typeof BustaskIdRoute
  '/bus_team/$id': typeof BusteamIdRoute
  '/bus_user/$id': typeof BususerIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tables/$tableName': typeof AdminTablesTableNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus_activity': typeof BusactivityRouteWithChildren
  '/bus_company': typeof BuscompanyRouteWithChildren
  '/bus_contact': typeof BuscontactRouteWithChildren
  '/bus_deal': typeof BusdealRouteWithChildren
  '/bus_deal_stage': typeof BusdealstageRouteWithChildren
  '/bus_email_message': typeof BusemailmessageRouteWithChildren
  '/bus_email_template': typeof BusemailtemplateRouteWithChildren
  '/bus_note': typeof BusnoteRouteWithChildren
  '/bus_pipeline': typeof BuspipelineRouteWithChildren
  '/bus_product': typeof BusproductRouteWithChildren
  '/bus_quote': typeof BusquoteRouteWithChildren
  '/bus_quote_item': typeof BusquoteitemRouteWithChildren
  '/bus_task': typeof BustaskRouteWithChildren
  '/bus_team': typeof BusteamRouteWithChildren
  '/bus_user': typeof BususerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_company/$id': typeof BuscompanyIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_deal/$id': typeof BusdealIdRoute
  '/bus_deal_stage/$id': typeof BusdealstageIdRoute
  '/bus_email_message/$id': typeof BusemailmessageIdRoute
  '/bus_email_template/$id': typeof BusemailtemplateIdRoute
  '/bus_note/$id': typeof BusnoteIdRoute
  '/bus_pipeline/$id': typeof BuspipelineIdRoute
  '/bus_product/$id': typeof BusproductIdRoute
  '/bus_quote/$id': typeof BusquoteIdRoute
  '/bus_quote_item/$id': typeof BusquoteitemIdRoute
  '/bus_task/$id': typeof BustaskIdRoute
  '/bus_team/$id': typeof BusteamIdRoute
  '/bus_user/$id': typeof BususerIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tables/$tableName': typeof AdminTablesTableNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bus_activity': typeof BusactivityRouteWithChildren
  '/bus_company': typeof BuscompanyRouteWithChildren
  '/bus_contact': typeof BuscontactRouteWithChildren
  '/bus_deal': typeof BusdealRouteWithChildren
  '/bus_deal_stage': typeof BusdealstageRouteWithChildren
  '/bus_email_message': typeof BusemailmessageRouteWithChildren
  '/bus_email_template': typeof BusemailtemplateRouteWithChildren
  '/bus_note': typeof BusnoteRouteWithChildren
  '/bus_pipeline': typeof BuspipelineRouteWithChildren
  '/bus_product': typeof BusproductRouteWithChildren
  '/bus_quote': typeof BusquoteRouteWithChildren
  '/bus_quote_item': typeof BusquoteitemRouteWithChildren
  '/bus_task': typeof BustaskRouteWithChildren
  '/bus_team': typeof BusteamRouteWithChildren
  '/bus_user': typeof BususerRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/admin/fields': typeof AdminFieldsRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/bus_activity/$id': typeof BusactivityIdRoute
  '/bus_company/$id': typeof BuscompanyIdRoute
  '/bus_contact/$id': typeof BuscontactIdRoute
  '/bus_deal/$id': typeof BusdealIdRoute
  '/bus_deal_stage/$id': typeof BusdealstageIdRoute
  '/bus_email_message/$id': typeof BusemailmessageIdRoute
  '/bus_email_template/$id': typeof BusemailtemplateIdRoute
  '/bus_note/$id': typeof BusnoteIdRoute
  '/bus_pipeline/$id': typeof BuspipelineIdRoute
  '/bus_product/$id': typeof BusproductIdRoute
  '/bus_quote/$id': typeof BusquoteIdRoute
  '/bus_quote_item/$id': typeof BusquoteitemIdRoute
  '/bus_task/$id': typeof BustaskIdRoute
  '/bus_team/$id': typeof BusteamIdRoute
  '/bus_user/$id': typeof BususerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tables/$tableName': typeof AdminTablesTableNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bus_activity'
    | '/bus_company'
    | '/bus_contact'
    | '/bus_deal'
    | '/bus_deal_stage'
    | '/bus_email_message'
    | '/bus_email_template'
    | '/bus_note'
    | '/bus_pipeline'
    | '/bus_product'
    | '/bus_quote'
    | '/bus_quote_item'
    | '/bus_task'
    | '/bus_team'
    | '/bus_user'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_activity/$id'
    | '/bus_company/$id'
    | '/bus_contact/$id'
    | '/bus_deal/$id'
    | '/bus_deal_stage/$id'
    | '/bus_email_message/$id'
    | '/bus_email_template/$id'
    | '/bus_note/$id'
    | '/bus_pipeline/$id'
    | '/bus_product/$id'
    | '/bus_quote/$id'
    | '/bus_quote_item/$id'
    | '/bus_task/$id'
    | '/bus_team/$id'
    | '/bus_user/$id'
    | '/admin'
    | '/admin/tables/$tableName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bus_activity'
    | '/bus_company'
    | '/bus_contact'
    | '/bus_deal'
    | '/bus_deal_stage'
    | '/bus_email_message'
    | '/bus_email_template'
    | '/bus_note'
    | '/bus_pipeline'
    | '/bus_product'
    | '/bus_quote'
    | '/bus_quote_item'
    | '/bus_task'
    | '/bus_team'
    | '/bus_user'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_activity/$id'
    | '/bus_company/$id'
    | '/bus_contact/$id'
    | '/bus_deal/$id'
    | '/bus_deal_stage/$id'
    | '/bus_email_message/$id'
    | '/bus_email_template/$id'
    | '/bus_note/$id'
    | '/bus_pipeline/$id'
    | '/bus_product/$id'
    | '/bus_quote/$id'
    | '/bus_quote_item/$id'
    | '/bus_task/$id'
    | '/bus_team/$id'
    | '/bus_user/$id'
    | '/admin'
    | '/admin/tables/$tableName'
  id:
    | '__root__'
    | '/'
    | '/bus_activity'
    | '/bus_company'
    | '/bus_contact'
    | '/bus_deal'
    | '/bus_deal_stage'
    | '/bus_email_message'
    | '/bus_email_template'
    | '/bus_note'
    | '/bus_pipeline'
    | '/bus_product'
    | '/bus_quote'
    | '/bus_quote_item'
    | '/bus_task'
    | '/bus_team'
    | '/bus_user'
    | '/dashboard'
    | '/admin/fields'
    | '/admin/rules'
    | '/admin/workflows'
    | '/auth/login'
    | '/auth/signup'
    | '/bus_activity/$id'
    | '/bus_company/$id'
    | '/bus_contact/$id'
    | '/bus_deal/$id'
    | '/bus_deal_stage/$id'
    | '/bus_email_message/$id'
    | '/bus_email_template/$id'
    | '/bus_note/$id'
    | '/bus_pipeline/$id'
    | '/bus_product/$id'
    | '/bus_quote/$id'
    | '/bus_quote_item/$id'
    | '/bus_task/$id'
    | '/bus_team/$id'
    | '/bus_user/$id'
    | '/admin/'
    | '/admin/tables/$tableName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusactivityRoute: typeof BusactivityRouteWithChildren
  BuscompanyRoute: typeof BuscompanyRouteWithChildren
  BuscontactRoute: typeof BuscontactRouteWithChildren
  BusdealRoute: typeof BusdealRouteWithChildren
  BusdealstageRoute: typeof BusdealstageRouteWithChildren
  BusemailmessageRoute: typeof BusemailmessageRouteWithChildren
  BusemailtemplateRoute: typeof BusemailtemplateRouteWithChildren
  BusnoteRoute: typeof BusnoteRouteWithChildren
  BuspipelineRoute: typeof BuspipelineRouteWithChildren
  BusproductRoute: typeof BusproductRouteWithChildren
  BusquoteRoute: typeof BusquoteRouteWithChildren
  BusquoteitemRoute: typeof BusquoteitemRouteWithChildren
  BustaskRoute: typeof BustaskRouteWithChildren
  BusteamRoute: typeof BusteamRouteWithChildren
  BususerRoute: typeof BususerRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  AdminFieldsRoute: typeof AdminFieldsRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTablesTableNameRoute: typeof AdminTablesTableNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusactivityRoute: BusactivityRouteWithChildren,
  BuscompanyRoute: BuscompanyRouteWithChildren,
  BuscontactRoute: BuscontactRouteWithChildren,
  BusdealRoute: BusdealRouteWithChildren,
  BusdealstageRoute: BusdealstageRouteWithChildren,
  BusemailmessageRoute: BusemailmessageRouteWithChildren,
  BusemailtemplateRoute: BusemailtemplateRouteWithChildren,
  BusnoteRoute: BusnoteRouteWithChildren,
  BuspipelineRoute: BuspipelineRouteWithChildren,
  BusproductRoute: BusproductRouteWithChildren,
  BusquoteRoute: BusquoteRouteWithChildren,
  BusquoteitemRoute: BusquoteitemRouteWithChildren,
  BustaskRoute: BustaskRouteWithChildren,
  BusteamRoute: BusteamRouteWithChildren,
  BususerRoute: BususerRouteWithChildren,
  DashboardRoute: DashboardRoute,
  AdminFieldsRoute: AdminFieldsRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTablesTableNameRoute: AdminTablesTableNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bus_activity",
        "/bus_company",
        "/bus_contact",
        "/bus_deal",
        "/bus_deal_stage",
        "/bus_email_message",
        "/bus_email_template",
        "/bus_note",
        "/bus_pipeline",
        "/bus_product",
        "/bus_quote",
        "/bus_quote_item",
        "/bus_task",
        "/bus_team",
        "/bus_user",
        "/dashboard",
        "/admin/fields",
        "/admin/rules",
        "/admin/workflows",
        "/auth/login",
        "/auth/signup",
        "/admin/",
        "/admin/tables/$tableName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bus_activity": {
      "filePath": "bus_activity.tsx",
      "children": [
        "/bus_activity/$id"
      ]
    },
    "/bus_company": {
      "filePath": "bus_company.tsx",
      "children": [
        "/bus_company/$id"
      ]
    },
    "/bus_contact": {
      "filePath": "bus_contact.tsx",
      "children": [
        "/bus_contact/$id"
      ]
    },
    "/bus_deal": {
      "filePath": "bus_deal.tsx",
      "children": [
        "/bus_deal/$id"
      ]
    },
    "/bus_deal_stage": {
      "filePath": "bus_deal_stage.tsx",
      "children": [
        "/bus_deal_stage/$id"
      ]
    },
    "/bus_email_message": {
      "filePath": "bus_email_message.tsx",
      "children": [
        "/bus_email_message/$id"
      ]
    },
    "/bus_email_template": {
      "filePath": "bus_email_template.tsx",
      "children": [
        "/bus_email_template/$id"
      ]
    },
    "/bus_note": {
      "filePath": "bus_note.tsx",
      "children": [
        "/bus_note/$id"
      ]
    },
    "/bus_pipeline": {
      "filePath": "bus_pipeline.tsx",
      "children": [
        "/bus_pipeline/$id"
      ]
    },
    "/bus_product": {
      "filePath": "bus_product.tsx",
      "children": [
        "/bus_product/$id"
      ]
    },
    "/bus_quote": {
      "filePath": "bus_quote.tsx",
      "children": [
        "/bus_quote/$id"
      ]
    },
    "/bus_quote_item": {
      "filePath": "bus_quote_item.tsx",
      "children": [
        "/bus_quote_item/$id"
      ]
    },
    "/bus_task": {
      "filePath": "bus_task.tsx",
      "children": [
        "/bus_task/$id"
      ]
    },
    "/bus_team": {
      "filePath": "bus_team.tsx",
      "children": [
        "/bus_team/$id"
      ]
    },
    "/bus_user": {
      "filePath": "bus_user.tsx",
      "children": [
        "/bus_user/$id"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/admin/fields": {
      "filePath": "admin/fields.tsx"
    },
    "/admin/rules": {
      "filePath": "admin/rules.tsx"
    },
    "/admin/workflows": {
      "filePath": "admin/workflows.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/bus_activity/$id": {
      "filePath": "bus_activity.$id.tsx",
      "parent": "/bus_activity"
    },
    "/bus_company/$id": {
      "filePath": "bus_company.$id.tsx",
      "parent": "/bus_company"
    },
    "/bus_contact/$id": {
      "filePath": "bus_contact.$id.tsx",
      "parent": "/bus_contact"
    },
    "/bus_deal/$id": {
      "filePath": "bus_deal.$id.tsx",
      "parent": "/bus_deal"
    },
    "/bus_deal_stage/$id": {
      "filePath": "bus_deal_stage.$id.tsx",
      "parent": "/bus_deal_stage"
    },
    "/bus_email_message/$id": {
      "filePath": "bus_email_message.$id.tsx",
      "parent": "/bus_email_message"
    },
    "/bus_email_template/$id": {
      "filePath": "bus_email_template.$id.tsx",
      "parent": "/bus_email_template"
    },
    "/bus_note/$id": {
      "filePath": "bus_note.$id.tsx",
      "parent": "/bus_note"
    },
    "/bus_pipeline/$id": {
      "filePath": "bus_pipeline.$id.tsx",
      "parent": "/bus_pipeline"
    },
    "/bus_product/$id": {
      "filePath": "bus_product.$id.tsx",
      "parent": "/bus_product"
    },
    "/bus_quote/$id": {
      "filePath": "bus_quote.$id.tsx",
      "parent": "/bus_quote"
    },
    "/bus_quote_item/$id": {
      "filePath": "bus_quote_item.$id.tsx",
      "parent": "/bus_quote_item"
    },
    "/bus_task/$id": {
      "filePath": "bus_task.$id.tsx",
      "parent": "/bus_task"
    },
    "/bus_team/$id": {
      "filePath": "bus_team.$id.tsx",
      "parent": "/bus_team"
    },
    "/bus_user/$id": {
      "filePath": "bus_user.$id.tsx",
      "parent": "/bus_user"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    },
    "/admin/tables/$tableName": {
      "filePath": "admin/tables.$tableName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
