/**
 * Test Setup for CRM App Backend
 * Generated by ERDwithAI
 *
 * Provides test utilities, fixtures, and database setup
 */

import { Test, TestingModule } from '@nestjs/testing';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { KYSELY_CONNECTION } from '../src/database/database.constants';
import { Kysely, MemoryDialect } from 'kysely';

// Use in-memory dialect for tests instead of SQLite
// This avoids native module loading issues in test environments

// Test database instance
let testDb: Kysely<any>;

// Test application instance
let testApp: NestFastifyApplication;

/**
 * Initialize test database connection
 */
export async function initTestDatabase(): Promise<Kysely<any>> {
  if (!testDb) {
    // Use in-memory dialect for tests (no native modules required)
    testDb = new Kysely({
      dialect: new MemoryDialect(),
    });
  }
  return testDb;
}

/**
 * Close test database connection
 */
export async function closeTestDatabase(): Promise<void> {
  if (testDb) {
    try {
      await testDb.destroy();
    } catch (_e) {
      // Already closed
    }
    testDb = undefined as any;
  }
}

/**
 * Create test application
 */
export async function createTestApp(module: any): Promise<NestFastifyApplication> {
  const builder = Test.createTestingModule({
    imports: [module],
  });

  // Override KYSELY_CONNECTION with the shared test database so the NestJS app
  // uses the same in-memory SQLite database as the test helpers.
  if (testDb) {
    builder.overrideProvider(KYSELY_CONNECTION).useValue(testDb);
  }

  const moduleFixture: TestingModule = await builder.compile();

  const app = moduleFixture.createNestApplication<NestFastifyApplication>(
    new FastifyAdapter()
  );

  // Match production configuration
  app.setGlobalPrefix('api');

  await app.init();
  await app.getHttpAdapter().getInstance().ready();

  return app;
}

/**
 * Close test application
 */
export async function closeTestApp(app: NestFastifyApplication): Promise<void> {
  if (app) {
    await app.close();
  }
}

/**
 * Generate test UUID
 */
export function generateTestId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Test data factories
 */
export const TestDataFactory = {
  /**
   * Create test ACCOUNT data
   */
  createACCOUNT(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      email: `Test Email ${uid}`,
      phone: `Test Phone ${uid}`,
      created_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test CONTACT data
   */
  createCONTACT(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      first_name: `Test First Name ${uid}`,
      last_name: `Test Last Name ${uid}`,
      email: `Test Email ${uid}`,
      phone: `Test Phone ${uid}`,
      account_id: 1,
      created_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test OPPORTUNITY data
   */
  createOPPORTUNITY(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      name: `Test Name ${uid}`,
      amount: 10.99,
      stage: `Test Stage ${uid}`,
      account_id: 1,
      close_date: new Date().toISOString(),
      created_at: new Date().toISOString(),
      ...overrides,
    };
  },

  /**
   * Create test ACTIVITY data
   */
  createACTIVITY(overrides: Partial<any> = {}): any {
    const uid = generateTestId().slice(0, 8);
    return {
      id: generateTestId(),
      type: `Test Type ${uid}`,
      description: `Test Description ${uid}`,
      contact_id: 1,
      opportunity_id: 1,
      activity_date: new Date().toISOString(),
      created_at: new Date().toISOString(),
      ...overrides,
    };
  },

};

/**
 * Clean up test data from database
 */
export async function cleanupTestData(): Promise<void> {
  const db = await initTestDatabase();

  // Delete in reverse order of dependencies
  try {
    await db.deleteFrom('bus_account').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_contact').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_opportunity').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
  try {
    await db.deleteFrom('bus_activity').execute();
  } catch (_e) {
    // Table may not exist, continue
  }
}

/**
 * Reset test database state
 */
export async function resetDatabase(): Promise<void> {
  await cleanupTestData();
}
